program MiniBroker;

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,
  Vcl.Forms,
  System.SysUtils,
  MyForm in 'mypatterns\MyForm.pas' {formMyForm},
  MyQuery in 'mypatterns\MyQuery.pas',
  MyUtil in 'mypatterns\MyUtil.pas',
  MyCdBasic in 'mypatterns\MyCdBasic.pas' {formMyCdBasic},
  MyCdMasterDetail in 'mypatterns\MyCdMasterDetail.pas' {formMyCdMasterDetail},
  MyAuditoria in 'mypatterns\MyAuditoria.pas',
  MyAuditoriaConsulta in 'mypatterns\MyAuditoriaConsulta.pas' {formMyauditoriaConsulta},
  MyMainBasic in 'mypatterns\MyMainBasic.pas' {formMyMainBasic},
  MyMainEnterprise in 'mypatterns\MyMainEnterprise.pas' {formMyMainEnterprise},
  FrMain in 'FrMain.pas' {formMain},
  FrBancoDeDados in 'FrBancoDeDados.pas' {formFrBancoDados},
  DatabaseSettings in 'DatabaseSettings.pas',
  MyGlobal in 'mypatterns\MyGlobal.pas',
  MyEntitiesBroker in 'mypatterns\MyEntitiesBroker.pas',
  ConnectionModule in 'ConnectionModule.pas' {FireDacMSSQLConnection: TDataModule},
  CdProcesso in 'CdProcesso.pas' {formMyCdProcesso},
  MyDgOk in 'mypatterns\MyDgOk.pas' {formMyDgOk},
  CdProcessoCtx in 'CdProcessoCtx.pas' {formMyCdProcessoCtx},
  MyFrameData in 'mypatterns\MyFrameData.pas' {FrameData: TFrame},
  MyFramePeriodo in 'mypatterns\MyFramePeriodo.pas' {FramePeriodo: TFrame},
  FmUnidadeNegocio in 'FmUnidadeNegocio.pas' {FrameUnidadeNegocio: TFrame},
  FmProduto in 'FmProduto.pas' {FrameProduto: TFrame},
  MyDialog in 'mypatterns\MyDialog.pas',
  CdEnquadramento in 'CdEnquadramento.pas' {formMyCdEnquadramento},
  MvProcessoDue in 'MvProcessoDue.pas' {formMvProcessoDue},
  FrSQLMonitor in 'FrSQLMonitor.pas' {formSQLMonitor},
  FrPesquisa in 'FrPesquisa.pas' {formMyPesquisa},
  FmRecintoAlfandegado in 'FmRecintoAlfandegado.pas' {FrameRecintoAlfandegado: TFrame},
  FmPais in 'FmPais.pas' {FramePais: TFrame},
  FmMoeda in 'FmMoeda.pas' {FrameMoeda: TFrame},
  FmEnquadramento in 'FmEnquadramento.pas' {FrameEnquadramento: TFrame},
  FmURF in 'FmURF.pas' {FrameURF: TFrame},
  FmIncoterm in 'FmIncoterm.pas' {FrameIncoterm: TFrame},
  MvProcessoDueNF in 'MvProcessoDueNF.pas' {formMvProcessoDueNF},
  FrIntegracaoDUE in 'FrIntegracaoDUE.pas' {formIntegracaoDue},
  FmDetail in 'FmDetail.pas' {FrameDetail: TFrame},
  FmNCMDestaque in 'FmNCMDestaque.pas' {FrameNCMDestaque: TFrame},
  DevExpressBR in 'mypatterns\DevExpressBR.pas',
  FmEmpresaNac in 'FmEmpresaNac.pas' {FrameEmpresaNac: TFrame},
  ClassesXMLDUE in 'ClassesXMLDUE.pas',
  CdRegraObservacoesAuto in 'CdRegraObservacoesAuto.pas' {formMyCdRegraObservacoesAuto},
  CdRegraTabelaCampo in 'CdRegraTabelaCampo.pas' {FormCdRegraTabelaCampo},
  xsdDue in 'xsdDue.pas',
  xsdDueDataModel in 'xsdDueDataModel.pas',
  frAjuda in 'frAjuda.pas' {formAjuda},
  MyEntitiesV2 in 'mypatterns\MyEntitiesV2.pas',
  uWalletBank in 'Wallet\uWalletBank.pas' {frmWalletBank},
  uWalletAuthUser in 'Wallet\uWalletAuthUser.pas' {frmWalletAuthUser},
  uWalletBranch in 'Wallet\uWalletBranch.pas' {frmWalletBranch},
  uWalletCountry in 'Wallet\uWalletCountry.pas' {FrmWalletCountry},
  uWalletItem in 'Wallet\uWalletItem.pas' {FrmWalletItem},
  ConnectionModuleV2 in 'Wallet\ConnectionModuleV2.pas' {FireDacMSSQLConnectionV2: TDataModule},
  uWalletOrganization in 'Wallet\uWalletOrganization.pas' {frmWalletOrganization},
  uWalletService in 'Wallet\uWalletService.pas' {frmWalletService},
  uWalletProductService in 'Wallet\uWalletProductService.pas' {frmWalletProductService},
  uWalletBeneficiaryAccount in 'Wallet\uWalletBeneficiaryAccount.pas' {frmWalletBeneficiaryAccount},
  uWalletCustomerGroup in 'Wallet\uWalletCustomerGroup.pas' {frmWalletCustomerGroup},
  uWalletCtx in 'Wallet\uWalletCtx.pas' {frmWalletCtx},
  uWalletCustomer in 'Wallet\uWalletCustomer.pas' {frmWalletCustomer},
  uWalletPagamentos in 'Wallet\uWalletPagamentos.pas' {frmWalletPagamentos},
  uWalletWSDL_CadClientes in 'Wallet\WSDL\uWalletWSDL_CadClientes.pas',
  uWalletWSDL_CadFornecedores in 'Wallet\WSDL\uWalletWSDL_CadFornecedores.pas',
  uWalletWSDL_CadPedidos in 'Wallet\WSDL\uWalletWSDL_CadPedidos.pas',
  uWalletWSDL_CadProcessos in 'Wallet\WSDL\uWalletWSDL_CadProcessos.pas',
  uWalletWSDL_Pagamentos_Senior in 'Wallet\WSDL\uWalletWSDL_Pagamentos_Senior.pas',
  uWalletWSDL_Numerarios_CRE_Senior in 'Wallet\WSDL\uWalletWSDL_Numerarios_CRE_Senior.pas',
  uWalletWSDL_Numerarios_CRE in 'Wallet\WSDL\uWalletWSDL_Numerarios_CRE.pas',
  uWalletNumerarios in 'Wallet\uWalletNumerarios.pas' {frmWalletNumerarios},
  uWalletSolicitacaoPagamento in 'Wallet\uWalletSolicitacaoPagamento.pas' {frmWalletSolicitacaoPagamento},
  uWalletPagamentosReplicar in 'Wallet\uWalletPagamentosReplicar.pas' {frmWalletPagamentosReplicar},
  uWalletGerarArquivos in 'Wallet\uWalletGerarArquivos.pas' {frmWalletGerarArquivos},
  uWalletImpressaoNumerarioImpo in 'Wallet\uWalletImpressaoNumerarioImpo.pas' {frmWalletImpressaoNumerarioImpo},
  uWalletImpressaoNumerarioExpo in 'Wallet\uWalletImpressaoNumerarioExpo.pas' {frmWalletImpressaoNumerarioExpo},
  GravaArquivoDigitalizacao in 'GravaArquivoDigitalizacao.pas',
  uWalletSelecionaImpostos in 'Wallet\uWalletSelecionaImpostos.pas' {frmWalletSelecionaImpostos},
  uWalletWSDL_Pagamentos in 'Wallet\WSDL\uWalletWSDL_Pagamentos.pas',
  uWalletWSDL_Pagamentos_Producao in 'Wallet\WSDL\uWalletWSDL_Pagamentos_Producao.pas',
  uWalletPagamentosTransferir in 'Wallet\uWalletPagamentosTransferir.pas' {frmWalletPagamentosTransferir},
  uWalletNumerariosReplicar in 'Wallet\uWalletNumerariosReplicar.pas' {frmWalletNumerariosReplicar},
  FmDetailCx in 'FmDetailCx.pas' {FrameDetailCX: TFrame},
  uWalletCustomerGroupCPFrame in 'Wallet\uWalletCustomerGroupCPFrame.pas' {FrameWalletCustomerGroupCP: TFrame},
  uWalletFrameBuscaProcesso in 'Wallet\uWalletFrameBuscaProcesso.pas' {FrameWalletPesquisaProcesso: TFrame},
  uWalletPreFaturamento in 'Wallet\uWalletPreFaturamento.pas' {frmWalletPreFaturamento},
  FrmDraftBL in 'FrmDraftBL.pas' {frmCdDraftBL},
  FrBuscaProcessos in 'FrBuscaProcessos.pas' {FrBuscaProcessos: TFrame},
  FrmDraftBLComentarios in 'FrmDraftBLComentarios.pas' {frameDraftBLComentarios: TFrame},
  FmDraftBLCtx in 'FmDraftBLCtx.pas' {frmDraftBlCtx},
  FrmDraftBLMercContainer in 'FrmDraftBLMercContainer.pas' {FramDraftBLMercContainer: TFrame},
  frmDraftBLMercadoria in 'frmDraftBLMercadoria.pas' {frameDraftBLMercadoria: TFrame},
  uGerarArquivosDraft in 'uGerarArquivosDraft.pas' {frmGerarArquivosDraft},
  uImpressaoDraftPadraoInttra in 'uImpressaoDraftPadraoInttra.pas' {frmImpressaoDraftPadraoInttra},
  uMySFTPClient in 'componentes\SFTP\uMySFTPClient.pas',
  libssh2 in 'componentes\SFTP\libssh2.pas',
  libssh2_sftp in 'componentes\SFTP\libssh2_sftp.pas',
  CdDescricaoMercadoriaDraft in 'CdDescricaoMercadoriaDraft.pas' {formMyCdDescricaoMercadoriaDraft},
  FrMercadoriasCadDescMercadoria in 'FrMercadoriasCadDescMercadoria.pas' {formMercadoriasCadDescMercadoria},
  DmGerarArquivosDraft in 'DmGerarArquivosDraft.pas' {dtmGerarArquivosDraft: TDataModule},
  frmRelatoriodraft in 'frmRelatoriodraft.pas' {formRelatorioDraft},
  CdConfiguracoes in 'CdConfiguracoes.pas' {formConfiguracoes},
  dmConfiguracoes in 'dmConfiguracoes.pas' {dtmConfiguracoes: TDataModule};

//gpprof in 'D:\Aplicativos\Delphi\gpprf133\gpprof.pas',
  //gpprofh in 'D:\Aplicativos\Delphi\gpprf133\gpprofh.pas';

{$R *.res}

begin
  //ReportMemoryLeaksOnShutdown := DebugHook <> 0;
  Application.Initialize;
  Application.MainFormOnTaskbar := true;
  Application.CreateForm(TformMain, formMain);
  Application.CreateForm(TformAjuda, formAjuda);
//  Application.CreateForm(TdtmConfiguracoes, dtmConfiguracoes);
  sUsuario  := ExtractFileName(ParamStr(2));
  sSenha    := ExtractFileName(ParamStr(4));
  sMenu     := ExtractFileName(ParamStr(6));
  sProcesso := ExtractFileName(ParamStr(8));
  Application.Run;
end.
