WITH TP AS(
	SELECT 
	  NR_PROCESSO,
	  CD_CLIENTE,
	  CD_PAIS_DESTINO,
	  CD_CANAL,
	  TX_MERCADORIA,
	  VL_PESO_BRUTO,
	  VL_PESO_LIQUIDO
	FROM TPROCESSO
	WHERE NR_PROCESSO IN ('0102EA-000001-18','0102EA-000002-18')
)
SELECT 
TP.NR_PROCESSO,
EN.NM_EMPRESA AS [CLIENTE],
DBO.FN_CONCATENA_REFRENCIA_TIPO(TP.NR_PROCESSO, G.TP_PEDIDO_BUSCA) AS [REFERÊNCIA CLIENTE],
PD.DESCRICAO AS [PAIS DE DESTINO],
CA.NM_CANAL AS [CANAL],
TP.TX_MERCADORIA AS [MERCADORIA],
TP.VL_PESO_BRUTO AS [PESO BRUTO],
TP.VL_PESO_LIQUIDO AS [PESO LIQUIDO],
(SELECT COUNT(CNT.NR_CNTR) FROM TPROCESSO_CNTR CNT WHERE CNT.NR_PROCESSO=TP.NR_PROCESSO) AS [QTDE CNTRS],
EV113.DT_REALIZACAO AS [LIBERAÇÃO DO PROCESSO],
EV314.DT_REALIZACAO AS [CARREGAMENTO NA FÁBRICA],
EV088.DT_REALIZACAO AS [DESEMBARAÇO],
ISNULL(EV149.DT_REALIZACAO,EV132.DT_REALIZACAO) AS [SAÍDA NAVIO/CAMINHÃO/VOO OU CRUZE],
FUP.CD_EVENTO AS [Código],
EV.NM_EVENTO AS [Evento],
CONVERT(VARCHAR(10),FUP.DT_PREVISTA,103) AS [Previsto],
CONVERT(VARCHAR(10),FUP.DT_REALIZACAO,103) AS [Realizado]
FROM TP
INNER JOIN TEMPRESA_NAC EN ON EN.CD_EMPRESA=TP.CD_CLIENTE
INNER JOIN BROKER.DBO.TGRUPO G ON G.CD_GRUPO=EN.CD_GRUPO
INNER JOIN BROKER.DBO.TTP_CANAL CA ON CA.CD_CANAL=TP.CD_CANAL
LEFT JOIN BROKER.DBO.TPAIS PD ON PD.CODIGO=TP.CD_PAIS_DESTINO
LEFT JOIN BROKER.DBO.TFOLLOWUP EV113 ON EV113.NR_PROCESSO=TP.NR_PROCESSO AND EV113.CD_EVENTO='113' AND EV113.IN_APLICAVEL='1'
LEFT JOIN BROKER.DBO.TFOLLOWUP EV314 ON EV314.NR_PROCESSO=TP.NR_PROCESSO AND EV314.CD_EVENTO='311' AND EV113.IN_APLICAVEL='1'
LEFT JOIN BROKER.DBO.TFOLLOWUP EV088 ON EV088.NR_PROCESSO=TP.NR_PROCESSO AND EV088.CD_EVENTO='088' AND EV113.IN_APLICAVEL='1'
LEFT JOIN BROKER.DBO.TFOLLOWUP EV149 ON EV149.NR_PROCESSO=TP.NR_PROCESSO AND EV149.CD_EVENTO='149' AND EV113.IN_APLICAVEL='1'
LEFT JOIN BROKER.DBO.TFOLLOWUP EV132 ON EV132.NR_PROCESSO=TP.NR_PROCESSO AND EV132.CD_EVENTO='132' AND EV113.IN_APLICAVEL='1'
LEFT JOIN BROKER.DBO.TFOLLOWUP FUP ON FUP.NR_PROCESSO=TP.NR_PROCESSO
LEFT JOIN BROKER.DBO.TEVENTO EV ON EV.CD_EVENTO=FUP.CD_EVENTO
ORDER BY TP.NR_PROCESSO
--SP_HELP TREF_CLIENTE


SELECT
FUP.CD_EVENTO AS [Código],
EV.NM_EVENTO AS [Evento],
CONVERT(VARCHAR(10),FUP.DT_PREVISTA,103) AS [Previsto],
CONVERT(VARCHAR(10),FUP.DT_REALIZACAO,103) AS [Realizado]
FROM TFOLLOWUP FUP
LEFT JOIN BROKER.DBO.TEVENTO EV ON EV.CD_EVENTO=FUP.CD_EVENTO
WHERE FUP.NR_PROCESSO='0102EM-000458-16'
ORDER BY FUP.NR_ORDEM

SELECT
'HTTP://WWW.MYINDAIAWEB.COM.BR/REDIRECIONA_DOC.ASP?COD=' + MASTER.DBO.FN_CRIPROGRAFA('DOCS_NOVO/0102EM-000458-16/CPAG01.PDF'),
TD.NM_TIPO_DOCTO AS [Tipo de Documento],
PD.NM_DESCRICAO AS [Descrição],
CONVERT(VARCHAR(10),PD.DT_CRIACAO,103) AS [Data criação],
PD.NM_ARQUIVO AS [Nome do Arquivo]
FROM TPROCESSO_DOCTOS PD
LEFT JOIN BROKER.DBO.TTP_DOCTO_DIGITALIZADO TD ON
TD.CD_TIPO_DOCTO=PD.CD_TIPO_DOCTO
WHERE PD.NR_PROCESSO='0102EM-000458-16'

\\indaiaweb\digitalizacao_novo\TPROCESSO\0101IM-002275-16