unit Consultas;

interface

  function getSelectNestleOF: String;
  function getSelectNestleLI: String;

implementation


function getSelectNestleOF: String;
begin
  result :=
    'SELECT ' + #13#10 +
    'Cast(ISNULL(STUFF((SELECT DISTINCT '', '' + LTRIM(RTRIM(R.CD_REFERENCIA)) ' + #13#10 +
    'FROM BROKER.DBO.TREF_CLIENTE R WITH (NOLOCK) ' + #13#10 +
    'WHERE R.NR_PROCESSO = TP.NR_PROCESSO ' + #13#10 +
    'AND R.TP_REFERENCIA = ''05'' ' + #13#10 +
    'FOR XML PATH('''')), 1, 1, ''''), '''') as Varchar(300)) AS [Carrier Booking Number], ' + #13#10 +
    'A.NM_AGENTE AS [Carrier SCAC], ' + #13#10 +
    'EN.COD_INTERNO AS [Nestle Owning Entity], ' + #13#10 +
    'EN.NM_EMPRESA AS [Shipper], ' + #13#10 +
    'EE.NM_EMPRESA AS [Importer], ' + #13#10 +
    'EE1.NM_EMPRESA AS [Consignee], ' + #13#10 +
    'Cast(ISNULL(STUFF((SELECT DISTINCT '', '' + LTRIM(RTRIM(R.CD_REFERENCIA)) ' + #13#10 +
    'FROM BROKER.DBO.TREF_CLIENTE R WITH (NOLOCK) ' + #13#10 +
    'WHERE R.NR_PROCESSO = TP.NR_PROCESSO ' + #13#10 +
    'AND R.TP_REFERENCIA = ''01'' ' + #13#10 +
    'FOR XML PATH('''')), 1, 1, ''''), '''') as Varchar(300)) AS [Importer PO reference], ' + #13#10 +
    'Cast(ISNULL(STUFF((SELECT DISTINCT '', '' + LTRIM(RTRIM(PC.NR_CNTR)) ' + #13#10 +
    'FROM BROKER.DBO.TPROCESSO_CNTR PC WITH (NOLOCK) ' + #13#10 +
    'WHERE PC.NR_PROCESSO = TP.NR_PROCESSO ' + #13#10 +
    'FOR XML PATH('''')), 1, 1, ''''), '''') as Varchar(300)) AS [Container Number] ' + #13#10 +
    'FROM BROKER.DBO.TPROCESSO TP (NOLOCK) ' + #13#10 +
    'INNER JOIN BROKER.DBO.TSERVICO_NOVO SN (NOLOCK) ON SN.CD_SERVICO = TP.CD_SERVICO ' + #13#10 +
    'INNER JOIN BROKER.DBO.TVIA_TRANSP_BROKER VT (NOLOCK) ON VT.CD_VIA_TRANSP = SN.CD_VIA_TRANSPORTE ' + #13#10 +
    'INNER JOIN BROKER.DBO.TEMPRESA_NAC EN (NOLOCK) ON EN.CD_EMPRESA = TP.CD_CLIENTE ' + #13#10 +
    'LEFT JOIN BROKER.DBO.TAGENTE A (NOLOCK) ON A.CD_AGENTE = TP.CD_AGENTE ' + #13#10 +
    'LEFT JOIN BROKER.DBO.TFOLLOWUP EV132 (NOLOCK) ON EV132.NR_PROCESSO = TP.NR_PROCESSO AND EV132.CD_EVENTO=''132'' ' + #13#10 +
    'LEFT JOIN BROKER.DBO.TPROCESSO_EXP PE (NOLOCK) ON PE.NR_PROCESSO = TP.NR_PROCESSO ' + #13#10 +
    'LEFT JOIN BROKER.DBO.TEMPRESA_EST EE (NOLOCK) ON EE.CD_EMPRESA = PE.CD_IMPORTADOR ' + #13#10 +
    'LEFT JOIN BROKER.DBO.TEMPRESA_EST EE1 (NOLOCK) ON EE1.CD_EMPRESA = PE.CD_CONSIGNATARIO ' + #13#10 +
    'WHERE TP.CD_GRUPO=''155'' ' + #13#10 +
    'AND TP.CD_PRODUTO=''02'' ' + #13#10 +
    'AND TP.IN_CANCELADO=''0'' ' + #13#10 +
    'AND TP.CD_CLIENTE NOT IN (''02594'',''02932'',''01983'',''02576'',''02945'') ' + #13#10 +
    'AND  EE.NM_EMPRESA LIKE ''%NESTL%'' ' + #13#10 +
    'AND VT.CD_VIA_TRANSP=''01'' ' + #13#10 +
    'AND CONVERT(DATE,EV132.DT_REALIZACAO) > CONVERT(DATE,GETDATE()-9) ';
end;

function getSelectNestleLI: String;
begin
  result :=
    ' SELECT ' + #13#10 +
    '   VT.NM_VIA_TRANSP AS [Via_Transporte] ' + #13#10 +
    '   ,TP.NR_PROCESSO AS [RefIndaia] ' + #13#10 +
    '   ,Cast(ISNULL(STUFF((SELECT DISTINCT '', '' + LTRIM(RTRIM(R.CD_REFERENCIA)) ' + #13#10 +
    '                     FROM BROKER.DBO.TREF_CLIENTE R WITH (NOLOCK) ' + #13#10 +
    '                     WHERE R.NR_PROCESSO   = TP.NR_PROCESSO ' + #13#10 +
    '                       AND R.TP_REFERENCIA = ''01'' ' + #13#10 +
    '             FOR XML PATH('''')), 1, 1, ''''), '''') as Varchar(300)) AS [RefCliente] ' + #13#10 +
    '   ,EN.NM_EMPRESA AS [Cliente] ' + #13#10 +
    '   ,SUBSTRING(EN.CGC_EMPRESA,1,2) + ''.'' + SUBSTRING(EN.CGC_EMPRESA,3,3) + ''.'' + SUBSTRING(EN.CGC_EMPRESA,6,3) + ''/'' + SUBSTRING(EN.CGC_EMPRESA,9,4) + ''-'' + SUBSTRING(EN.CGC_EMPRESA,13,2) AS [CNPJ] ' + #13#10 +
    '   ,A.NM_AREA AS [Area] ' + #13#10 +
    '   ,TP.TX_MERCADORIA AS [Mercadoria] ' + #13#10 +
    '   ,EE.NM_EMPRESA AS [Exportador] ' + #13#10 +
    '   ,PE.NM_PAIS AS [PaisExportador] ' + #13#10 +
    '   ,Cast(ISNULL(STUFF((SELECT DISTINCT '', '' + LTRIM(RTRIM(R.CD_REFERENCIA)) ' + #13#10 +
    '                     FROM BROKER.DBO.TREF_CLIENTE R WITH (NOLOCK) ' + #13#10 +
    '                     WHERE R.NR_PROCESSO   = TP.NR_PROCESSO ' + #13#10 +
    '                       AND R.TP_REFERENCIA = ''34'' ' + #13#10 +
    '             FOR XML PATH('''')), 1, 1, ''''), '''') as Varchar(300)) AS [RefExportador] ' + #13#10 +
    '   ,EEF.NM_EMPRESA AS [Fabricante] ' + #13#10 +
    '   ,PF.NM_PAIS AS [PaisOrigem] ' + #13#10 +
    '   ,LE.DESCRICAO AS [LocalDesembarque] ' + #13#10 +
    '   ,TP.VL_PESO_LIQUIDO AS [PesoLiquido] ' + #13#10 +
    '   ,TP.VL_PESO_BRUTO AS [PesoBruto] ' + #13#10 +
    '   ,MM.AP_MOEDA AS [MoedaMercCondVenda] ' + #13#10 +
    '   ,TP.VL_MLE_MNEG AS [ValorFOB] ' + #13#10 +
    '   ,TP.CD_INCOTERM AS [Incoterm] ' + #13#10 +
    '   ,CASE WHEN EV168.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV168.DT_REALIZACAO,103) END AS [DataPedidoSAP] ' + #13#10 +
    '   ,CASE WHEN EV425.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV425.DT_REALIZACAO,103) END AS [EnvioShippingInstruction] ' + #13#10 +
    '   ,CASE WHEN EV219.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV219.DT_REALIZACAO,103) END AS [PedidoConfirmadoFornecedor] ' + #13#10 +
    '   ,CASE WHEN EV798.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV798.DT_REALIZACAO,103) END AS [NecessidadeFabrica] ' + #13#10 +
    '   ,CASE WHEN EV233.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV233.DT_REALIZACAO,103) END AS [DeliveryDateRevisada] ' + #13#10 +
    '   ,CASE WHEN EV486.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV486.DT_REALIZACAO,103) END AS [DataEmbarqueSolicitada] ' + #13#10 +
    '   ,CASE WHEN EV506.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV506.DT_REALIZACAO,103) END AS [PrevisaoProntidaoCarga] ' + #13#10 +
    '   ,CASE WHEN EV421.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV421.DT_REALIZACAO,103) END AS [ProntidaoCarga] ' + #13#10 +
    '   ,CASE WHEN EV131.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV131.DT_REALIZACAO,103) END AS [PrevisaoEmbarque] ' + #13#10 +
    '   ,CASE WHEN EV551.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV551.DT_REALIZACAO,103) END AS [DataEmbarque] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_SOLICITACAO,103) AS [SolicitacaoLI] ' + #13#10 +
    '   ,PLI.NR_LI AS [NumeroLI] ' + #13#10 +
    '   ,PLI.NR_DOSSIE_POS AS [NumeroLPCO] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_REGISTRO,103) AS [RegistroLISISCOMEX] ' + #13#10 +
    '   ,PLIOA.CD_ORGAO_ANUENTE AS [OrgaoAnuente] ' + #13#10 +
    '   ,PLIS.TX_STATUS AS [Status] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLIS.DT_STATUS,103) AS [DataStatus] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_SOLICITACAO_REQUISITO,103) AS [SolicitacaoRequisitos] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_RECEPCAO_REQ_SANITARIO,103) AS [RecepcaoRequisito] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_FIN_DOSSIE,103) AS [FinalizacaoDossie] ' + #13#10 +
    '   ,PLI.NR_DOSSIE as [NrDossie] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_LECOM,103) AS [DataLecom] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLIOA.DT_ENTR_PROC,103) AS [ProtocoloMAPA] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_LI_AUTORIZADA,103) AS [AutorizacaoEmbarque] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),EV660.DT_REALIZACAO+90,103) AS [VencimentoAutorizacao] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_PROTOCOLO_REMOTO_OK,103) AS [ProtocoloRemoto] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_DOCTOS_DOSSIE,103) AS [SolicitacaoParametrizacaoLPCO] ' + #13#10 +
    '   ,CASE WHEN PLI.IN_INSPECAO=''1'' THEN ''Sim'' ELSE ''Não'' END AS [InInspecao] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_INSPECAO,103) AS [DataInspecao] ' + #13#10 +
    '   ,CASE WHEN PLI.IN_COLETA_AMOSTRA=''1'' THEN ''Sim'' ELSE ''Não'' END AS [InColetaAmostra] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_COLETA_AMOSTRA,103) AS [DataAmostra] ' + #13#10 +
    '   ,PLI.NR_INFA AS [NrINFA] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLIOA.DT_DEFERIMENTO,103) AS [DeferimentoLI] ' + #13#10 +
    '   ,PLI.TX_OBS_LI_NOVA_SUB AS [MotivoLISUB] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_EMISSAO_GRU,103) AS [EmissaoGRU] ' + #13#10 +
    '   ,PLI.NR_TRANSACAO_GRU AS [NumeroTransacao] ' + #13#10 +
    '   ,CONVERT(VARCHAR(10),PLI.DT_PGMTO_GRU,103) AS [PagamentoGRU] ' + #13#10 +
    '   ,CASE WHEN EV082.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV082.DT_REALIZACAO,103) END AS [DocumentosCompletosParaAnalise] ' + #13#10 +
    '   ,CASE WHEN EV416.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV416.DT_REALIZACAO,103) END AS [AnaliseDocumental] ' + #13#10 +
    '   ,CASE WHEN EV215.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV215.DT_REALIZACAO,103) END AS [RecepcaoBL] ' + #13#10 +
    '   ,NAV.NM_EMBARCACAO AS [Embarcacao] ' + #13#10 +
    '   ,AG.NM_AGENTE AS [ArmadorAgente] ' + #13#10 +
    '   ,CASE WHEN EV161.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV161.DT_REALIZACAO,103) END AS [PrevisaoChegadaModal] ' + #13#10 +
    '   ,CASE WHEN EV333.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV333.DT_REALIZACAO,103) END AS [PrevisaoChegadaDestino] ' + #13#10 +
    '   ,CASE WHEN EV162.IN_APLICAVEL=''0'' THEN ''N/A'' ELSE CONVERT(VARCHAR(10),EV162.DT_REALIZACAO,103) END AS [ChegadaNavioAviaoCaminhao] ' + #13#10 +
    '   ,CASE WHEN ISNULL(PLI.IN_EXIGENCIA, 0)=1 THEN ''Sim'' ELSE ''Não'' END AS [InExigencia] ' + #13#10 +
    ' FROM BROKER.DBO.TPROCESSO TP ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TLOCAL_EMBARQUE LE (NOLOCK) ON LE.CODIGO = TP.CD_LOCAL_DESEMBARQUE ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TEMBARCACAO NAV (NOLOCK) ON NAV.CD_EMBARCACAO = TP.CD_EMBARCACAO ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TAGENTE AG (NOLOCK) ON AG.CD_AGENTE = TP.CD_AGENTE ' + #13#10 +
    ' INNER JOIN BROKER.DBO.TAREA A (NOLOCK) ON A.CD_AREA = TP.CD_AREA ' + #13#10 +
    ' INNER JOIN BROKER.DBO.TEMPRESA_NAC EN (NOLOCK) ON EN.CD_EMPRESA = TP.CD_CLIENTE ' + #13#10 +
    ' INNER JOIN BROKER.DBO.TSERVICO_NOVO SN (NOLOCK) ON SN.CD_SERVICO = TP.CD_SERVICO ' + #13#10 +
    ' INNER JOIN BROKER.DBO.TVIA_TRANSP_BROKER VT (NOLOCK) ON VT.CD_VIA_TRANSP = SN.CD_VIA_TRANSPORTE ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TEXPORTADOR_DI EDI (NOLOCK) ON EDI.NR_PROCESSO = TP.NR_PROCESSO ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TEMPRESA_EST EE (NOLOCK) ON EE.CD_EMPRESA = EDI.CD_EXPORTADOR ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TPAIS_BROKER PE (NOLOCK) ON PE.CD_PAIS = EE.CD_PAIS ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFABRICANTE_DI FDI (NOLOCK) ON FDI.NR_PROCESSO = TP.NR_PROCESSO ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TEMPRESA_EST EEF (NOLOCK) ON EEF.CD_EMPRESA = FDI.CD_FABRICANTE ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TPAIS_BROKER PF (NOLOCK) ON PF.CD_PAIS = EEF.CD_PAIS ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TMOEDA_BROKER MM (NOLOCK) ON MM.CD_MOEDA = TP.CD_MOEDA_MLE ' + #13#10 +
    ' INNER JOIN BROKER.DBO.TPROCESSO_LI PLI (NOLOCK) ON PLI.NR_PROCESSO = TP.NR_PROCESSO ' + #13#10 +
    ' INNER JOIN BROKER.DBO.TPROCESSO_LI_ORGAO_ANUENTE PLIOA (NOLOCK) ON PLIOA.NR_LI = PLI.NR_LI ' + #13#10 +
    ' 																AND PLIOA.NR_PROCESSO = PLI.NR_PROCESSO ' + #13#10 +
    ' JOIN BROKER.DBO.TPROCESSO_LI_STATUS PLIS (NOLOCK) ON PLIS.NR_PROCESSO = PLI.NR_PROCESSO ' + #13#10 +
    ' 												 AND PLIS.NR_LI       = PLI.NR_LI ' + #13#10 +
    ' 												 AND PLIS.CD_ORGAO_ANUENTE = PLIOA.CD_ORGAO_ANUENTE ' + #13#10 +
    ' 												 AND PLIS.DT_STATUS_EFETIVA = (SELECT MAX(DT_STATUS_EFETIVA) ' + #13#10 +
    '                                                                         FROM BROKER.DBO.TPROCESSO_LI_STATUS A  (NOLOCK) ' + #13#10 +
    '                                                                        WHERE A.NR_PROCESSO      = PLI.NR_PROCESSO ' + #13#10 +
    '                                                                          AND A.NR_LI            = PLI.NR_LI ' + #13#10 +
    '                                                                          AND A.CD_ORGAO_ANUENTE = PLIOA.CD_ORGAO_ANUENTE   ) ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV021 (NOLOCK) ON EV021.NR_PROCESSO = TP.NR_PROCESSO AND EV021.CD_EVENTO=''021'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV082 (NOLOCK) ON EV082.NR_PROCESSO = TP.NR_PROCESSO AND EV082.CD_EVENTO=''082'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV131 (NOLOCK) ON EV131.NR_PROCESSO = TP.NR_PROCESSO AND EV131.CD_EVENTO=''131'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV161 (NOLOCK) ON EV161.NR_PROCESSO = TP.NR_PROCESSO AND EV161.CD_EVENTO=''161'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV162 (NOLOCK) ON EV162.NR_PROCESSO = TP.NR_PROCESSO AND EV162.CD_EVENTO=''162'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV164 (NOLOCK) ON EV164.NR_PROCESSO = TP.NR_PROCESSO AND EV164.CD_EVENTO=''164'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV168 (NOLOCK) ON EV168.NR_PROCESSO = TP.NR_PROCESSO AND EV168.CD_EVENTO=''168'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV215 (NOLOCK) ON EV215.NR_PROCESSO = TP.NR_PROCESSO AND EV215.CD_EVENTO=''215'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV219 (NOLOCK) ON EV219.NR_PROCESSO = TP.NR_PROCESSO AND EV219.CD_EVENTO=''219'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV233 (NOLOCK) ON EV233.NR_PROCESSO = TP.NR_PROCESSO AND EV233.CD_EVENTO=''233'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV333 (NOLOCK) ON EV333.NR_PROCESSO = TP.NR_PROCESSO AND EV333.CD_EVENTO=''333'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV350 (NOLOCK) ON EV350.NR_PROCESSO = TP.NR_PROCESSO AND EV350.CD_EVENTO=''350'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV416 (NOLOCK) ON EV416.NR_PROCESSO = TP.NR_PROCESSO AND EV416.CD_EVENTO=''416'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV421 (NOLOCK) ON EV421.NR_PROCESSO = TP.NR_PROCESSO AND EV421.CD_EVENTO=''421'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV425 (NOLOCK) ON EV425.NR_PROCESSO = TP.NR_PROCESSO AND EV425.CD_EVENTO=''425'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV486 (NOLOCK) ON EV486.NR_PROCESSO = TP.NR_PROCESSO AND EV486.CD_EVENTO=''486'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV506 (NOLOCK) ON EV506.NR_PROCESSO = TP.NR_PROCESSO AND EV506.CD_EVENTO=''506'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV551 (NOLOCK) ON EV551.NR_PROCESSO = TP.NR_PROCESSO AND EV551.CD_EVENTO=''551'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV660 (NOLOCK) ON EV660.NR_PROCESSO = TP.NR_PROCESSO AND EV660.CD_EVENTO=''660'' ' + #13#10 +
    ' LEFT JOIN BROKER.DBO.TFOLLOWUP EV798 (NOLOCK) ON EV798.NR_PROCESSO = TP.NR_PROCESSO AND EV798.CD_EVENTO=''798'' ' + #13#10 +
    ' WHERE ' + #13#10 +
//    '   ( EV021.DT_REALIZACAO IS NULL AND EV350.DT_REALIZACAO IS NOT NULL ) ' + #13#10 +
//    '   AND ( EV021.IN_APLICAVEL=''1'' AND EV350.IN_APLICAVEL=''1'' ) ' + #13#10 +
    '   ( EV164.DT_REALIZACAO IS NULL OR EV164.DT_REALIZACAO > GETDATE()-6 ) ' + #13#10 +
    '   AND EV164.IN_APLICAVEL=''1''         ' + #13#10 +
    '   AND TP.CD_GRUPO=''155'' ' + #13#10 +
    '   AND TP.CD_PRODUTO=''01'' ' + #13#10 +
    '   AND TP.IN_CANCELADO=''0'' ';

end;

end.
