object atz_webForm: Tatz_webForm
  Left = 200
  Top = 104
  Width = 544
  Height = 375
  Caption = 'Atualiza WEB'
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  PixelsPerInch = 96
  TextHeight = 13
  object db_proc_web: TDatabase
    AliasName = 'DBPROCWEB'
    SessionName = 'Default'
    Left = 22
    Top = 16
  end
end
