program DDBroker;

uses
  ShareMem,
  Forms,
  Controls,
  Graphics,
  Windows,
  Dialogs,
  SysUtils,
  DBTables,
  Registry,
  DevExpressBR in 'DevExpressBR.pas',
  PGBF001 in 'PGBF001.pas' {frm_integra_basf},
  PGBF002 in 'PGBF002.pas' {datm_integra_basf: TDataModule},
  PGCH009 in 'PGCH009.pas' {frm_sel_data},
  PGCH012 in 'PGCH012.pas' {frm_ent_ch_br},
  PGCH013 in 'PGCH013.pas' {datm_ent_ch_br: TDataModule},
  PGCH016 in 'PGCH016.pas' {frm_cheque_avulso},
  PGCH017 in 'PGCH017.pas' {datm_cheque_avulso: TDataModule},
  PGCH021 in 'PGCH021.pas' {frm_sel_mes_ano_produto},
  PGCH022 in 'PGCH022.pas' {datm_sel_mes_ano: TDataModule},
  PGCH029 in 'PGCH029.pas' {frm_sel_unid_cli_mes_ano},
  PGCH030 in 'PGCH030.pas' {datm_sel_unid_cli_mes_ano: TDataModule},
  PGCH032 in 'pgch032.pas' {frm_sel_cli_periodo},
  PGCH033 in 'pgch033.pas' {datm_sel_cli_periodo: TDataModule},
  PGCH038 in 'PGCH038.pas' {frm_sel_unid_prod_cli},
  PGCH039 in 'PGCH039.pas' {datm_sel_unid_prod_cli: TDataModule},
  PGDI001 in 'PGDI001.pas' {frm_DI_capa},
  PGDI003 in 'PGDI003.pas' {frm_DI},
  PGDI004 in 'PGDI004.pas' {frm_DI_adicao},
  PGDI005 in 'PGDI005.pas' {frm_DI_Itens},
  PGDI008 in 'PGDI008.pas' {frm_contrato_cambio_antec},
  PGDI009 in 'PGDI009.pas' {frm_contrato_cambio_avista},
  PGDI010 in 'PGDI010.pas' {frm_duplica_di},
  PGDI011 in 'PGDI011.pas' {frm_DI_NVE},
  PGDI014 in 'PGDI014.pas' {frm_Integracao_LI},
  PGDI015 in 'PGDI015.pas' {frm_DI_adicao_Com_LI},
  PGDI017 in 'PGDI017.pas' {datm_DI: TDataModule},
  PGDI018 in 'PGDI018.pas' {datm_DI_Capa: TDataModule},
  PGDI019 in 'PGDI019.pas' {datm_DI_Adicao: TDataModule},
  PGDI020 in 'PGDI020.pas' {datm_DI_Itens: TDataModule},
  PGDI022 in 'PGDI022.pas' {datm_duplica_di: TDataModule},
  PGDI025 in 'PGDI025.pas' {frm_rascunho_LI},
  PGDI026 in 'PGDI026.pas' {frm_imp_varias_di},
  PGDI027 in 'PGDI027.pas' {datm_imp_varias_di: TDataModule},
  PGDI029 in 'PGDI029.pas' {frm_recalc_proc},
  PGDI030 in 'PGDI030.pas' {datm_recalc_proc: TDataModule},
  PGDI031 in 'PGDI031.pas' {datm_integracao_li: TDataModule},
  PGDI032 in 'PGDI032.pas' {frm_DI_Resumo},
  PGDI033 in 'PGDI033.pas' {datm_DI_Resumo: TDataModule},
  PGDI034 in 'PGDI034.pas' {datm_DI_adicao_com_LI: TDataModule},
  PGDI036 in 'PGDI036.pas' {frm_AtualizaSISCOMEX},
  PGDI037 in 'PGDI037.pas' {datm_AtualizaSISCOMEX: TDataModule},
  PGES001 in 'PGES001.pas' {frm_tot_gastos_processo},
  PGES002 in 'PGES002.pas' {datm_tot_gastos_processo: TDataModule},
  PGES003 in 'PGES003.pas' {frm_tot_gastos_porto},
  PGES004 in 'PGES004.pas' {datm_tot_gastos_porto: TDataModule},
  PGFI001 in 'PGFI001.pas' {frm_financeiro},
  PGFI002 in 'PGFI002.pas' {datm_financeiro: TDataModule},
  PGFI009 in 'PGFI009.pas' {frm_sel_col_periodo},
  PGFI010 in 'PGFI010.pas' {datm_sel_col_periodo},
  PGFI011 in 'pgfi011.pas' {frm_sel_unid_prod_fin},
  PGFI012 in 'pgfi012.pas' {datm_sel_unid_prod_fin: TDataModule},
  PGFI013 in 'PGFI013.pas' {frm_sel_moeda_periodo},
  PGFI014 in 'PGFI014.pas' {datm_sel_moeda_periodo: TDataModule},
  PGFT001 in 'PGFT001.pas' {frm_fat_cc},
  PGFT002 in 'PGFT002.pas' {datm_fat_cc: TDataModule},
  PGFT003 in 'PGFT003.pas' {frm_fat_sol},
  PGFT004 in 'PGFT004.pas' {datm_fat_sol: TDataModule},
  pgft006 in 'pgft006.pas' {datm_sel_fat: TDataModule},
  PGFT009 in 'PGFT009.pas' {frm_sel_processo},
  PGFT010 in 'PGFT010.pas' {datm_sel_processo: TDataModule},
  PGFT011 in 'PGFT011.pas' {frm_cli_mes_ano},
  PGFT012 in 'PGFT012.pas' {datm_cli_mes_ano: TDataModule},
  PGFT013 in 'PGFT013.pas' {frm_imp_lanc_fat_cc},
  PGFT014 in 'PGFT014.pas' {datm_imp_lanc_fat_cc: TDataModule},
  PGFT019 in 'PGFT019.pas' {frm_sel_unid_cli},
  PGFT020 in 'PGFT020.pas' {datm_sel_unid_cli: TDataModule},
  PGFT021 in 'PGFT021.pas' {frm_livro_iss},
  PGFT022 in 'PGFT022.pas' {datm_livro_iss: TDataModule},
  PGFT023 in 'PGFT023.pas' {frm_imp_despesas_nao_faturaveis},
  PGFT024 in 'PGFT024.pas' {datm_imp_despesas_nao_faturaveis: TDataModule},
  PGFT025 in 'PGFT025.pas' {frm_imp_receitas_operacionais},
  PGFT026 in 'PGFT026.pas' {datm_imp_receitas_operacionais: TDataModule},
  PGFT031 in 'PGFT031.pas' {frm_previsao_custo},
  PGFT032 in 'PGFT032.pas' {datm_previsao_custo: TDataModule},
  PGGA003 in 'PGGA003.pas' {frm_proc_realiza},
  PGGA004 in 'PGGA004.pas' {datm_proc_realiza: TDataModule},
  PGGA011 in 'Pgga011.pas' {frm_evento_realizacao},
  PGGA012 in 'Pgga012.pas' {datm_evento_realizacao: TDataModule},
  PGGA013 in 'PGGA013.pas' {frm_rel_proc_pend},
  PGGA014 in 'PGGA014.pas' {datm_rel_proc_pend: TDataModule},
  PGGA019 in 'PGGA019.pas' {frm_repassa_dados},
  PGGA020 in 'PGGA020.pas' {datm_repassa_dados: TDataModule},
  PGGA023 in 'PGGA023.pas' {frm_sel_unid_prod_via},
  PGGA024 in 'PGGA024.pas' {datm_sel_unid_prod_via: TDataModule},
  PGGP001 in 'PGGP001.pas' {frm_main},
  PGGP002 in 'PGGP002.pas' {frm_consulta_li},
  PGGP003 in 'PGGP003.pas' {frm_senha},
  PGGP004 in 'PGGP004.pas' {frm_splash},
  PGGP006 in 'PGGP006.pas' {datm_consulta_li: TDataModule},
  PGGP013 in 'PGGP013.pas' {frm_lib_ctaapagar},
  PGGP014 in 'PGGP014.pas' {datm_lib_ctaapagar: TDataModule},
  PGGP015 in 'PGGP015.pas' {frm_consulta_processo},
  PGGP017 in 'PGGP017.pas' {datm_main: TDataModule},
  PGGP018 in 'PGGP018.pas' {frm_manut_proc},
  PGGP019 in 'PGGP019.pas' {datm_manut_proc: TDataModule},
  PGGP020 in 'PGGP020.pas' {frm_consulta_previsao},
  PGGP021 in 'PGGP021.pas' {datm_consulta_previsao: TDataModule},
  PGGP022 in 'PGGP022.pas' {datm_consulta_processo: TDataModule},
  PGGP023 in 'pggp023.pas' {frm_consulta_pe},
  PGGP024 in 'pggp024.pas' {datm_consulta_pe: TDataModule},
  PGGP025 in 'pggp025.pas' {frm_consulta_exp},
  PGGP026 in 'pggp026.pas' {datm_consulta_exp: TDataModule},
  PGGP027 in 'PGGP027.pas' {frm_sel_unid_prod_emb},
  PGGP029 in 'PGGP029.pas' {frm_sel_unid_prod_arm},
  PGGP030 in 'PGGP030.pas' {datm_sel_unid_prod_arm: TDataModule},
  PGGP031 in 'PGGP031.pas' {frm_consulta_exp_saque},
  PGGP032 in 'PGGP032.pas' {datm_consulta_exp_saque: TDataModule},
  PGGP033 in 'pggp033.pas' {frm_acordo_normas},
  PGGP034 in 'pggp034.pas' {datm_acordo_normas: TDataModule},
  PGLI001 in 'pgli001.pas' {frm_LI_capa},
  PGLI002 in 'pgli002.pas' {frm_LI},
  pgli003 in 'pgli003.pas' {frm_LI_Itens},
  PGLI004 in 'pgli004.pas' {datm_LI: TDataModule},
  PGLI005 in 'pgli005.pas' {datm_LI_Capa: TDataModule},
  PGLI006 in 'pgli006.pas' {datm_LI_Itens: TDataModule},
  PGLI007 in 'PGLI007.pas' {frm_trans_LI},
  PGLI008 in 'PGLI008.pas' {datm_trans_LI: TDataModule},
  PGLQ007 in 'PGLQ007.pas' {frm_imp_cheque_branco},
  PGLQ008 in 'PGLQ008.pas' {datm_imp_cheque_branco: TDataModule},
  PGNM001 in 'PGNM001.pas' {frm_numerario},
  PGNM002 in 'PGNM002.pas' {datm_numerario: TDataModule},
  PGNM003 in 'PGNM003.pas' {frm_recebimento},
  PGNM004 in 'PGNM004.pas' {datm_recebimento: TDataModule},
  PGNM021 in 'PGNM021.pas' {frm_Impressao_Numerario},
  PGNM022 in 'PGNM022.pas' {datm_Impressao_Numerario: TDataModule},
  PGNM023 in 'PGNM023.pas' {frm_libera_sol_aberto},
  PGNM024 in 'PGNM024.pas' {datm_libera_sol_aberto: TDataModule},
  PGNM025 in 'PGNM025.pas' {frm_print_recibo},
  PGNM026 in 'PGNM026.pas' {datm_print_recibo: TDataModule},
  PGPE001 in 'PGPE001.pas' {frm_pe_capa},
  PGPE002 in 'PGPE002.pas' {frm_pe},
  PGPE003 in 'PGPE003.pas' {frm_pe_itens},
  PGPE004 in 'PGPE004.pas' {datm_pe: TDataModule},
  PGPE005 in 'PGPE005.pas' {datm_pe_capa: TDataModule},
  PGPE006 in 'PGPE006.pas' {datm_pe_itens: TDataModule},
  PGPE007 in 'PGPE007.pas' {frm_pe_prepara},
  PGPE008 in 'PGPE008.pas' {datm_pe_prepara: TDataModule},
  PGPE009 in 'PGPE009.pas' {frm_pe_duplica},
  PGPE010 in 'PGPE010.pas' {datm_pe_duplica: TDataModule},
  PGPE011 in 'PGPE011.pas' {frm_pe_estorno},
  PGPE012 in 'PGPE012.pas' {datm_pe_estorno: TDataModule},
  PGPE013 in 'PGPE013.pas' {frm_pe_consulta_itens},
  PGPE014 in 'PGPE014.pas' {datm_pe_consulta_itens: TDataModule},
  PGPE015 in 'PGPE015.pas' {frm_pe_consulta_prod},
  PGPE016 in 'PGPE016.pas' {datm_pe_consulta_prod: TDataModule},
  PGPE017 in 'PGPE017.pas' {frm_exp_capa},
  PGPE018 in 'PGPE018.pas' {frm_exp},
  PGPE019 in 'PGPE019.pas' {frm_exp_itens},
  PGPE020 in 'PGPE020.pas' {datm_exp: TDataModule},
  PGPE021 in 'PGPE021.pas' {datm_exp_capa: TDataModule},
  PGPE022 in 'PGPE022.pas' {datm_exp_itens: TDataModule},
  PGPE023 in 'PGPE023.pas' {frm_exp_duplica},
  PGPE024 in 'PGPE024.pas' {datm_exp_duplica: TDataModule},
  PGPE025 in 'PGPE025.pas' {frm_pe_impressao},
  PGPE026 in 'PGPE026.pas' {datm_pe_impressao: TDataModule},
  PGPE027 in 'PGPE027.pas' {frm_exp_impressao},
  PGPE028 in 'PGPE028.pas' {datm_exp_impressao: TDataModule},
  PGPE029 in 'PGPE029.pas' {frm_exp_impr_fatura},
  PGPE031 in 'pgpe031.pas' {frm_exp_impr_cert_orig},
  PGPE032 in 'pgpe032.pas' {datm_exp_impr_cert_orig: TDataModule},
  PGPE033 in 'pgpe033.pas' {frm_exp_impr_packing},
  PGPE034 in 'pgpe034.pas' {datm_exp_impr_packing: TDataModule},
  PGPE035 in 'pgpe035.pas' {frm_exp_impr_cert_seg},
  PGPE036 in 'pgpe036.pas' {datm_exp_impr_cert_seg: TDataModule},
  PGPE037 in 'pgpe037.pas' {frm_exp_impr_instr_emb},
  PGPE038 in 'pgpe038.pas' {datm_exp_impr_instr_emb: TDataModule},
  PGPE039 in 'Pgpe039.pas' {frm_exp_saque},
  PGPE040 in 'Pgpe040.pas' {datm_exp_saque: TDataModule},
  PGPE041 in 'Pgpe041.pas' {frm_exp_impr_saque},
  PGPE042 in 'Pgpe042.pas' {datm_exp_impr_saque: TDataModule},
  PGPG001 in 'PGPG001.pas' {frm_solic_pagto},
  PGPG002 in 'PGPG002.pas' {datm_solic_pagto: TDataModule},
  PGPG003 in 'PGPG003.pas' {frm_monta_pagto},
  PGPG004 in 'PGPG004.pas' {datm_monta_pagto: TDataModule},
  PGPG005 in 'PGPG005.pas' {frm_lib_pagto},
  PGPG006 in 'PGPG006.pas' {datm_lib_pagto: TDataModule},
  PGPG007 in 'PGPG007.pas' {frm_imp_pagtos},
  PGPG008 in 'PGPG008.pas' {datm_imp_pagtos: TDataModule},
  PGPG011 in 'PGPG011.pas' {frm_solic_adm},
  PGPG012 in 'PGPG012.pas' {datm_solic_adm: TDataModule},
  PGPG013 in 'PGPG013.pas' {frm_monta_adm},
  PGPG014 in 'PGPG014.pas' {datm_monta_adm: TDataModule},
  PGPG015 in 'PGPG015.pas' {frm_pesq_pagto},
  PGPG016 in 'PGPG016.pas' {datm_pesq_pagto: TDataModule},
  PGPG017 in 'PGPG017.pas' {frm_pesq_adm},
  PGPG018 in 'PGPG018.pas' {datm_pesq_adm: TDataModule},
  PGPG019 in 'PGPG019.pas' {frm_imp_adm},
  PGPG020 in 'PGPG020.pas' {datm_imp_adm: TDataModule},
  PGPO001 in 'PGpo001.pas' {frm_po},
  PGPO002 in 'PGpo002.pas' {datm_po: TDataModule},
  PGPO003 in 'PGpo003.pas' {frm_po_prepara},
  PGPO004 in 'PGpo004.pas' {datm_po_prepara: TDataModule},
  PGPO005 in 'PGpo005.pas' {frm_po_estorno},
  PGPO006 in 'PGpo006.pas' {datm_po_estorno: TDataModule},
  PGPO007 in 'pgpo007.pas' {frm_po_consulta_itens},
  PGPO008 in 'pgpo008.pas' {datm_po_consulta_itens: TDataModule},
  PGPO009 in 'PGPO009.pas' {frm_consulta_po},
  PGPO010 in 'pgpo010.pas' {datm_consulta_po: TDataModule},
  PGPO011 in 'PGpo011.pas' {frm_po_consulta_prod},
  PGPO012 in 'pgpo012.pas' {datm_po_consulta_prod: TDataModule},
  PGPO013 in 'pgpo013.pas' {datm_po_leitura: TDataModule},
  PGPO016 in 'pgpo016.pas' {frm_po_impressao},
  PGPO017 in 'pgpo017.pas' {datm_po_impressao: TDataModule},
  PGSD002 in 'PGSD002.pas' {frm_relatorio_extrato_honorarios},
  PGSM001 in 'PGSM001.pas' {frm_modulo},
  PGSM002 in 'PGSM002.pas' {frm_ensaios},
  PGSM003 in 'PGSM003.pas' {datm_ensaios: TDataModule},
  PGSM004 in 'PGSM004.pas' {frm_pesq_log},
  PGSM005 in 'PGSM005.pas' {datm_pesq_log: TDataModule},
  PGSM006 in 'PGSM006.pas' {frm_observacoes},
  PGSM007 in 'PGSM007.pas' {frm_faixas_ensaio},
  PGSM008 in 'PGSM008.pas' {datm_faixas_ensaio: TDataModule},
  PGSM009 in 'PGSM009.pas' {datm_obs: TDataModule},
  PGSM010 in 'PGSM010.pas' {frm_produto},
  PGSM011 in 'PGSM011.pas' {frm_via_transp},
  PGSM012 in 'PGSM012.pas' {frm_unid_medida},
  PGSM013 in 'PGSM013.pas' {datm_via_transp: TDataModule},
  PGSM014 in 'PGSM014.pas' {frm_local_embarque},
  PGSM015 in 'PGSM015.pas' {frm_cargo},
  PGSM016 in 'PGSM016.pas' {frm_usuario},
  PGSM018 in 'PGSM018.pas' {frm_unidade},
  PGSM019 in 'PGSM019.pas' {frm_Transportador_itl},
  PGSM020 in 'PGSM020.pas' {datm_serv_classif: TDataModule},
  PGSM022 in 'PGSM022.pas' {frm_servico},
  PGSM024 in 'PGSM024.pas' {frm_cliente},
  PGSM025 in 'PGSM025.pas' {frm_cliente_contato},
  PGSM026 in 'PGSM026.pas' {datm_servico: TDataModule},
  PGSM027 in 'PGSM027.pas' {frm_sda},
  PGSM028 in 'PGSM028.pas' {frm_serv_classif},
  PGSM029 in 'PGSM029.pas' {frm_hab_desp},
  PGSM030 in 'Pgsm030.pas' {frm_duplica_param_cli},
  PGSM031 in 'Pgsm031.pas' {datm_duplica_param_cli: TDataModule},
  PGSM032 in 'PGSM032.pas' {datm_hab_desp: TDataModule},
  PGSM033 in 'PGSM033.pas' {frm_duplica_eventos},
  PGSM034 in 'PGSM034.pas' {frm_etapa},
  PGSM035 in 'PGSM035.pas' {datm_etapa: TDataModule},
  PGSM036 in 'PGSM036.pas' {frm_evento},
  PGSM037 in 'PGSM037.pas' {datm_evento: TDataModule},
  PGSM038 in 'PGSM038.pas' {datm_duplica_eventos: TDataModule},
  PGSM039 in 'PGSM039.pas' {frm_observacoes_processo},
  PGSM041 in 'PGSM041.pas' {frm_banco},
  PGSM042 in 'PGSM042.pas' {datm_banco: TDataModule},
  PGSM044 in 'PGSM044.pas' {frm_celula},
  PGSM045 in 'PGSM045.pas' {datm_celula: TDataModule},
  PGSM046 in 'PGSM046.pas' {frm_despachante},
  PGSM047 in 'PGSM047.pas' {frm_duplica_ct_contabil_gerencial},
  PGSM048 in 'PGSM048.pas' {frm_moeda},
  PGSM049 in 'PGSM049.pas' {datm_moeda: TDataModule},
  PGSM050 in 'PGSM050.pas' {datm_modulo: TDataModule},
  PGSM051 in 'PGSM051.pas' {frm_transp_rod},
  PGSM052 in 'PGSM052.pas' {datm_transp_rod: TDataModule},
  PGSM053 in 'PGSM053.pas' {datm_cargo: TDataModule},
  PGSM054 in 'PGSM054.pas' {frm_expurgo},
  PGSM055 in 'PGSM055.pas' {datm_expurgo: TDataModule},
  PGSM056 in 'PGSM056.pas' {frm_DARF},
  PGSM057 in 'PGSM057.pas' {datm_DARF: TDataModule},
  PGSM058 in 'PGSM058.pas' {datm_usuario: TDataModule},
  PGSM059 in 'PGSM059.pas' {frm_item},
  PGSM060 in 'PGSM060.pas' {datm_item: TDataModule},
  PGSM061 in 'PGSM061.pas' {frm_priori_item},
  PGSM062 in 'PGSM062.pas' {datm_priori_item: TDataModule},
  PGSM063 in 'PGSM063.pas' {datm_amz: TDataModule},
  PGSM064 in 'PGSM064.pas' {frm_amz},
  PGSM065 in 'PGSM065.pas' {frm_cliente_numerario},
  PGSM066 in 'PGSM066.pas' {datm_cliente_contato: TDataModule},
  PGSM067 in 'PGSM067.pas' {datm_cliente_numerario: TDataModule},
  PGSM068 in 'PGSM068.pas' {datm_cliente_co: TDataModule},
  PGSM069 in 'PGSM069.PAS' {frm_cliente_transp},
  PGSM070 in 'PGSM070.pas' {datm_cliente_transp: TDataModule},
  PGSM071 in 'PGSM071.pas' {frm_cliente_repres},
  PGSM072 in 'PGSM072.pas' {datm_cliente_repres: TDataModule},
  PGSM075 in 'PGSM075.pas' {frm_cliente_servico},
  PGSM076 in 'PGSM076.pas' {datm_cliente_servico: TDataModule},
  PGSM077 in 'PGSM077.pas' {frm_cliente_faturamento},
  PGSM078 in 'PGSM078.pas' {datm_cliente_faturamento: TDataModule},
  PGSM079 in 'PGSM079.pas' {frm_tx_codesp},
  PGSM080 in 'PGSM080.pas' {datm_tx_codesp: TDataModule},
  PGSM081 in 'PGSM081.pas' {frm_tx_tra},
  PGSM082 in 'PGSM082.pas' {datm_tx_tra: TDataModule},
  PGSM083 in 'PGSM083.pas' {frm_tx_amg},
  PGSM084 in 'PGSM084.pas' {datm_tx_amg: TDataModule},
  PGSM085 in 'PGSM085.pas' {frm_tx_teca},
  PGSM086 in 'PGSM086.pas' {datm_tx_teca: TDataModule},
  PGSM087 in 'PGSM087.pas' {datm_emb: TDataModule},
  PGSM088 in 'PGSM088.pas' {frm_emb},
  PGSM089 in 'PGSM089.pas' {datm_favor: TDataModule},
  PGSM090 in 'PGSM090.pas' {frm_Favor},
  PGSM091 in 'PGSM091.pas' {frm_embal},
  PGSM092 in 'PGSM092.pas' {datm_embal: TDataModule},
  PGSM093 in 'PGSM093.pas' {frm_conta},
  PGSM094 in 'PGSM094.pas' {datm_conta: TDataModule},
  PGSM095 in 'PGSM095.pas' {datm_emp_est: TDataModule},
  PGSM096 in 'PGSM096.pas' {frm_consulta_padrao},
  PGSM100 in 'PGSM100.pas' {datm_senha: TDataModule},
  PGSM102 in 'PGSM102.pas' {datm_param_sistema: TDataModule},
  PGSM103 in 'PGSM103.pas' {frm_emp_est},
  PGSM104 in 'PGSM104.pas' {frm_cliente_co},
  PGSM105 in 'PGSM105.pas' {datm_unidade: TDataModule},
  PGSM106 in 'PGSM106.pas' {datm_transportador_itl: TDataModule},
  PGSM107 in 'PGSM107.pas' {datm_local_embarque: TDataModule},
  PGSM108 in 'PGSM108.pas' {datm_cliente: TDataModule},
  PGSM109 in 'PGSM109.pas' {frm_faixas},
  PGSM110 in 'PGSM110.pas' {datm_produto: TDataModule},
  PGSM113 in 'PGSM113.pas' {datm_despachante: TDataModule},
  PGSM116 in 'PGSM116.pas' {datm_sda: TDataModule},
  PGSM117 in 'PGSM117.pas' {frm_mercadoria},
  PGSM118 in 'PGSM118.pas' {datm_mercadoria: TDataModule},
  PGSM119 in 'PGSM119.pas' {frm_grupo},
  PGSM120 in 'PGSM120.pas' {datm_grupo: TDataModule},
  PGSM121 in 'PGSM121.pas' {frm_previsao},
  PGSM122 in 'PGSM122.pas' {datm_previsao: TDataModule},
  PGSM125 in 'PGSM125.pas' {datm_ag_tx: TDataModule},
  PGSM126 in 'pgsm126.pas' {frm_ag_tx},
  PGSM129 in 'PGSM129.pas' {datm_faixas: TDataModule},
  PGSM130 in 'PGSM130.pas' {frm_abre_proc},
  PGSM131 in 'PGSM131.pas' {datm_abre_proc: TDataModule},
  PGSM132 in 'PGSM132.pas' {frm_lib_proc},
  PGSM133 in 'PGSM133.pas' {datm_lib_proc: TDataModule},
  PGSM134 in 'PGSM134.pas' {frm_canc_proc},
  PGSM135 in 'PGSM135.pas' {datm_canc_proc: TDataModule},
  PGSM136 in 'PGSM136.pas' {frm_pesq_proc},
  PGSM137 in 'PGSM137.pas' {datm_pesq_proc: TDataModule},
  PGSM138 in 'PGSM138.pas' {frm_mod_follow_up},
  PGSM139 in 'PGSM139.pas' {datm_mod_follow_up: TDataModule},
  PGSM142 in 'PGSM142.pas' {frm_sel_col_data},
  PGSM143 in 'PGSM143.pas' {datm_sel_col_data: TDataModule},
  PGSM146 in 'PGSM146.pas' {frm_log_erro_calculo},
  PGSM147 in 'PGSM147.pas' {datm_log_erro_calculo: TDataModule},
  PGSM148 in 'PGSM148.pas' {datm_consulta_padrao: TDataModule},
  PGSM149 in 'pgsm149.pas' {frm_disp_legal},
  PGSM150 in 'PGSM150.pas' {datm_disp_legal: TDataModule},
  PGSM151 in 'PGSM151.pas' {frm_feriado},
  PGSM152 in 'PGSM152.pas' {datm_feriado: TDataModule},
  PGSM153 in 'PGSM153.pas' {frm_arm_rec},
  PGSM154 in 'PGSM154.pas' {datm_arm_rec: TDataModule},
  PGSM155 in 'pgsm155.pas' {frm_po_leitura},
  PGSM156 in 'PGSM156.pas' {frm_follow_obs},
  PGSM157 in 'PGSM157.pas' {frm_ncm},
  PGSM158 in 'PGSM158.pas' {datm_ncm: TDataModule},
  PGSM159 in 'PGSM159.pas' {datm_acesso_scx: TDataModule},
  PGSM160 in 'PGSM160.pas' {frm_acesso_scx},
  PGSM161 in 'PGSM161.pas' {datm_enquad_op: TDataModule},
  PGSM162 in 'PGSM162.pas' {frm_enquad_op},
  PGSM163 in 'PGSM163.pas' {datm_urf_scx_exp: TDataModule},
  PGSM164 in 'PGSM164.pas' {frm_urf_scx_exp},
  PGSM165 in 'PGSM165.pas' {datm_inst_negoc: TDataModule},
  PGSM166 in 'PGSM166.pas' {frm_inst_negoc},
  PGSM167 in 'PGSM167.pas' {datm_duplica_ct_contabil_gerencial: TDataModule},
  PGSM168 in 'PGSM168.pas' {frm_ct_contabil},
  PGSM169 in 'PGSM169.pas' {datm_ct_contabil: TDataModule},
  PGSM170 in 'PGSM170.pas' {frm_ct_gerencial},
  PGSM171 in 'PGSM171.pas' {datm_ct_gerencial: TDataModule},
  PGSM172 in 'PGSM172.pas' {frm_ct_custo},
  PGSM173 in 'PGSM173.pas' {datm_ct_custo: TDataModule},
  PGSM174 in 'PGSM174.pas' {frm_hist_padrao},
  PGSM175 in 'PGSM175.pas' {datm_hist_padrao: TDataModule},
  PGSM176 in 'PGSM176.pas' {frm_finalidade_merc},
  PGSM177 in 'PGSM177.pas' {datm_finalidade_merc: TDataModule},
  PGSM178 in 'PGSM178.pas' {frm_modalidade_trans},
  PGSM179 in 'PGSM179.pas' {datm_modalidade_trans: TDataModule},
  PGSM180 in 'PGSM180.pas' {frm_familia_prod},
  PGSM181 in 'PGSM181.pas' {datm_familia_prod: TDataModule},
  PGSM182 in 'PGSM182.pas' {frm_termo_pagto},
  PGSM183 in 'PGSM183.pas' {datm_termo_pagto: TDataModule},
  PGSM184 in 'PGSM184.pas' {frm_mercadoria_exp},
  PGSM185 in 'PGSM185.pas' {datm_mercadoria_exp: TDataModule},
  PGSM186 in 'PGSM186.pas' {frm_acordo},
  PGSM187 in 'PGSM187.pas' {datm_acordo: TDataModule},
  PGSM188 in 'PGSM188.pas' {frm_normas},
  PGSM189 in 'PGSM189.pas' {datm_normas: TDataModule},
  PGSM190 in 'pgsm190.pas' {frm_cabecalho},
  PGSM191 in 'pgsm191.pas' {datm_cabecalho: TDataModule},
  PGSM192 in 'pgsm192.pas' {frm_local_emissao},
  PGSM193 in 'pgsm193.pas' {datm_local_emissao: TDataModule},
  PGSM194 in 'PGSM194.pas' {frm_rel_extrato_cc},
  PGSM195 in 'PGSM195.pas' {datm_rel_extrato_cc: TDataModule},
  PGSM196 in 'pgsm196.pas' {frm_de_para},
  PGSM197 in 'pgsm197.pas' {datm_de_para: TDataModule},
  PGSM198 in 'pgsm198.pas' {frm_retorno_fi},
  PGSM199 in 'pgsm199.pas' {datm_retorno_fi: TDataModule},
  PGSM200 in 'pgsm200.pas' {frm_ncm_exp},
  PGSM201 in 'pgsm201.pas' {datm_ncm_exp: TDataModule},
  PGSM202 in 'pgsm202.pas' {frm_naladi_ncca_exp},
  PGSM203 in 'pgsm203.pas' {datm_naladi_ncca_exp: TDataModule},
  PGSM204 in 'pgsm204.pas' {frm_naladi_sh_exp},
  PGSM205 in 'pgsm205.pas' {datm_naladi_sh_exp: TDataModule},
  PGSM206 in 'PGSM206.pas' {frm_manut_rel_fin},
  PGSM207 in 'PGSM207.pas' {datm_manut_rel_fin: TDataModule},
  PGSM209 in 'PGSM209.pas' {datm_documento: TDataModule},
  PGPE043 in 'PGPE043.pas' {frm_exp_bordero},
  PGPE044 in 'PGPE044.pas' {datm_exp_bordero: TDataModule},
  PGSM208 in 'PGSM208.pas' {frm_documento},
  PGGA007 in 'PGGA007.pas' {frm_imp_darf},
  PGGA008 in 'PGGA008.pas' {datm_imp_darf: TDataModule},
  PGFT027 in 'PGFT027.pas' {frm_urf_scx},
  PGFT028 in 'PGFT028.pas' {datm_urf_scx: TDataModule},
  PGDI038 in 'pgdi038.pas' {frm_trans_DI},
  PGDI039 in 'pgdi039.pas' {datm_trans_DI: TDataModule},
  PGSM210 in 'pgsm210.pas' {frm_pais},
  PGSM211 in 'pgsm211.pas' {datm_pais: TDataModule},
  pgsm212 in 'pgsm212.pas' {frm_area},
  PGSM213 in 'PGSM213.pas' {datm_area: TDataModule},
  PGBF003 in 'PGBF003.pas' {frm_exp_leitura_nf},
  PGBF004 in 'PGBF004.pas' {datm_exp_leitura_nf: TDataModule},
  PGDI041 in 'pgdi041.pas' {datm_di_rec_diag: TDataModule},
  PGDI040 in 'PGDI040.pas' {frm_di_rec_diag},
  PGGA025 in 'pgga025.pas' {frm_rel_and_servico},
  PGGA026 in 'pgga026.pas' {datm_rel_and_servico: TDataModule},
  PGSM214 in 'PGSM214.pas' {frm_cliente_docto},
  PGSM215 in 'PGSM215.pas' {datm_cliente_docto: TDataModule},
  PGSM216 in 'PGSM216.pas' {frm_evento_po},
  PGSM217 in 'PGSM217.pas' {datm_evento_po: TDataModule},
  PGPO018 in 'PGPO018.pas' {frm_po_flp},
  PGPO020 in 'PGPO020.pas' {frm_flp_po_obs},
  PGCH040 in 'PGCH040.pas' {frm_sel_data_proc},
  PGCH041 in 'PGCH041.pas' {datm_sel_data_proc: TDataModule},
  PGSM218 in 'PGSM218.pas' {frm_sel_mercadoria},
  PGSM219 in 'PGSM219.pas' {datm_sel_mercadoria: TDataModule},
  PGGP037 in 'PGGP037.pas' {frm_ajuste_impressao_icms},
  PGGP038 in 'PGGP038.pas' {datm_ajuste_impressao_icms: TDataModule},
  PGGP067 in 'PGGP067.pas' {frm_po_planilha},
  PGGP068 in 'PGGP068.pas' {datm_po_planilha : TDataModule},
  PGSM220 in 'pgsm220.pas' {frm_duplica_unid},
  PGSM221 in 'pgsm221.pas' {datm_duplica_unid: TDataModule},
  PGGP039 in 'pggp039.pas' {frm_ajuste_impressao_sda},
  PGGP040 in 'pggp040.pas' {datm_ajuste_impressao_sda: TDataModule},
  PGFI015 in 'PGFI015.pas' {frm_financeiro_fech_data},
  PGDI044 in 'PGDI044.pas' {frm_DI_saida},
  PGDI045 in 'PGDI045.pas' {datm_DI_saida: TDataModule},
  PGGA028 in 'PGGA028.pas' {datm_proc_vinc_realiza: TDataModule},
  PGGA027 in 'PGGA027.pas' {frm_proc_vinc_realiza},
  PGSM101 in 'PGSM101.pas' {frm_param_sistema},
  pggp043 in 'PGGP043.pas' {frm_ajuste_impressao_gnre},
  pggp044 in 'pggp044.pas' {datm_ajuste_impressao_gnre: TDataModule},
  PGFT005 in 'pgft005.pas' {frm_sel_fat},
  PGCH044 in 'pgch044.pas' {frm_sel_unid_prod_cli_arm},
  PGCH045 in 'pgch045.pas' {datm_sel_unid_prod_cli_arm: TDataModule},
  PGGP047 in 'PGGP047.pas' {frm_ajuste_impressao_darf},
  PGGP048 in 'PGGP048.pas' {frm_ajuste_impressao_exoneracao},
  PGGP049 in 'PGGP049.pas' {datm_ajuste_impressao_darf: TDataModule},
  PGGP050 in 'PGGP050.pas' {datm_ajuste_impressao_exoneracao: TDataModule},
  PGSM232 in 'PGSM232.pas' {frm_cliente_indicado},
  PGSM233 in 'PGSM233.pas' {datm_cliente_indicado: TDataModule},
  PGGP051 in 'PGGP051.pas' {frm_ajuste_impressao_boleto},
  PGGP052 in 'PGGP052.pas' {datm_ajuste_impressao_boleto: TDataModule},
  PGSM234 in 'PGSM234.pas' {frm_depto},
  PGSM236 in 'PGSM236.pas' {frm_depto_cargo},
  PGSM235 in 'PGSM235.pas' {datm_depto: TDataModule},
  PGSM237 in 'PGSM237.pas' {datm_depto_cargo: TDataModule},
  PGGP053 in 'PGGP053.pas' {frm_rel_com_imp_exp},
  PGGP054 in 'PGGP054.pas' {datm_rel_com_imp_exp: TDataModule},
  PGGP055 in 'PGGP055.pas' {frm_rel_com_ind_por},
  PGGP056 in 'PGGP056.pas' {datm_rel_com_ind_por: TDataModule},
  PGPE047 in 'Pgpe047.pas' {frm_sel_unid_cli_serv_anal},
  Pgpe048 in 'Pgpe048.pas' {datm_sel_unid_cli_serv_anal: TDataModule},
  PGPE049 in 'Pgpe049.pas' {frm_rel_dde_vencto},
  PGPE050 in 'Pgpe050.pas' {datm_rel_dde_vencto: TDataModule},
  PGFT049 in 'PGFT049.pas' {frm_nf_serv},
  PGFT050 in 'PGFT050.pas' {datm_nf_serv: TDataModule},
  PGGP057 in 'PGGP057.pas' {frm_ajuste_impressao_nf_serv},
  PGGP058 in 'PGGP058.pas' {datm_ajuste_impressao_nf_serv: TDataModule},
  PGGP059 in 'PGGP059.pas' {frm_sel_padrao_agente},
  PGGP060 in 'PGGP060.pas' {datm_sel_padrao_agente: TDataModule},
  PGSM238 in 'PGSM238.pas' {frm_grupo_item},
  PGSM239 in 'PGSM239.pas' {datm_grupo_item: TDataModule},
  PGLQ010 in 'PGLQ010.pas' {frm_liq},
  PGLQ011 in 'PGLQ011.pas' {datm_liq: TDataModule},
  PGPG021 in 'PGPG021.pas' {frm_sel_unid_cli_grupo_item},
  PGPG022 in 'PGPG022.pas' {datm_sel_unid_cli_grupo_item: TDataModule},
  PGPO019 in 'PGPO019.pas' {datm_po_flp: TDataModule},
  PGSM240 in 'PGSM240.pas' {frm_viagem},
  PGSM241 in 'PGSM241.pas' {datm_viagem: TDataModule},
  PGGP062 in 'PGGP062.pas' {datm_sel_unid_cont: TDataModule},
  PGPG023 in 'PGPG023.pas' {frm_lib_adm},
  PGPG024 in 'PGPG024.pas' {datm_lib_adm: TDataModule},
  PGPG027 in 'PGPG027.pas' {frm_sel_pagtos},
  PGPG028 in 'PGPG028.pas' {datm_sel_pagtos: TDataModule},
  PGPG025 in 'PGPG025.pas' {frm_pagto_gera_ted},
  PGPG026 in 'PGPG026.pas' {datm_pagto_gera_ted: TDataModule},
  PGPG029 in 'PGPG029.pas' {frm_imp_adm_gera_ted},
  PGPG030 in 'PGPG030.pas' {datm_imp_adm_gera_ted: TDataModule},
  PGFI017 in 'PGFI017.pas' {frm_fin_transf_pagto},
  PGFI018 in 'PGFI018.pas' {datm_fin_transf_pagto: TDataModule},
  PGDE001 in 'PGDE001.pas' {frm_dem_cntr},
  PGDE002 in 'PGDE002.pas' {datm_dem_cntr: TDataModule},
  PGFI019 in 'PGFI019.pas' {frm_pesq_fin},
  PGFI020 in 'PGFI020.pas' {datm_pesq_fin: TDataModule},
  PGRE002 in 'PGRE002.pas' {frm_rel_exp_flp},
  PGRE003 in 'PGRE003.pas' {datm_rel_exp_flp: TDataModule},
  PGDE003 in 'PGDE003.pas' {frm_dem_fat},
  PGDE004 in 'PGDE004.pas' {datm_dem_fat: TDataModule},
  PGPE030 in 'pgpe030.pas' {datm_exp_impr_fatura: TDataModule},
  PGPE051 in 'PGPE051.pas' {frm_exp_carta_cred},
  PGPE052 in 'PGPE052.pas' {datm_exp_carta_cred: TDataModule},
  PGSM242 in 'PGSM242.pas' {frm_cliente_agente},
  PGSM243 in 'PGSM243.pas' {datm_cliente_agente: TDataModule},
  PGIN001 in 'PGIN001.pas' {frm_int_work_im},
  PGIN002 in 'PGIN002.pas' {datm_int_work_im: TDataModule},
  pgen001 in 'pgen001.pas' {frm_da},
  PGEN002 in 'pgen002.pas' {datm_da: TDataModule},
  PGSM244 in 'PGSM244.pas' {frm_prop_merc},
  PGSM245 in 'PGSM245.pas' {datm_prop_merc: TDataModule},
  PGEN003 in 'pgen003.pas' {frm_nac},
  PGEN004 in 'pgen004.pas' {datm_nac: TDataModule},
  PGGP063 in 'PGGP063.pas' {frm_pesq_lote},
  PGGP064 in 'PGGP064.pas' {datm_pesq_lote: TDataModule},
  PGSM246 in 'PGSM246.pas' {frm_atualiza_ncm},
  PGSM247 in 'PGSM247.pas' {datm_atualiza_ncm: TDataModule},
  PGRE004 in 'PGRE004.pas' {frm_sel_unid_cli_imp_area},
  PGRE005 in 'PGRE005.pas' {datm_sel_unid_cli_imp_area: TDataModule},
  PGSM248 in 'PGSM248.pas' {frm_int_mesquita},
  PGSM249 in 'PGSM249.pas' {datm_int_mesquita: TDataModule},
  PGDI050 in 'PGDI050.pas' {frm_di_libera},
  PGDI051 in 'PGDI051.pas' {datm_di_libera: TDataModule},
  PGDI052 in 'PGDI052.pas' {frm_erros_di},
  PGSD008 in 'PGSD008.pas' {datm_relatorio_extrato_honorarios: TDataModule},
  PGSM250 in 'PGSM250.pas' {frm_lembrete_po},
  PGSM251 in 'PGSM251.pas' {datm_lembrete_po: TDataModule},
  PGGP061 in 'PGGP061.pas' {frm_sel_unid_cont},
  PGDI023 in 'PGDI023.pas' {frm_icms_online},
  PGDI024 in 'PGDI024.pas' {datm_icms_online: TDataModule},
  PGGP065 in 'PGGP065.pas' {frm_release},
  PGGP066 in 'PGGP066.pas' {datm_release: TDataModule},
  PGSD011 in 'PGSD011.pas' {frm_sda_distr},
  PGSD012 in 'PGSD012.pas' {datm_sda_distr: TDataModule},
  PGSD013 in 'PGSD013.pas' {frm_sda_emissao},
  PGSD014 in 'PGSD014.pas' {datm_sda_emissao: TDataModule},
  PGSD015 in 'PGSD015.pas' {frm_sda_cancel},
  PGSD016 in 'PGSD016.pas' {datm_sda_cancel: TDataModule},
  PGSD017 in 'PGSD017.pas' {frm_sda_pesq},
  PGSD018 in 'PGSD018.pas' {datm_sda_pesq: TDataModule},
  PGGP028 in 'PGGP028.pas' {datm_sel_unid_prod_emb: TDataModule},
  PGSM252 in 'PGSM252.pas' {frm_at_basf},
  PGSM253 in 'PGSM253.pas' {datm_at_basf: TDataModule},
  PGCH015 in 'PGCH015.pas' {datm_sel_unid_prod: TDataModule},
  PGCH014 in 'PGCH014.pas' {frm_sel_unid_prod},
  PGGP005 in 'PGGP005.pas' {dlg_about},
  PGCH036 in 'PGCH036.pas' {frm_sel_relat},
  PGCH037 in 'PGCH037.pas' {datm_sel_relat: TDataModule},
  PGPO023 in 'pgpo023.pas' {frm_gestao_po},
  PGPO024 in 'pgpo024.pas' {datm_gestao_po: TDataModule},
  PGPO025 in 'PGPO025.pas' {frm_evento_critico},
  PGPO026 in 'PGPO026.pas' {datm_evento_critico: TDataModule},
  PGSM292 in 'PGSM292.pas' {frm_recebimento_ag},
  PGSM280 in 'PGSM280.pas' {datm_recebimento_ag: TDataModule},
  PGSM990 in 'PGSM990.pas' {frm_impressao},
  PGSM290 in 'PGSM290.PAS' {frm_cntr},
  PGSM291 in 'PGSM291.pas' {datm_cntr: DataModule},
  PGSM300 in 'PGSM300.PAS' {frm_trans_nota},
  PGSM301 in 'PGSM301.pas' {datm_trans_nota: DataModule},
  PGSM295 in 'PGSM295.pas' {frm_notificacao},
  PGSM296 in 'PGSM296.pas' {datm_notificacao: DataModule},
  PGGP011 in 'PGGP011.pas' {frm_ctaapagar},
  PGGP012 in 'PGGP012.pas' {datm_ctaapagar: DataModule},
  ConsOnLineEx in 'ConsOnLineEx.pas' {frmConsOnLineEx},
  uCadNcmPisCofins in 'uCadNcmPisCofins.pas' {frm_ncm_pis_cofins},
  uProcComerc in 'uProcComerc.pas' {frm_proc_comerc},
  dProcComerc in 'dProcComerc.pas' {datm_proc_comerc: DataModule},
  uProcComercAgendVisita in 'uProcComercAgendVisita.pas' {frm_proc_comerc_agend_visita},
  uProposta in 'uProposta.pas' {frm_proposta},
  dProposta in 'dProposta.pas' {datm_proposta: DataModule},
  uCotacao in 'uCotacao.pas' {frm_cotacao},
  dCotacao in 'dCotacao.pas' {datm_cotacao: DataModule},
  uAgendaComercial in 'uAgendaComercial.pas' {frm_agenda_comercial},
  dAgendaComercial in 'dAgendaComercial.pas' {datm_agenda_comercial: DataModule},
  uPedidoInstrucao in 'uPedidoInstrucao.pas' {frm_pedido_instrucao},
  dPedidoInstrucao in 'dPedidoInstrucao.pas' {datm_pedido_instrucao: DataModule},
  uVendedores in 'uVendedores.pas' {frm_vendedores},
  dVendedores in 'dVendedores.pas' {datm_vendedores: DataModule},
  uPortos in 'uPortos.pas' {frm_portos},
  dPortos in 'dPortos.pas' {datm_portos: DataModule},
  uGrupoPortos in 'uGrupoPortos.pas' {frm_grupo_portos},
  dGrupoPortos in 'dGrupoPortos.pas' {datm_grupo_portos: DataModule},
  uAg in 'uAg.pas' {frm_ag},
  dAg in 'dAg.pas' {datm_ag: DataModule},
  uVeiculo in 'uVeiculo.pas' {frm_Veiculo},
  dVeiculo in 'dVeiculo.pas' {datm_Veiculo: DataModule},
  uBancoItl in 'ubancoItl.pas' {frm_banco_itl},
  uConsFrete in 'uConsFrete.pas' {frm_cons_frete},
  uFreteServ in 'uFreteServ.pas' {frm_frete_serv},
  dFreteServ in 'dFreteServ.pas' {datm_frete_serv: DataModule},
  uModDoc in 'uModDoc.pas' {frm_mod_doc},
  dModDoc in 'dModDoc.pas' {datm_mod_doc},
  uNotificador in 'uNotificador.pas' {frm_notificador},
  dNotificador in 'dNotificador.pas' {datm_notificador: DataModule},
  uGerarConsolidada in 'uGerarConsolidada.pas' {frm_gerar_consolidada},
  dGerarConsolidada in 'dGerarConsolidada.pas' {datm_gerar_consolidada: DataModule},
  uEmissaoRemessa in 'uEmissaoRemessa.pas' {frm_Emissao_Remessa},
  dEmissaoRemessa in 'dEmissaoRemessa.pas' {datm_Emissao_Remessa: DataModule},
  uInstrucaoEmbarque in 'uInstrucaoEmbarque.pas' {frm_instrucao_embarque},
  dInstrucaoEmbarque in 'dInstrucaoEmbarque.pas' {datm_instrucao_embarque: DataModule},
  uExpCalcProfit in 'uExpCalcProfit.pas' {frm_exp_calc_profit},
  dExpCalcProfit in 'dExpCalcProfit.pas' {datm_exp_calc_profit: DataModule},
  uExpProfitMarit in 'uExpProfitMarit.pas' {frm_exp_profit_marit},
  dExpProfitMarit in 'dExpProfitMarit.pas' {datm_exp_profit_marit: DataModule},
  uEmissaoBL in 'uEmissaoBL.pas' {frm_emissao_bl},
  frm_conhec_awb in 'frm_conhec_awb.pas' {frm_conhec_awb},
  frm_conhec_house in 'frm_conhec_house.pas' {frm_conhec_house},
  frm_conhecimento in 'frm_conhecimento.pas' {frm_conhecimento},
  uRelatoriosMailAut in 'uRelatoriosMailAut.pas' {frm_relatorios_mail_aut},
  dRelatoriosMailAut in 'dRelatoriosMailAut.pas' {datm_relatorios_mail_aut: DataModule},
  dReCapa in 'dReCapa.pas' {datm_re_capa: DataModule},
  dDDE in 'dDDE.pas' {datm_dde: DataModule},
  udatm_dse in 'udatm_dse.pas' {datm_dse: DataModule},
  ufrm_dse in 'ufrm_dse.pas' {frm_dse},
  uDDE in 'uDDE.pas' {frm_dde},
  uHistoricoDDE in 'uHistoricoDDE.pas' {frm_historico_dde},
  uExpMontaRe in 'uExpMontaRe.pas' {frm_exp_monta_re},
  uReAnexoFabric in 'uReAnexoFabric.pas' {frmReAnexoFabric},
  uReCapa in 'uReCapa.pas' {frmReCapa},
  uReclassificacaoAnexos in 'uReclassificacaoAnexos.pas' {frm_re_classificacao_anexos},
  uFaturaComercial2 in 'uFaturaComercial2.pas' {frm_fatura_comercial2},
  uPackingList2 in 'uPackingList2.pas' {frm_packing_list2},
  uAlteraServico in 'uAlteraServico.pas' {frm_altera_servico},
  uIntegracaoDeloitte in 'uIntegracaoDeloitte.pas' {Form1},
  uAccount in 'uAccount.pas' {frm_account},
  dAccount in 'dAccount.pas' {datm_account: DataModule},
  dEmissaoFatura in 'dEmissaoFatura.pas' {datm_emissao_fatura: DataModule},
  uEmissaoFatura in 'uEmissaoFatura.pas' {frm_emissao_fatura},
  uGerarRemessa in 'uGerarRemessa.pas' {frm_gerar_remessa},
  dGerarRemessa in 'dGerarRemessa.pas' {datm_gerar_remessa: DataModule},
  uLibAccount in 'uLibAccount.pas' {frm_lib_account},
  dLibAccount in 'dLibAccount.pas' {datm_lib_account: DataModule},
  uDispRemessa in 'uDispRemessa.pas' {frm_disp_remessa},
  uFaturaComplementar in 'uFaturaComplementar.pas' {frm_fat_Itl_complementar},
  dFaturaComplementar in 'dFaturaComplementar.pas' {datm_fat_Itl_complementar: DataModule},
  uProfitMaritimo in 'uProfitMaritimo.pas' {frm_profit_maritimo},
  dProfitMaritimo in 'dProfitMaritimo.pas' {datm_profit_maritimo: DataModule},
  uProcIata in 'uProcIata.pas' {frm_proc_iata},
  dProcIata in 'dProcIata.pas' {datm_proc_iata: DataModule},
  uRetificador in 'uRetificador.pas' {frm_retifica},
  dRetificador in 'dRetificador.pas' {datm_retifica: DataModule},
  uCtrlDemurrage in 'uCtrlDemurrage.pas' {frm_ctrl_demurrage},
  dCtrlDemurrage in 'dCtrlDemurrage.pas' {datm_ctrl_demurrage: DataModule},
  dCalcProfit in 'dCalcProfit.pas' {datm_calc_profit: DataModule},
  uRelIntegradoDrawback in 'uRelIntegradoDrawback.pas' {frm_rel_integrado_drawback},
  uRelProcessosCAT63 in 'uRelProcessosCAT63.pas' {frmRelProcessosCAT63},
  uCatalogoEnderecos in 'uCatalogoEnderecos.pas' {frmCatalogoEnderecos},
  uIntegracaoBSH in 'uIntegracaoBSH.pas' {frmIntegracaoBSH},
  uNewTrataErros in 'uNewTrataErros.pas' {frmNewTrataErros},
  Uimp_rd in 'Uimp_rd.pas' {frm_impressao_rd},
  uIntegraDem in 'uIntegraDem.pas' {frm_integra_dem},
  uParametrizacao in 'uParametrizacao.pas' {frm_parametrizacao},
  uFollowUp in 'uFollowUp.pas' {frm_followup},
  uBSHIntegracaoDI in 'uBSHIntegracaoDI.pas' {frm_BSH_Integracao_DI},
  uControleViagem in 'uControleViagem.pas' {Form2},
  uClienteArmazem in 'uClienteArmazem.pas' {frm_cliente_armazem},
  uArmazenagem in 'uArmazenagem.pas' {frmArmazenagem},
  uCartaConfig in 'uCartaConfig.pas' {frmCartaConfig},
  uEmissaoDocumentos in 'uEmissaoDocumentos.pas' {frmEmissaoDocumentos},
  uCriaVariaveis in 'uCriaVariaveis.pas' {frmCriaVariaveis},
  uConciliacao in 'uConciliacao.pas' {frm_conciliacao},
  dConciliacao in 'dConciliacao.pas' {datm_conciliacao: DataModule},
  uExpIntegraRAP in 'uExpIntegraRAP.pas' {frmExpIntegraRAP},
  UintegracaoWEB in 'UintegracaoWEB.pas' {frm_upload_img},
  uGestaoPedido in 'uGestaoPedido.pas' {frmGestaoPedido},
  uPaletizacao in 'uPaletizacao.pas' {frmPaletizacao},
  uPackingList in 'uPackingList.pas' {frmPackingList},
  uContCambio in 'uContCambio.pas' {frmContCambio},
  GSMLIB in 'GSMLIB.pas',
  Filetext in 'Filetext.pas',
  ByNumExtenso in 'bynumextenso.pas',
  Funcoes in 'FUNCOES\Funcoes.pas',
  RateioExp in 'RateioExp.pas',
  FuncoesExport in 'FUNCOES\FuncoesExport.pas',
  WabUtil in 'WabPas\WabUtil.pas',
  uCentroCusto in 'uCentroCusto.pas' {frm_centro_custo},
  dCentroCusto in 'dCentroCusto.pas' {datm_centro_custo: TDataModule},
  uRelRetrabalho in 'uRelRetrabalho.pas' {FrmRelRetrabalho},
  uIntegraNotaBasf in 'uIntegraNotaBasf.pas' {frm_integra_nota_basf},
  uRetencaoPorEmpresa in 'uRetencaoPorEmpresa.pas' {FrmControleRetencao},
  uHistoricoCalculoDI in 'uHistoricoCalculoDI.pas' {frmHistoricoClalculoDI},
  upendencias in 'upendencias.pas' {frm_pendencias},
  uDeclaracoes_Fiesp in 'uDeclaracoes_Fiesp.pas' {frm_Declaracoes_Fiesp},
  uIntNexus in 'uIntNexus.pas' {frmIntNexus},
  uIntFORDExp in 'uIntFORDExp.pas' {frmIntFORDExp},
  dIntFORDExp in 'dIntFORDExp.pas' {datmFordExp: TDataModule},
  uInfoNovoEx in 'uInfoNovoEx.pas' {frm_info_novoex},
  dInfoNovoEx in 'dInfoNovoEx.pas' {datm_info_novoex: TDataModule},
  uCONovoEx in 'uCONovoEx.pas' {frm_co_novoex},
  dCONovoEx in 'dCONovoEx.pas' {datm_co_novoex: TDataModule},
  uNfeSamsung in 'uNfeSamsung.pas' {frmNfeSamsung},
  uRelatorioBasico in 'uRelatorioBasico.pas' {frmRelatorioBasico},
  dRelatorioBasico in 'dRelatorioBasico.pas' {datmRelatorioBasico: TDataModule},
  uIntegracaoPoSystem in 'uIntegracaoPoSystem.pas' {frmIntegrcaoPoSystem},
  KrQuery in 'KrQuery.pas',
  KrHandle in 'KrHandle.pas',
  KrUtil in 'KrUtil.pas',
  KrFormat in 'KrFormat.pas',
  uLeiautePOSystem in 'uLeiautePOSystem.pas',
  uLeiauteSefazMattel in 'uLeiauteSefazMattel.pas',
  RlBasic in 'RlBasic.pas' {frmRLBasic},
  RlBasicCab in 'RlBasicCab.pas' {frmRLBasicCab},
  OiValorPorAdicao in 'OiValorPorAdicao.pas' {frmOiValorPorAdicao},
  KrCSV in 'KrCSV.pas',
  uConsulta in 'uConsulta.pas' {fmConsulta},
  uConsultaLICtx in 'uConsultaLICtx.pas' {fmConsultaLiCtx},
  KrSQL in 'KrSQL.pas',
  KrBoolean in 'KrBoolean.pas',
  DMLeiaute in 'DMLeiaute.pas' {dmdLeiaute: TDataModule},
  dgChaveValor in 'dgChaveValor.pas' {frmChaveValor},
  dgLeiauteLista in 'dgLeiauteLista.pas' {frmLeiauteLista},
  uDatm_acesso_externo in 'uDatm_acesso_externo.pas' {datm_acesso_externo: TDataModule},
  uAcesso_Externo in 'uAcesso_Externo.PAS' {frm_acesso_externo},
  uConsultaExigenciaInmetro in 'uConsultaExigenciaInmetro.pas' {frmConsultaExigenciaInmetro},
  KrLI in 'KrLI.pas',
  uDuplicaLi in 'uDuplicaLi.pas' {frmDuplicaLI},
  uCadUfIcmsOnLine in 'uCadUfIcmsOnLine.PAS' {frm_CadUfIcmsOnLine},
  uCargillTrimestralOperacoes in 'uCargillTrimestralOperacoes.pas' {frCargillTrimestralOperacoes},
  dmCargillTrimestralOperacoes in 'dmCargillTrimestralOperacoes.pas' {dmdCargillTrimestralOperacoes: TDataModule},
  FrDespesasBASF in 'FrDespesasBASF.pas' {frmDespesasBASF},
  FrNumerariosBASF in 'FrNumerariosBASF.pas' {frmNumerariosBASF},
  FrNumerariosNaoFaturados in 'FrNumerariosNaoFaturados.pas' {frmNumerariosNaoFaturados},
  frFaturadosNestle in 'frFaturadosNestle.pas' {frmFaturadosNestle},
  uDDENovo in 'uDDENovo.pas' {frm_dde_novo},
  dDDENovo in 'dDDENovo.pas' {datm_dde_novo: TDataModule},
  FrConsultaPagamentosWalletCtx in 'FrConsultaPagamentosWalletCtx.pas' {FormConsultaPaqamentosWallet},
  uConsultaLI in 'uConsultaLI.pas' {fmConsultaLI},
  FrControleFaturamentoUsuarioCtx in 'FrControleFaturamentoUsuarioCtx.pas' {FormControleFaturamentoUsuarioCtx},
  FrmSISCOSERVDespesasPagasCtx in 'FrmSISCOSERVDespesasPagasCtx.pas' {FormPadraoSISCOSERVCtx},
  FrmFaturadosSaldoFaturaCtx in 'FrmFaturadosSaldoFaturaCtx.pas' {FormFaturadosSaldoFaturaCtx},
  FrmCargilFaturadoImportacaoCtx in 'FrmCargilFaturadoImportacaoCtx.pas' {FormCargilFaturadosImportacaoCtx},
  FrmPagamentosNaoFaturadosCtx in 'FrmPagamentosNaoFaturadosCtx.pas' {FormPagamentosNaoFaturadosCtx},
  FrmRelDespesasPagasCtx in 'FrmRelDespesasPagasCtx.pas' {FormRelDepesasPagasCtx},
  FrmRlCargilFaturadosExportacaoCtx in 'FrmRlCargilFaturadosExportacaoCtx.pas' {FormRlCargilFaturadosExportacao},
  FrmRlFaturadosCEBRACECtx in 'FrmRlFaturadosCEBRACECtx.pas' {FormRlFaturadosCEBRACECtx},
  FrmRLFirmenichFaturadosCtx in 'FrmRLFirmenichFaturadosCtx.pas' {FormRLFirmenichFaturadosCtx},
  FrmRlWhirlpoolFaturadosCtx in 'FrmRlWhirlpoolFaturadosCtx.pas' {FormRlWhirlpooFaturadoslCtx},
  FrmRlBASFComissoesCtx in 'FrmRlBASFComissoesCtx.pas' {FormRlBASFComissoesCtx},
  FrmRlTM_BASFCtx in 'FrmRlTM_BASFCtx.pas' {FormRlTM_BASFCtx},
  FrmProcessoExportacaoItensCtx in 'FrmProcessoExportacaoItensCtx.pas' {FormProcessoExportacaoItensCtx},
  FrmSaintGobainSpedFiscalCtx in 'FrmSaintGobainSpedFiscalCtx.pas' {FormSaintGobainSpedFiscalCtx},
  FrmSaintCBESpedFiscalCtx in 'FrmSaintCBESpedFiscalCtx.pas' {FormCDESpedFiscalCtx},
  FrmFirmenichSpedFiscalCtx in 'FrmFirmenichSpedFiscalCtx.pas' {FormFirmenichSpedFiscalCtx},
  FrmCardinalICF in 'FrmCardinalICF.pas' {FormCardinalICF},
  FrGerenciamentoDeProcessos in 'FrGerenciamentoDeProcessos.pas' {FormGerenciamentoDeProcessos},
  DmGerenciamentoDeProcessos in 'DmGerenciamentoDeProcessos.pas' {dmdGerenciamentoProcessos: TDataModule},
  DebugUtils in 'DebugUtils.pas' {FormDebugUtils},
  frmIntegracaoPhilips in 'frmIntegracaoPhilips.pas' {FormIntegracaoPhilips},
  KrDetalheMercadoria in 'KrDetalheMercadoria.pas',
  KrCloneDataSet in 'KrCloneDataSet.pas',
  FrmRlBASFArmazenagemExpoCtx in 'FrmRlBASFArmazenagemExpoCtx.pas' {FormRlBASFArmazenagemExpoCtx},
  KrDialog in 'KrDialog.pas',
  KrGlobal in 'KrGlobal.pas',
  UAtualizaDatasLisProcesso in 'UAtualizaDatasLisProcesso.pas' {frmAtualizaDatasLisProcesso},
  UAtualizaDatasOrgaosAnuentesProcesso in 'UAtualizaDatasOrgaosAnuentesProcesso.pas' {frmAtualizaDatasOrgaosAnuentesProcesso},
  uConfigurarEnvioArquivosEmail in 'uConfigurarEnvioArquivosEmail.pas' {frmConfigurarEnvioArquivosEmail},
  datm_ConfigEnvioArquivosEmail in 'datm_ConfigEnvioArquivosEmail.pas' {datm_ConfigEnvioEmail: TDataModule},
  UConsultaMercanteDivergencias in 'UConsultaMercanteDivergencias.pas' {frmConsultaMercanteDivergencias},
  RlDIValoresPorAdicao in 'RlDIValoresPorAdicao.pas',
  FrAnvisa in 'FrAnvisa.pas' {FormAnvisa},
  URelProformaNestleING in 'URelProformaNestleING.pas' {frmRelProformaNestleING},
  URelCaricomNestleING in 'URelCaricomNestleING.pas' {frmRelCaricomNestleING},
  URelInternalExportDocumentNestleESP in 'URelInternalExportDocumentNestleESP.pas' {frmRelInternalExportDocumentNestleESP},
  URelSaqueNestleING in 'URelSaqueNestleING.pas' {frmRelSaqueNestleING},
  URelOrdemLiberacaoProcessoNestlePOR in 'URelOrdemLiberacaoProcessoNestlePOR.pas' {frmRelOrdemLiberacaoProcessoNestlePOR},
  URelBorderoNestlePOR in 'URelBorderoNestlePOR.pas' {frmRelBorderoNestlePOR},
  URelProgramacaoRodoviariaNestlePOR in 'URelProgramacaoRodoviariaNestlePOR.pas' {frmRelProgramacaoRodoviariaNestlePOR},
  UConsultaMercante in 'UConsultaMercante.pas' {frmConsultaMercante},
  dRE_NOVOEX in 'dRE_NOVOEX.pas' {datmRE_NOVOEX: TDataModule},
  uRE_NOVOEX in 'uRE_NOVOEX.pas' {frmRE_NovoEx},
  datm_RelatoriosNestle in 'datm_RelatoriosNestle.pas' {datm_RelatorioNestle: TDataModule},
  URelatoriosNestle in 'URelatoriosNestle.pas' {frmRelatoriosNestle},
  URelShippingInstructionsNestle in 'URelShippingInstructionsNestle.pas' {frmRelShippingInstructionsNestle},
  URlPhilipsFaturadosCtx in 'URlPhilipsFaturadosCtx.pas' {FrmRlPhilipsFaturadosCtx},
  uRelPackingListNestleESP in 'uRelPackingListNestleESP.pas' {frmRelPackingListNestleESP},
  uFatores in 'uFatores.pas' {frmFatores},
  dFatores in 'dFatores.pas' {datmFatores: TDataModule},
  URelatorioLIs in 'URelatorioLIs.pas' {frmRelatorioLIs},
  FrNumerariosNestle in 'FrNumerariosNestle.pas' {frmNumerariosNestle},
  URelFaturamentoLIs in 'URelFaturamentoLIs.pas' {frmRelFaturamentoLIs},
  uRelatorioMercadorias in 'uRelatorioMercadorias.pas' {frmRelatorioMercadorias},
  FrmRlWhirlpoolFaturadosComissoesCtx in 'FrmRlWhirlpoolFaturadosComissoesCtx.pas' {FormRlWhirlpoolFaturadosComissoesCtx},
  FrmRlWhirlpoolAFaturarCtx in 'FrmRlWhirlpoolAFaturarCtx.pas' {FormRlWhirlpoolAFaturarCtx},
  FrFaturadosMattel in 'FrFaturadosMattel.pas' {frmFaturadosMattel},
  FrmRlBASFPagmtoAFRMM in 'FrmRlBASFPagmtoAFRMM.pas' {FormRlBASFPagmtoAFRMM},
  uRelPagamentoAFRMM in 'uRelPagamentoAFRMM.pas' {frmRelPagamentoAFRMM},
  URelPagamentoAFRMMCtx in 'URelPagamentoAFRMMCtx.pas' {frmRelPagamentoAFRMMCtx},
  usemaforico in 'usemaforico.pas' {frm_semaforico},
  frFaturadosNestleSemanal in 'frFaturadosNestleSemanal.pas' {frmFaturadosNestleSemanal},
  USelecionaTiposDoctosEmail in 'USelecionaTiposDoctosEmail.pas' {frmSelecionaTiposDoctosEmail},
  UCadPendenciasProc in 'UCadPendenciasProc.pas' {frmCadPendenciasProc},
  uLI_Importa_XML in 'uLI_Importa_XML.pas' {frmLi_Importa_XML},
  uArquivoCroda in 'uArquivoCroda.pas' {frmArquivoCroda},
  uPrometeonEDI in 'uPrometeonEDI.pas' {frmPrometeonEDI},
  FrmRelDespesasPagasCtxSG in 'FrmRelDespesasPagasCtxSG.pas' {FormRelDepesasPagasCtxSG},
  FrDespesasClienteBASF in 'FrDespesasClienteBASF.pas' {frmDespesasClienteBASF},
  uImportarPlanilhaItensDI in 'uImportarPlanilhaItensDI.pas' {frmImportarPlanilhaItensDI},
  uIntegraNotaBasf_Filhotes in 'uIntegraNotaBasf_Filhotes.pas' {frm_integra_nota_basf_filhotes},
  uImportarXMLDISiscomex in 'uImportarXMLDISiscomex.pas' {frmImportarXMLDISiscomex},
  ExternalApplication in 'ExternalApplication.pas',
  FrmRlYaraFaturadosComissoesCtx in 'FrmRlYaraFaturadosComissoesCtx.pas' {FormRlYaraFaturadosComissoesCtx},
  uRelCertificadoVigilanciaSanitariaNestle in 'uRelCertificadoVigilanciaSanitariaNestle.pas' {frmRelCertificadoVigilanciaSanitariaNestle},
  uFaturaComercialPetronas in 'uFaturaComercialPetronas.pas' {frmFaturaComercialPetronas},
  uDocumentosExportacao in 'uDocumentosExportacao.pas' {frmDocumentosExportacao},
  udatm_DocumentosExportacao in 'udatm_DocumentosExportacao.pas' {datm_DocumentosExportacao: TDataModule},
  uPackingListPetronas in 'uPackingListPetronas.pas' {frmPackingListPetronas},
  FrNumerariosYara in 'FrNumerariosYara.pas' {frmNumerariosYara},
  uImportarPlanilhaPetronasExp in 'uImportarPlanilhaPetronasExp.pas' {frmImportarPlanilhaPetronasExp},
  uValidarLotesNestle in 'uValidarLotesNestle.pas' {frmValidarLotesNestle},
  uRelatoriosNestleConfigEmail in 'uRelatoriosNestleConfigEmail.pas' {frmRelatoriosNestleConfigEmail},
  FerreroDIeImpostosEASY in 'FerreroDIeImpostosEASY.pas' {FormFerreroDIeImpostosEASY},
  CdAcorodoComercial in 'CdAcorodoComercial.PAS' {frmCdAcordoComercial},
  KrComunication in 'KrComunication.pas',
  CdDeclarcaoOrigem in 'CdDeclarcaoOrigem.pas' {frmCdDeclaracaoOrigem},
  KrAuditoria in 'KrAuditoria.pas',
  FrmFaturadosSaldoFaturaCtxAprovComissao in 'FrmFaturadosSaldoFaturaCtxAprovComissao.pas' {FormFaturadosSaldoFaturaCtxAprovComissao},
  uConsultaIntegracaoSAPCargil in 'uConsultaIntegracaoSAPCargil.pas' {fmConsultaIntegracaoSAPCargil},
  uConsultaIntegracaoSAPCargilCtx in 'uConsultaIntegracaoSAPCargilCtx.pas' {fmConsultaIntegracaoSAPCargilCtx},
  frmAjuda in 'frmAjuda.pas' {formAjuda},
  uIntegracaoNotaNestle in 'uIntegracaoNotaNestle.pas' {frm_integracao_nota_nestle},
  FrmRlRousselotFaturadosDespesasCtx in 'FrmRlRousselotFaturadosDespesasCtx.pas' {FormRlRousselotFaturadosDespesasCtx},
  uIntegracaoAberturaProcessoNestle in 'uIntegracaoAberturaProcessoNestle.pas' {frm_integracao_abertura_processo_nestle},
  uIntegracaoAberturaProcessoNestleLean in 'uIntegracaoAberturaProcessoNestleLean.pas' {frm_integracao_abertura_processo_nestle_Lean},
  uIntegracaoBookingInttra in 'uIntegracaoBookingInttra.pas' {fmIntegracaoBookingInttra},
  FrmRlSaintGobainFaturadosCtx in 'FrmRlSaintGobainFaturadosCtx.pas' {FormRlSaintGobainFaturadosCtx},
  FrmIntegracaoApolo in 'frmIntegracaoApolo.pas' {FormIntegracaoApolo},
  FrmIntegracaoNestleExpItemLote in 'frmIntegracaoNestleExpItemLote.pas' {FormIntegracaoNestleExpItemLote},
  uIntegracaoNotaEssity in 'uIntegracaoNotaEssity.pas' {frm_integracao_nota_essity},
  uIntegracaoNotaNexans in 'uIntegracaoNotaNexans.pas' {frm_integracao_nota_nexans},
  uIntegracaoNumerarioMattel in 'uIntegracaoNumerarioMattel.pas' {frm_integracao_numerario_mattel},
  USelecionaProcTransitTime in 'USelecionaProcTransitTime.pas' {frmSelecionaProcTransitTime},
  FrFaturadosHusqvarna in 'FrFaturadosHusqvarna.pas' {frmFaturadosHusqvarna},
  frAnvisaNestle in 'frAnvisaNestle.pas' {frmAnvisaNestle};

{$R *.res}

//var
//  HMain: HWND;

procedure AtualizaRegistro;
  //HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION
var
  R: TRegistry;
  App: string;
begin
  R := TRegistry.Create;
  try
    App       := ExtractFileName(ParamStr(0));
    R.RootKey := HKEY_CURRENT_USER;
    if R.OpenKey('SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION', True) then
    begin
      R.WriteInteger(App, $2af9); //IE11
    end;
  finally
    R.Free;
  end;
end;

procedure RemoveRegistroIE;
  //HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION
var
  R: TRegistry;
  App: string;
begin
  R := TRegistry.Create;
  try
    App       := ExtractFileName(ParamStr(0));
    R.RootKey := HKEY_CURRENT_USER;
    if R.OpenKey('SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION', True) then
    begin
       r.DeleteValue(App);
    end;
  finally
    R.Free;
  end;
end;

begin
  AtualizaRegistro;
  //RemoveRegistroIE;
  Screen.Cursor := crAppStart;
  Application.Initialize;
  screen.Cursor     := crDefault;
  Application.Title := 'MyIndaiá';
  {HMain := FindWindow('Tfrm_main', nil);
  if HMain > 0 then
  begin
    ShowWindow(HMain, SW_SHOW);
    SetActiveWindow(HMain);
    SetForegroundWindow(HMain);
    Halt;
  end;}
  Application.CreateForm(Tfrm_main, frm_main);
  Application.CreateForm(Tfrm_senha, frm_senha);
  Application.CreateForm(TfrmHistoricoClalculoDI, frmHistoricoClalculoDI);
  Application.CreateForm(Tfrm_pendencias, frm_pendencias);
  Application.CreateForm(TfrmSelecionaProcTransitTime, frmSelecionaProcTransitTime);
  Application.CreateForm(TfrmFaturadosHusqvarna, frmFaturadosHusqvarna);
  Application.CreateForm(TfrmAnvisaNestle, frmAnvisaNestle);
  // Adicionado para tentar contornar o erro de lock file
  {if not DirectoryExists(ExtractFilePath(ParamStr(0)) + 'PRIV') then
    MkDir(ExtractFilePath(ParamStr(0)) + 'PRIV');
  if DirectoryExists(ExtractFilePath(ParamStr(0)) + 'PRIV') then
    Session.PrivateDir := ExtractFilePath(ParamStr(0)) + 'PRIV';
  if not DirectoryExists(ExtractFilePath(ParamStr(0)) + 'REDE') then
    MkDir(ExtractFilePath(ParamStr(0)) + 'REDE');
  if DirectoryExists(ExtractFilePath(ParamStr(0)) + 'REDE') then
    Session.NetFileDir := ExtractFilePath(ParamStr(0)) + 'REDE';}

  Application.CreateForm(Tdatm_main, datm_main);
  // definindo as cores de menu e paineis de destaque
  clMenuBroker     := clBtnFace;//RGB(getRValue(ColorToRGB(clBtnFace)) - 15, getGValue(ColorToRGB(clBtnFace)) - 15, getBValue(ColorToRGB(clBtnFace)) - 8);
  clPnlClaroBroker := clBtnFace;//RGB(getRValue(ColorToRGB(clBtnFace)) + 20 , getGValue(ColorToRGB(clBtnFace)) + 20 , getBValue(ColorToRGB(clBtnFace)) + 20 );
  Application.Run;
end.

