unit PGCH037;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Db, DBTables, ppEndUsr, ppProd, ppClass, ppReport, ppComm, ppRelatv,
  ppCache, ppDB, ppDBPipe, ppDBBDE, ppBands, ppCtrls, ppVar, ppPrnabl,
  ppMemo, ppStrtch, ppRegion, ppParameter;

type
  Tdatm_sel_relat = class(TDataModule)
    qry_unid_neg_: TQuery;
    ds_unid_neg: TDataSource;
    qry_produto_: TQuery;
    qry_grupo_: TQuery;
    qry_cliente_: TQuery;
    ds_produto: TDataSource;
    ds_grupo: TDataSource;
    ds_cliente: TDataSource;
    qry_unid_neg_CD_UNID_NEG: TStringField;
    qry_unid_neg_NM_UNID_NEG: TStringField;
    qry_produto_CD_PRODUTO: TStringField;
    qry_produto_NM_PRODUTO: TStringField;
    qry_grupo_CD_GRUPO: TStringField;
    qry_grupo_NM_GRUPO: TStringField;
    qry_cliente_CD_EMPRESA: TStringField;
    qry_cliente_AP_EMPRESA: TStringField;
    sp_rel_retencao: TStoredProc;
    ppBDERelRetencao: TppBDEPipeline;
    ppRelUnidProd: TppReport;
    ppDesigner: TppDesigner;
    qry_rel_retencao_: TQuery;
    ds_rel_retencao: TDataSource;
    qry_rel_retencao_CD_EMPRESA: TStringField;
    qry_rel_retencao_AP_EMPRESA: TStringField;
    qry_rel_retencao_CNPJ_EMPRESA: TStringField;
    qry_rel_retencao_CD_GRUPO_CLIENTE: TStringField;
    qry_rel_retencao_NR_NOTA_FATURA: TStringField;
    qry_rel_retencao_DT_FATURA: TDateTimeField;
    qry_rel_retencao_VL_NUMERARIO: TFloatField;
    qry_rel_retencao_VL_COMISSAO: TFloatField;
    qry_rel_retencao_VL_ITEM_COFINS_RETENCAO: TFloatField;
    qry_rel_retencao_VL_IRRF: TFloatField;
    qry_rel_retencao_VL_NAO_TRIBUTAVEL: TFloatField;
    qry_rel_retencao_VL_TRIBUTAVEL: TFloatField;
    qry_rel_retencao_VL_SALDO_FAT: TFloatField;
    qry_rel_retencao_VL_TOTAL_FATURA: TFloatField;
    qry_rel_retencao_VL_ISS: TFloatField;
    qry_rel_retencao_CalcNrProcesso: TStringField;
    qry_rel_retencao_NR_PROCESSO: TStringField;
    sp_rel_proc_andamento: TStoredProc;
    ds_rel_proc_andamento: TDataSource;
    qry_rel_proc_andamento_: TQuery;
    qry_rel_proc_desembaracados_: TQuery;
    sp_rel_proc_desembaracados: TStoredProc;
    ds_proc_desembaracados: TDataSource;
    qry_rel_proc_desembaracados_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_proc_desembaracados_NR_PROCESSO_INDAIA: TStringField;
    qry_rel_proc_desembaracados_NR_PROC_PO: TStringField;
    qry_rel_proc_desembaracados_AP_MERCADORIA: TStringField;
    qry_rel_proc_desembaracados_NM_EMPRESA: TStringField;
    qry_rel_proc_desembaracados_NM_EMBARCACAO: TStringField;
    qry_rel_proc_desembaracados_DT_CHEGADA_EMBARCACAO: TDateTimeField;
    qry_rel_proc_desembaracados_DT_REG_DI: TDateTimeField;
    qry_rel_proc_desembaracados_TX_CAMBIO: TFloatField;
    qry_rel_proc_desembaracados_DT_SOL_NF: TDateTimeField;
    qry_rel_proc_desembaracados_DT_RECEB_NF: TDateTimeField;
    qry_rel_proc_desembaracados_DT_CI: TDateTimeField;
    qry_rel_proc_desembaracados_DT_ENTERGA_NF_TRANSP: TDateTimeField;
    qry_rel_proc_desembaracados_DT_FATURAMENTO: TDateTimeField;
    qry_rel_proc_desembaracados_NR_DIAS_DESP: TIntegerField;
    qry_rel_proc_desembaracados_NR_ITEM: TStringField;
    qry_rel_proc_andamento_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_proc_andamento_NR_PROCESSO_INDAIA: TStringField;
    qry_rel_proc_andamento_NR_PROC_PO: TStringField;
    qry_rel_proc_andamento_NR_ITEM_PO: TStringField;
    qry_rel_proc_andamento_AP_MERCADORIA: TStringField;
    qry_rel_proc_andamento_QT_MERC_UN_COMERC: TFloatField;
    qry_rel_proc_andamento_NM_EMPRESA: TStringField;
    qry_rel_proc_andamento_DT_RECEB_PO: TDateTimeField;
    qry_rel_proc_andamento_DT_RECEB_COPIAS: TDateTimeField;
    qry_rel_proc_andamento_NM_EMBARCACAO: TStringField;
    qry_rel_proc_andamento_DT_CHEGADA_EMBARCACAO: TDateTimeField;
    qry_rel_proc_andamento_DT_CAMBIO: TDateTimeField;
    qry_rel_proc_andamento_DT_SOL_NUMERARIO: TDateTimeField;
    qry_rel_proc_andamento_DT_RECEB_NUMERARIO: TDateTimeField;
    qry_rel_proc_andamento_DT_SOL_NUMERARIO_IMP: TDateTimeField;
    qry_rel_proc_andamento_DT_RECEB_DOCUMENTOS: TDateTimeField;
    qry_rel_proc_andamento_DT_REGISTRO_DI: TDateTimeField;
    qry_rel_proc_andamento_NM_CANAL: TStringField;
    qry_rel_proc_andamento_DT_SOL_NF: TDateTimeField;
    qry_rel_proc_andamento_DT_REC_NF: TDateTimeField;
    qry_rel_proc_andamento_DT_CI: TDateTimeField;
    qry_rel_proc_andamento_DT_ENTERGA_NF_TRANSP: TDateTimeField;
    qry_rel_proc_andamento_DT_EMISSAO_LI: TDateTimeField;
    qry_rel_proc_andamento_DT_REFERIMENTO_LI: TDateTimeField;
    qry_rel_proc_andamento_NR_DIAS_DESP: TIntegerField;
    qry_rel_proc_andamento_TX_OBSERVACOES: TMemoField;
    qry_rel_proc_desembaracados_QT_MERC_UN_COMERC: TStringField;
    qry_rel_mapa_an_: TQuery;
    ds_rel_mapa_an: TDataSource;
    qry_rel_mapa_an_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_mapa_an_CD_REFERENCIA: TStringField;
    qry_rel_mapa_an_AP_MERCADORIA: TStringField;
    qry_rel_mapa_an_QT_PESO_LIQ: TFloatField;
    qry_rel_mapa_an_NM_EMBARCACAO: TStringField;
    qry_rel_mapa_an_DT_PREV_CHEGADA: TDateTimeField;
    qry_rel_mapa_an_DT_EMBARQUE: TDateTimeField;
    qry_rel_mapa_an_NR_RE: TStringField;
    qry_rel_mapa_an_IN_RE: TStringField;
    qry_rel_mapa_an_DT_CI: TStringField;
    qry_rel_mapa_an_DESCRICAO: TStringField;
    qry_rel_mapa_an_NM_AGENTE: TStringField;
    qry_rel_mapa_an_NR_SD: TStringField;
    qry_rel_mapa_an_QT_CNTR: TStringField;
    sp_rel_mapa_an: TStoredProc;
    qry_rel_mapa_an_NR_PROCESSO: TStringField;
    qry_rel_qt_processos_: TQuery;
    sp_rel_qt_processos: TStoredProc;
    ds_rel_qt_processos: TDataSource;
    qry_rel_mapa_an_DT_SAIDA: TDateTimeField;
    qry_rel_mapa_an_DT_ETA: TDateTimeField;
    qry_destino_: TQuery;
    ds_destino: TDataSource;
    qry_destino_CODIGO: TStringField;
    qry_destino_DESCRICAO: TStringField;
    qry_modal_: TQuery;
    ds_modal: TDataSource;
    qry_modal_CD_VIA_TRANSPORTE: TStringField;
    qry_analista_cliente_: TQuery;
    ds_analista: TDataSource;
    qry_analista_cliente_CD_CONTATO: TStringField;
    qry_analista_cliente_NM_CONTATO: TStringField;
    qry_rel_mapa_an_AP_EMPRESA: TStringField;
    qry_modal_DESCRICAO: TStringField;
    qry_rel_qt_processos_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_qt_processos_NR_PROCESSO: TStringField;
    qry_rel_qt_processos_DT_ABERTURA: TStringField;
    sp_rel_acomp_proc: TStoredProc;
    qry_rel_acomp_proc_: TQuery;
    qry_rel_acomp_proc_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_acomp_proc_NR_PROCESSO_INDAIA: TStringField;
    qry_rel_acomp_proc_NR_PROC_PO: TStringField;
    qry_rel_acomp_proc_NM_SIGLA_PO: TStringField;
    qry_rel_acomp_proc_NR_ITEM_PO: TStringField;
    qry_rel_acomp_proc_CD_CIAFILIAL: TStringField;
    qry_rel_acomp_proc_TP_MERC: TStringField;
    qry_rel_acomp_proc_CFI: TStringField;
    qry_rel_acomp_proc_AP_MERCADORIA: TStringField;
    qry_rel_acomp_proc_CD_NCM: TStringField;
    qry_rel_acomp_proc_QT_EMBARCADA: TFloatField;
    qry_rel_acomp_proc_QT_RECEBIDA: TFloatField;
    qry_rel_acomp_proc_CD_UNID_MED_COMERC: TStringField;
    qry_rel_acomp_proc_TP_EMBALAGEM: TStringField;
    qry_rel_acomp_proc_NR_CNTR: TIntegerField;
    qry_rel_acomp_proc_TP_VIA_TRANSP: TStringField;
    qry_rel_acomp_proc_CD_INCOTERM: TStringField;
    qry_rel_acomp_proc_AP_FABRICANTE: TStringField;
    qry_rel_acomp_proc_NM_PAIS: TStringField;
    qry_rel_acomp_proc_AP_FORNECEDOR: TStringField;
    qry_rel_acomp_proc_NR_FATURA: TStringField;
    qry_rel_acomp_proc_VL_FOB_MNEG: TFloatField;
    qry_rel_acomp_proc_CD_MOEDA_FOB_MNEG: TStringField;
    qry_rel_acomp_proc_VL_UNITARIO_FOB_MNEG: TFloatField;
    qry_rel_acomp_proc_CD_MOEDA_UNITARIO_FOB_MNEG: TStringField;
    qry_rel_acomp_proc_VL_FRETE_MNEG: TFloatField;
    qry_rel_acomp_proc_CD_MOEDA_FRETE_MNEG: TStringField;
    qry_rel_acomp_proc_VL_UNITARIO_FRETE_MNEG: TFloatField;
    qry_rel_acomp_proc_CD_MOEDA_UNITARIO_FRETE_MNEG: TStringField;
    qry_rel_acomp_proc_VL_CFR_MNEG: TFloatField;
    qry_rel_acomp_proc_CD_MOEDA_CFR_MNEG: TStringField;
    qry_rel_acomp_proc_VL_UNITARIO_CFR_MNEG: TFloatField;
    qry_rel_acomp_proc_CD_MOEDA_UNITARIO_CFR_MNEG: TStringField;
    qry_rel_acomp_proc_VL_SEGURO_MNEG: TFloatField;
    qry_rel_acomp_proc_CD_MOEDA_SEGURO_MNEG: TStringField;
    qry_rel_acomp_proc_VL_CIF_MNEG: TFloatField;
    qry_rel_acomp_proc_VL_CIF: TFloatField;
    qry_rel_acomp_proc_TP_DRAWBACK: TStringField;
    qry_rel_acomp_proc_AP_PORTO_AERO_ORIGEM: TStringField;
    qry_rel_acomp_proc_AP_PAIS_PROCEDENCIA: TStringField;
    qry_rel_acomp_proc_AP_PORTO_AERO_DESTINO: TStringField;
    qry_rel_acomp_proc_AP_NAVIO: TStringField;
    qry_rel_acomp_proc_AP_TRANSBORDO: TStringField;
    qry_rel_acomp_proc_DT_EMBARQUE: TDateTimeField;
    qry_rel_acomp_proc_DT_CHEGADA: TDateTimeField;
    qry_rel_acomp_proc_DT_DESEMBARACO: TDateTimeField;
    qry_rel_acomp_proc_TX_OBSERVACOES: TMemoField;
    qry_rel_acomp_proc_NM_DIAS: TIntegerField;
    qry_rel_acomp_proc_NM_CANAL: TStringField;
    qry_rel_acomp_proc_PR_PAGAMENTO: TStringField;
    qry_rel_acomp_proc_NR_DI: TStringField;
    qry_rel_acomp_proc_VL_ADIANTAMENTO_1: TFloatField;
    qry_rel_acomp_proc_DT_ADIANTAMENTO_1: TDateTimeField;
    qry_rel_acomp_proc_VL_ADIANTAMENTO_2: TFloatField;
    qry_rel_acomp_proc_DT_ADIANTAMENTO_2: TDateTimeField;
    qry_rel_acomp_proc_VL_ACERTO: TFloatField;
    qry_rel_acomp_proc_DT_ACERTO: TDateTimeField;
    qry_rel_acomp_proc_TP_ACERTO: TStringField;
    qry_rel_acomp_proc_VL_SALDO_ACERTO: TFloatField;
    qry_rel_acomp_proc_VL_HONORARIO: TFloatField;
    qry_rel_acomp_proc_NR_NOTA_HONORARIO: TStringField;
    qry_rel_acomp_proc_DT_PAGAMENTO: TDateTimeField;
    qry_rel_acomp_proc_VL_SDA: TFloatField;
    qry_rel_acomp_proc_VL_DESPACHANTES: TFloatField;
    qry_rel_acomp_proc_NM_DETALHAMENTO: TStringField;
    qry_rel_acomp_proc_VL_CPMF: TFloatField;
    qry_rel_acomp_proc_VL_TAXA_DI: TFloatField;
    qry_rel_acomp_proc_VL_ICMS: TFloatField;
    qry_rel_acomp_proc_VL_ICMS_MNEG: TFloatField;
    qry_rel_acomp_proc_NM_BANCO: TStringField;
    qry_rel_acomp_proc_DT_PAGTO_BCO: TDateTimeField;
    qry_rel_acomp_proc_PC_IPI: TFloatField;
    qry_rel_acomp_proc_VL_IPI: TFloatField;
    qry_rel_acomp_proc_VL_IPI_MNEG: TFloatField;
    qry_rel_acomp_proc_PC_II: TFloatField;
    qry_rel_acomp_proc_VL_II: TFloatField;
    qry_rel_acomp_proc_VL_II_MNEG: TFloatField;
    qry_rel_acomp_proc_VL_AFRMM: TFloatField;
    qry_rel_acomp_proc_VL_TX_SICOMEX: TFloatField;
    qry_rel_acomp_proc_VL_TX_REG_LI: TFloatField;
    qry_rel_acomp_proc_VL_FUNDAF: TFloatField;
    qry_rel_acomp_proc_VL_MULTAS: TFloatField;
    qry_rel_acomp_proc_NM_MOTIVO: TStringField;
    qry_rel_acomp_proc_VL_TAXI_ENG: TFloatField;
    qry_rel_acomp_proc_NM_LANCHA: TStringField;
    qry_rel_acomp_proc_VL_LANCHA: TFloatField;
    qry_rel_acomp_proc_NM_LAUDO_TEC: TStringField;
    qry_rel_acomp_proc_VL_LAUDO_TEC: TFloatField;
    qry_rel_acomp_proc_NM_MINISTERIO: TStringField;
    qry_rel_acomp_proc_VL_LAUDO_MINISTERIO: TFloatField;
    qry_rel_acomp_proc_VL_RECEITA_FED: TFloatField;
    qry_rel_acomp_proc_VL_TUP_SOP: TFloatField;
    qry_rel_acomp_proc_VL_CAPATAZIA: TFloatField;
    qry_rel_acomp_proc_VL_MOVIMENTACAO: TFloatField;
    qry_rel_acomp_proc_VL_ATRACACAO: TFloatField;
    qry_rel_acomp_proc_VL_DRAGAGEM: TFloatField;
    qry_rel_acomp_proc_VL_DESCONSOLIDACAO: TFloatField;
    qry_rel_acomp_proc_VL_DESP_AERO: TFloatField;
    qry_rel_acomp_proc_VL_DESP_AERO_MNEG: TFloatField;
    qry_rel_acomp_proc_VL_ARMAZENAGEM: TFloatField;
    qry_rel_acomp_proc_NM_TERMINAL: TStringField;
    qry_rel_acomp_proc_NM_AGENCIA: TStringField;
    qry_rel_acomp_proc_VL_FRETE: TFloatField;
    qry_rel_acomp_proc_DT_PAGTO_FR: TDateTimeField;
    qry_rel_acomp_proc_VL_FRETE_TX_AGENCIA: TFloatField;
    qry_rel_acomp_proc_VL_TX_LIB_BL: TFloatField;
    qry_rel_acomp_proc_VL_TX_LIB_BL_MNEG: TFloatField;
    qry_rel_acomp_proc_NM_FUMIGACAO: TStringField;
    qry_rel_acomp_proc_VL_FUMIGACAO: TFloatField;
    qry_rel_acomp_proc_VL_DEMURRAGE: TFloatField;
    qry_rel_acomp_proc_VL_DEMURRAGE_MNEG: TFloatField;
    qry_rel_acomp_proc_DT_PAGTO_DEM: TDateTimeField;
    sp_rel_controle_emb: TStoredProc;
    qry_controle_emb_: TQuery;
    qry_controle_emb_NR_IDENTIFICADOR: TIntegerField;
    qry_controle_emb_NR_PROCESSO: TStringField;
    qry_controle_emb_NR_PO: TStringField;
    qry_controle_emb_NM_AGENTE: TStringField;
    qry_controle_emb_NM_EXPORTADOR: TStringField;
    qry_controle_emb_TX_MERCADORIA: TMemoField;
    qry_controle_emb_IMO: TStringField;
    qry_controle_emb_QT_PESO: TFloatField;
    qry_controle_emb_NM_MODALIDADE: TStringField;
    qry_controle_emb_NR_CNTR: TStringField;
    qry_controle_emb_QT_EMBALAGEM: TStringField;
    qry_controle_emb_NM_NAVIO: TStringField;
    qry_controle_emb_DT_ETD: TDateTimeField;
    qry_controle_emb_NM_ETD: TStringField;
    qry_controle_emb_DT_ETA: TDateTimeField;
    qry_controle_emb_NM_ETA: TStringField;
    qry_controle_emb_NR_MASTER: TStringField;
    qry_controle_emb_NR_HOUSE: TStringField;
    qry_controle_emb_VL_FRETE: TFloatField;
    qry_controle_emb_DT_ENV_DOC: TStringField;
    qry_controle_emb_TX_OBSERVACAO: TMemoField;
    qry_rel_acomp_proc_PC_PIS: TFloatField;
    qry_rel_acomp_proc_VL_PIS: TFloatField;
    qry_rel_acomp_proc_VL_PIS_MNEG: TFloatField;
    qry_rel_acomp_proc_PC_COFINS: TFloatField;
    qry_rel_acomp_proc_VL_COFINS: TFloatField;
    qry_rel_acomp_proc_VL_COFINS_MNEG: TFloatField;
    qry_rel_acomp_proc_TP_STATUS_ACERTO: TDateTimeField;
    ppParameterList1: TppParameterList;
    sp_rel_vl_retencao: TStoredProc;
    ppBDERelVlRetencao: TppBDEPipeline;
    qry_rel_valor_retencao_: TQuery;
    qry_rel_valor_retencao_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_valor_retencao_NR_PROCESSO: TStringField;
    qry_rel_valor_retencao_NR_SOLICITACAO: TStringField;
    qry_rel_valor_retencao_CD_CLIENTE: TStringField;
    qry_rel_valor_retencao_AP_CLIENTE: TStringField;
    qry_rel_valor_retencao_CD_GRUPO: TStringField;
    qry_rel_valor_retencao_NR_NOTA: TStringField;
    qry_rel_valor_retencao_DT_FATURA: TDateTimeField;
    qry_rel_valor_retencao_VL_TRIBUTAVEL: TFloatField;
    qry_rel_valor_retencao_VL_RETENCAO: TFloatField;
    qry_rel_valor_retencao_NR_NOTA_ACUMULADA: TStringField;
    qry_rel_valor_retencao_IN_STATUS: TStringField;
    qry_rel_valor_retencao_NM_USUARIO_CANC: TStringField;
    qry_rel_valor_retencao_DT_CANC: TDateTimeField;
    ds_rel_valor_retencao: TDataSource;
    qry_rel_valor_retencao_CalcNrProcesso: TStringField;
    qry_rel_acomp_proc_SIGLA_MOEDA_FOB_TOTAL: TStringField;
    qry_rel_acomp_proc_SIGLA_MOEDA_FOB_UNIT: TStringField;
    qry_rel_acomp_proc_SIGLA_MOEDA_FRETE_TOTAL: TStringField;
    qry_rel_acomp_proc_SIGLA_MOEDA_FRETE_UNIT: TStringField;
    qry_rel_acomp_proc_SIGLA_MOEDA_CFR_TOTAL: TStringField;
    qry_rel_acomp_proc_DT_EMISSAO_INT_1: TDateTimeField;
    qry_rel_acomp_proc_VL_RECEBIDO_INT_1: TFloatField;
    qry_rel_acomp_proc_DT_EMISSAO_INT_2: TDateTimeField;
    qry_rel_acomp_proc_VL_RECEBIDO_INT_2: TFloatField;
    qry_rel_acomp_proc_DT_DI: TStringField;
    ds_rel_dupont: TDataSource;
    qry_rel_dupont_: TQuery;
    qry_rel_dupont_DT_FATURA: TDateTimeField;
    qry_rel_dupont_NR_NOTA_FATURA: TStringField;
    qry_rel_dupont_NR_PROCESSO: TStringField;
    qry_rel_dupont_VL_NUM_TAXA: TFloatField;
    qry_rel_dupont_FUMIGACAO: TStringField;
    qry_rel_dupont_LOCAL_ENTREGA: TStringField;
    qry_rel_dupont_REF_EASY: TStringField;
    qry_rel_dupont_REF_SAP: TStringField;
    qry_rel_dupont_exp_: TQuery;
    qry_rel_dupont_exp_DT_FATURA: TDateTimeField;
    qry_rel_dupont_exp_NR_NOTA_FATURA: TStringField;
    qry_rel_dupont_exp_NR_PROCESSO: TStringField;
    qry_rel_dupont_exp_VL_NUM_TAXA: TFloatField;
    qry_rel_dupont_exp_FUMIGACAO: TStringField;
    qry_rel_dupont_exp_REF_EASY: TStringField;
    qry_rel_dupont_exp_REF_SAP: TStringField;
    qry_rel_dupont_exp_LOCAL_ENTREGA: TStringField;
    qry_rel_proc_desembaracados_NM_UNID_MEDIDA: TStringField;
    qry_rel_retencao_DT_VENCTO_FATURA: TDateTimeField;
    ppHeaderBand1: TppHeaderBand;
    ppImage1: TppImage;
    ppTitulo: TppLabel;
    ppLabel2: TppLabel;
    ppLabel4: TppLabel;
    ppLabel5: TppLabel;
    ppLabel7: TppLabel;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppLabel10: TppLabel;
    ppLabel11: TppLabel;
    ppLabel12: TppLabel;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppDetailBand1: TppDetailBand;
    ppDBText3: TppDBText;
    ppDBText4: TppDBText;
    ppDBText5: TppDBText;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBText14: TppDBText;
    ppFooterBand1: TppFooterBand;
    ppLine6: TppLine;
    ppVarRodapeDir: TppVariable;
    ppTotPag: TppSystemVariable;
    ppNumPag: TppSystemVariable;
    pplblCliente: TppLabel;
    pplblProduto: TppLabel;
    pplblUnidade: TppLabel;
    pplblArea: TppLabel;
    ppVarRodapeEsq: TppVariable;
    ppSummaryBand1: TppSummaryBand;
    ppLabel17: TppLabel;
    ppDBCalc19: TppDBCalc;
    ppDBCalc20: TppDBCalc;
    ppDBCalc21: TppDBCalc;
    ppDBCalc22: TppDBCalc;
    ppDBCalc23: TppDBCalc;
    ppDBCalc24: TppDBCalc;
    ppDBCalc25: TppDBCalc;
    ppDBCalc26: TppDBCalc;
    ppDBCalc27: TppDBCalc;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppLabel16: TppLabel;
    ppDBCalc10: TppDBCalc;
    ppDBCalc11: TppDBCalc;
    ppDBCalc12: TppDBCalc;
    ppDBCalc13: TppDBCalc;
    ppDBCalc14: TppDBCalc;
    ppDBCalc15: TppDBCalc;
    ppDBCalc16: TppDBCalc;
    ppDBCalc17: TppDBCalc;
    ppDBCalc18: TppDBCalc;
    ppGroup2: TppGroup;
    ppGroupHeaderBand2: TppGroupHeaderBand;
    ppLabel1: TppLabel;
    ppDBText1: TppDBText;
    ppLabel3: TppLabel;
    ppDBText2: TppDBText;
    ppLine1: TppLine;
    ppGroupFooterBand2: TppGroupFooterBand;
    ppLabel6: TppLabel;
    ppDBCalc1: TppDBCalc;
    ppDBCalc2: TppDBCalc;
    ppDBCalc3: TppDBCalc;
    ppDBCalc4: TppDBCalc;
    ppDBCalc5: TppDBCalc;
    ppDBCalc6: TppDBCalc;
    ppDBCalc7: TppDBCalc;
    ppDBCalc8: TppDBCalc;
    ppDBCalc9: TppDBCalc;
    ppLabel18: TppLabel;
    ppDBText15: TppDBText;
    ppBDERelRetencaoppField18: TppField;
    procedure qry_rel_retencao_CalcFields(DataSet: TDataSet);
    procedure ppTituloPrint(Sender: TObject);
    procedure ppVarRodapeEsqCalc(Sender: TObject; var Value: Variant);
    procedure ppVarRodapeDirCalc(Sender: TObject; var Value: Variant);
    procedure qry_rel_valor_retencao_CalcFields(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  datm_sel_relat: Tdatm_sel_relat;

implementation

uses PGCH036, GSMLIB, PGGP001;

{$R *.DFM}

procedure Tdatm_sel_relat.qry_rel_retencao_CalcFields(DataSet: TDataSet);
begin
  qry_rel_retencao_CalcNrProcesso.AsString := Copy( qry_rel_retencao_NR_PROCESSO.AsString, 5, 14 );
end;

procedure Tdatm_sel_relat.ppTituloPrint(Sender: TObject);
begin
    case frm_sel_relat.tp_rel of
       1 :     if frm_sel_relat.msk_dt_inicio.Date = frm_sel_relat.msk_dt_fim.Date Then
                 ppTitulo.Caption := 'Retenção de Impostos (Fatura) [ ' + FormatDateTime( 'dd/mm/yyyy', frm_sel_relat.msk_dt_inicio.Date ) + ' ]'
               else
                 ppTitulo.Caption := 'Retenção de Impostos (Fatura) [ ' + FormatDateTime( 'dd/mm/yyyy', frm_sel_relat.msk_dt_inicio.Date ) + ' a ' + FormatDateTime( 'dd/mm/yyyy', frm_sel_relat.msk_dt_fim.Date ) + ' ]';
       8 :     if frm_sel_relat.msk_dt_inicio.Date = frm_sel_relat.msk_dt_fim.Date Then
                 ppTitulo.Caption := 'Valores de Retenção [ ' + FormatDateTime( 'dd/mm/yyyy', frm_sel_relat.msk_dt_inicio.Date ) + ' ]'
               else
                 ppTitulo.Caption := 'Valores de Retenção [ ' + FormatDateTime( 'dd/mm/yyyy', frm_sel_relat.msk_dt_inicio.Date ) + ' a ' + FormatDateTime( 'dd/mm/yyyy', frm_sel_relat.msk_dt_fim.Date ) + ' ]';
    end;
end;

procedure Tdatm_sel_relat.ppVarRodapeEsqCalc(Sender: TObject;
  var Value: Variant);
begin
  case frm_sel_relat.tp_rel of
     1 : ppVarRodapeEsq.AsString := 'RBFAT004' + Space(5) + 'Emitido em ' + FormatDateTime( 'dd/mm/yyyy', dt_server ) + '  às  ' + FormatDateTime( 'hh:mm:ss', hr_server );
     8 : ppVarRodapeEsq.AsString := 'RBRET001' + Space(5) + 'Emitido em ' + FormatDateTime( 'dd/mm/yyyy', dt_server ) + '  às  ' + FormatDateTime( 'hh:mm:ss', hr_server );
  end;
end;

procedure Tdatm_sel_relat.ppVarRodapeDirCalc(Sender: TObject;
  var Value: Variant);
begin
  ppVarRodapeDir.AsString := 'Folha ' + ppNumPag.Text + ' / ' + ppTotPag.Text;
end;

procedure Tdatm_sel_relat.qry_rel_valor_retencao_CalcFields(DataSet: TDataSet);
begin
  qry_rel_valor_retencao_CalcNrProcesso.AsString := Copy( qry_rel_valor_retencao_NR_PROCESSO.AsString, 5, 14 );
end;

end.
