unit PGDI045;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Db, DBTables, IBCustomDataSet, IBDatabase, IBQuery;

type
  Tdatm_DI_saida = class(TDataModule)
    qry_grid_di_: TQuery;
    ds_grid_di: TDataSource;
    qry_grid_di_NR_PROCESSO: TStringField;
    qry_grid_di_CD_IMPORTADOR: TStringField;
    qry_grid_di_NM_EMPRESA: TStringField;
    qry_grid_di_CalcNrProcesso: TStringField;
    qry_di_: TQuery;
    qry_processo_: TQuery;
    qry_processo_cntr_: TQuery;
    ds_di: TDataSource;
    qry_ts_fatura_: TQuery;
    qry_faturamento_cc_: TQuery;
    qry_faturamento_cc_NR_PROCESSO: TStringField;
    qry_faturamento_cc_DT_LANCAMENTO: TDateTimeField;
    qry_faturamento_cc_CD_ITEM: TStringField;
    qry_faturamento_cc_VL_ITEM: TFloatField;
    qry_di_NR_PROCESSO: TStringField;
    qry_di_NR_IDENT_USUARIO: TStringField;
    qry_di_CD_APLICACAO_MERC: TStringField;
    qry_di_CD_BANDEIRA_TRANSP: TStringField;
    qry_di_CD_COBERTURA_CAMBIAL: TStringField;
    qry_di_CD_DESTAQUE_NCM: TStringField;
    qry_di_CD_FORMA_PAGAMENTO: TStringField;
    qry_di_CD_FUND_LEGAL_II: TStringField;
    qry_di_CD_IMPORTADOR: TStringField;
    qry_di_CD_INCOTERM: TStringField;
    qry_di_CD_LOCAL_EMBARQUE: TStringField;
    qry_di_CD_METODO_VALORACAO: TStringField;
    qry_di_CD_MODALIDADE_DESP: TStringField;
    qry_di_CD_MODALIDADE_PAGTO: TStringField;
    qry_di_CD_MOEDA_DESPESAS: TStringField;
    qry_di_CD_MOEDA_FRETE: TStringField;
    qry_di_CD_MOEDA_MLE: TStringField;
    qry_di_CD_MOEDA_SEGURO: TStringField;
    qry_di_CD_MOTIVO_SEM_COBERTURA: TStringField;
    qry_di_CD_MOTIVO_TRANS: TStringField;
    qry_di_CD_PAIS_IMPORTADOR: TStringField;
    qry_di_CD_PAIS_PROC_CARGA: TStringField;
    qry_di_CD_RECINTO_ALFAND: TStringField;
    qry_di_CD_REG_TRIB_II: TStringField;
    qry_di_CD_REG_TRIB_IPI: TStringField;
    qry_di_CD_SETOR_ARMAZENAM: TStringField;
    qry_di_CD_TIPO_AG_CARGA: TStringField;
    qry_di_CD_TIPO_CONSIG: TStringField;
    qry_di_CD_TIPO_DCTO_CARGA: TStringField;
    qry_di_CD_TIPO_DECLARACAO: TStringField;
    qry_di_CD_TIPO_IMPORTADOR: TStringField;
    qry_di_CD_TIPO_MANIFESTO: TStringField;
    qry_di_CD_TRANSPORTADOR: TStringField;
    qry_di_CD_URF_DESPACHO: TStringField;
    qry_di_CD_URF_ENTR_CARGA: TStringField;
    qry_di_CD_UTIL_DCTO_CARGA: TStringField;
    qry_di_CD_VIA_TRANSP_CARG: TStringField;
    qry_di_CD_VINC_IMPO_EXPO: TStringField;
    qry_di_DT_CHEGADA_CARGA: TStringField;
    qry_di_DT_EMBARQUE: TStringField;
    qry_di_DT_PROCESSAMENTO: TStringField;
    qry_di_DT_REGISTRO_DI: TStringField;
    qry_di_DT_TRANSMISSAO: TStringField;
    qry_di_IN_BEM_ENCOMENDA: TBooleanField;
    qry_di_IN_MATERIAL_USADO: TBooleanField;
    qry_di_IN_MOEDA_NACIONAL: TStringField;
    qry_di_IN_MOEDA_UNICA: TBooleanField;
    qry_di_IN_MULTIMODAL: TBooleanField;
    qry_di_IN_OPERACAO_FUNDAP: TBooleanField;
    qry_di_IN_RATEAR_FRETE_ITENS: TBooleanField;
    qry_di_IN_RATEAR_SEGURO_ITENS: TBooleanField;
    qry_di_IN_REPASSA_DADOS_ADICAO: TBooleanField;
    qry_di_IN_REPASSA_DADOS_CAMBIO: TBooleanField;
    qry_di_NM_CONSIGNATARIO: TStringField;
    qry_di_NM_VEICULO_TRANSP: TStringField;
    qry_di_NR_AGENTE_CARGA: TStringField;
    qry_di_NR_BANCO_COM: TStringField;
    qry_di_NR_BANCO_PAGAMENTO: TStringField;
    qry_di_NR_COMPRADOR_ME: TStringField;
    qry_di_NR_CONSIGNATARIO: TStringField;
    qry_di_NR_CONTRATO_CAMBIO: TStringField;
    qry_di_NR_CPF_REPR_LEGAL: TStringField;
    qry_di_NR_DCTO_CARGA: TStringField;
    qry_di_NR_DCTO_CARGA_MAST: TStringField;
    qry_di_NR_DECL_IMP_PROT: TStringField;
    qry_di_NR_DECLARACAO_IMP: TStringField;
    qry_di_NR_IDENTIFICACAO_COM: TStringField;
    qry_di_NR_MANIFESTO: TStringField;
    qry_di_NR_PRACA_COM: TStringField;
    qry_di_NR_PRACA_PAGAMENTO: TStringField;
    qry_di_NR_ROF: TStringField;
    qry_di_NR_VEICULO_TRANSP: TStringField;
    qry_di_PB_CARGA: TFloatField;
    qry_di_PC_COMISSAO: TFloatField;
    qry_di_PC_ICMS: TFloatField;
    qry_di_PC_REDUCAO_ICMS: TFloatField;
    qry_di_PL_CARGA: TFloatField;
    qry_di_QT_ADICOES: TIntegerField;
    qry_di_TX_INFO_COMPL: TMemoField;
    qry_di_VL_FRETE_TNAC_MNEG: TFloatField;
    qry_di_VL_TOT_DESPS_MN: TFloatField;
    qry_di_VL_TOT_DESPS_MNEG: TFloatField;
    qry_di_VL_TOT_FRT_COLLECT: TFloatField;
    qry_di_VL_TOT_FRT_PREPAID: TFloatField;
    qry_di_VL_TOT_MLE_MNEG: TFloatField;
    qry_di_VL_TOT_SEGURO_MNEG: TFloatField;
    qry_di_VL_TOTAL_FRETE_MN: TFloatField;
    qry_di_VL_TOTAL_MLE_MN: TFloatField;
    qry_di_VL_TOTAL_SEG_MN: TFloatField;
    qry_di_PC_SEGURO_MLE: TFloatField;
    qry_di_VL_TOTAL_II: TFloatField;
    qry_di_VL_TOTAL_IPI: TFloatField;
    qry_di_VL_TOTAL_AD: TFloatField;
    qry_di_DT_ULTIMA_ALTERACAO: TDateTimeField;
    qry_di_IN_RISC_ATUALIZADO: TStringField;
    qry_di_CD_TIPO_BASE_SEGURO: TStringField;
    qry_di_IN_REB: TStringField;
    qry_di_VL_TOT_ICMS: TFloatField;
    qry_di_CD_TIPO_PGTO_TRIB: TStringField;
    qry_di_NR_CONTA_PGTO_TRIB: TStringField;
    qry_di_TX_MLE: TFloatField;
    qry_di_TX_FRETE: TFloatField;
    qry_di_TX_SEGURO: TFloatField;
    qry_di_TX_DOLAR: TFloatField;
    qry_di_NR_REF_CLI: TStringField;
    qry_di_IN_SISCOMEX: TStringField;
    qry_di_CD_TIPO_ICMS: TStringField;
    qry_di_IN_ICMS_IMPRESSO: TStringField;
    qry_di_DT_ICMS_IMPRESSO: TDateTimeField;
    qry_di_VL_TOTAL_ACRESCIMOS_MN: TFloatField;
    qry_di_VL_TOTAL_DEDUCOES_MN: TFloatField;
    qry_di_DT_CALCULO: TDateTimeField;
    qry_di_VL_DESPESA_ITEM: TFloatField;
    qry_di_VL_DESPESA_ITEM_MN: TFloatField;
    qry_di_CD_ORGAO_FIN_INTER: TStringField;
    qry_di_CD_PRESENCA_CARGA: TStringField;
    qry_di_NR_SEQ_RETIFICACAO: TStringField;
    qry_di_CD_MOTIVO_RETIF: TStringField;
    qry_di_DT_RETIFICACAO: TDateTimeField;
    qry_di_DT_EXON_IMPRESSO: TDateTimeField;
    qry_di_IN_EXON_IMPRESSO: TStringField;
    qry_di_CD_TRIBUTACAO_ICMS: TStringField;
    qry_di_CD_FUND_LEGAL_ICMS: TStringField;
    qry_di_VL_TOTAL_CAMBIO: TFloatField;
    qry_di_CD_AUSENCIA_FABRIC: TStringField;
    qry_di_CD_FORNECEDOR: TStringField;
    qry_di_CD_FABRICANTE: TStringField;
    qry_di_CD_PAIS_AQUIS_MERC: TStringField;
    qry_di_CD_PAIS_ORIG_MERC: TStringField;
    qry_di_QT_PARC_FINANC_360: TIntegerField;
    qry_di_QT_PERIOD_PGTO_360: TIntegerField;
    qry_di_CD_PERIOD_PGTO_360: TStringField;
    qry_di_IN_EMBUT_FRT_ITENS: TBooleanField;
    qry_di_IN_EMBUT_SEG_ITENS: TBooleanField;
    qry_di_VL_TOTAL_ACRESCIMOS_MNEG: TFloatField;
    qry_di_VL_TOTAL_DEDUCOES_MNEG: TFloatField;
    qry_di_VL_TOTAL_FRETE_MNEG: TFloatField;
    qry_di_NR_PROCESSO_SISCOMEX: TStringField;
    qry_di_IN_PGTO_VARIAV_360: TBooleanField;
    qry_processo_cntr_TP_CNTR: TStringField;
    qry_ts_fatura_NR_NOTA_FATURA: TStringField;
    qry_dt_receb_doc_: TQuery;
    qry_dt_receb_doc_DT_REALIZACAO: TDateTimeField;
    qry_dt_desemb_: TQuery;
    qry_dt_entrega_merc_: TQuery;
    qry_instr_emb_: TQuery;
    qry_instr_emb_NR_DCTO_INSTRUCAO: TStringField;
    qry_dt_desemb_DT_REALIZACAO: TDateTimeField;
    qry_dt_entrega_merc_DT_REALIZACAO: TDateTimeField;
    qry_processo_CD_AGENTE: TStringField;
    qry_processo_CD_MOEDA_FRETE: TStringField;
    qry_processo_VL_TAXA_FRETE: TFloatField;
    qry_ddimport_: TQuery;
    sp_ddimport: TStoredProc;
    qry_ts_fatura_DT_FATURA: TDateTimeField;
    qry_ts_fatura_VL_FATURA: TFloatField;
    qry_ts_fatura_DT_PAGTO_ITEM: TDateTimeField;
    qry_dt_embarque_: TQuery;
    qry_dt_embarque_DT_REALIZACAO: TDateTimeField;
    qry_dt_prev_chegada_: TQuery;
    qry_dt_prev_chegada_DT_REALIZACAO: TDateTimeField;
    qry_dt_prev_entr_merc_: TQuery;
    qry_processo_CD_CANAL: TStringField;
    qry_processo_VL_CIF_DOLAR: TFloatField;
    qry_processo_nf_: TQuery;
    qry_dt_prev_entr_merc_DT_REALIZACAO: TDateTimeField;
    qry_instr_emb_CD_TIPO_DCTO_INSTR: TStringField;
    qry_faturamento_cc_IN_NAO_FAT: TStringField;
    qry_processo_nf_NR_NOTA: TStringField;
    qry_processo_nf_NR_PROCESSO: TStringField;
    qry_processo_nf_DT_NOTA: TDateTimeField;
    qry_processo_nf_VL_NOTA: TFloatField;
    qry_unid_neg_: TQuery;
    qry_unid_neg_CD_UNID_NEG: TStringField;
    qry_unid_neg_NM_UNID_NEG: TStringField;
    qry_grupo_: TQuery;
    qry_grupo_CD_GRUPO: TStringField;
    qry_grupo_NM_GRUPO: TStringField;
    qry_grupo_DT_INCLUSAO: TDateTimeField;
    qry_grupo_IN_ATIVO: TStringField;
    qry_cliente_: TQuery;
    qry_cliente_CD_EMPRESA: TStringField;
    qry_cliente_NM_EMPRESA: TStringField;
    qry_cliente_AP_EMPRESA: TStringField;
    qry_ddimport_desp_: TQuery;
    sp_ddimport_flp: TStoredProc;
    qry_ddimport_flp_: TQuery;
    qry_produto_: TQuery;
    sp_ddimport_custo: TStoredProc;
    qry_ddimport_custo_: TQuery;
    qry_itens_numerario_: TQuery;
    qry_itens_numerario_NR_PROCESSO: TStringField;
    qry_itens_numerario_DT_SOLICITACAO: TDateTimeField;
    qry_itens_numerario_CD_ITEM: TStringField;
    qry_itens_numerario_NM_ITEM: TStringField;
    qry_itens_numerario_VL_SOLICITADO: TFloatField;
    qry_itens_numerario_PAGA_POR_QUEM: TStringField;
    qry_itens_numerario_ADIANTAMENTO: TStringField;
    db_nota: TIBDatabase;
    qryNFCapa: TIBQuery;
    qryNFItens: TIBQuery;
    trNota: TIBTransaction;
    qryNFCapaSTR_CODIGOCFOP: TIBStringField;
    qryNFCapaSTR_REFERENCIA: TIBStringField;
    qryNFCapaDT_ABERTURAPROCESSO: TDateTimeField;
    qryNFCapaDT_DATACHEGADA: TDateTimeField;
    qryNFCapaDT_REGISTRODI: TDateTimeField;
    qryNFCapaSTR_REGISTRODI: TIBStringField;
    qryNFCapaSTR_VIATRANSPORTE: TIBStringField;
    qryNFCapaF_1: TFloatField;
    qryNFCapaDBL_VALORICMS: TFloatField;
    qryNFCapaDBL_BASEICMS: TFloatField;
    qryNFCapaSTR_CODIGOIMPORTADOR: TIBStringField;
    qryNFCapaSTR_CODIGOTRANSP: TIBStringField;
    qryNFCapaDBL_VALORSEGUROREAIS: TFloatField;
    qryNFCapaDBL_VALORIPIRECOLHER: TFloatField;
    qryNFCapaDBL_VALORORIGEMMOEDA: TFloatField;
    qryNFCapaSTR_CODIGOEXPORTADOR: TIBStringField;
    qryNFItensSTR_CODIGOPRODUTO: TIBStringField;
    qryNFItensSTR_REGIMETRIBICMSAD: TIBStringField;
    qryNFItensSTR_REGIMETRIBUTACAOIPI: TIBStringField;
    qryNFItensSTR_NUMEROITEM: TIBStringField;
    qryNFItensDBL_QUANTIDADE: TFloatField;
    qryNFItensSTR_UNIDADEMEDIDA: TIBStringField;
    qryNFItensDBL_VALORIPIRECOLHER: TFloatField;
    qryNFItensDBL_VALORORIGEMREAIS: TFloatField;
    qryNFItensMEM_DESCRICAOPRODUTO: TBlobField;
    qryNFItensDBL_VALORFOBREAIS: TFloatField;
    qryNFItensDBL_VALORFRETEREAIS: TFloatField;
    qryNFItensDBL_VALORSEGUROREAIS: TFloatField;
    qryNFItensDBL_VALORIIRECOLHER: TFloatField;
    qryNFItensDBL_ALIQUOTAPERCREDUIPI: TFloatField;
    qryNFItensDBL_DESPESASMOEDA: TFloatField;
    qryNFItensSTR_REFERENCIA: TIBStringField;
    qryNFItensSTR_EXNCM: TIBStringField;
    qryNFItensSTR_NUMEROFATURA: TIBStringField;
    qryNFItensDBL_VALORICMS: TFloatField;
    qryNFItensDBL_PESOLIQUIDO: TFloatField;
    qryNFItensDBL_ALIQUOTANORMALII: TFloatField;
    qryNFItensSTR_NUMEROPEDIDO: TIBStringField;
    qryNFItensDBL_BASENORMALICMS: TFloatField;
    qryNFItensDBL_VALORFOBMOEDA: TFloatField;
    qryNFItensDBL_ALIQUOTAPISPASEP: TFloatField;
    qryNFItensDBL_BASECALCULOPISPASEPCOFINS: TFloatField;
    qryNFItensDBL_VALORPISPASEPARECOLHER: TFloatField;
    qryNFItensDBL_ALIQUOTACOFINS: TFloatField;
    qryNFItensDBL_BASECALCULOPISPASEPCOFINS1: TFloatField;
    qryNFItensDBL_VALORCOFINSARECOLHER: TFloatField;
    qryNFItensSTR_NUMEROADICAO: TIBStringField;
    qryNFItensSTR_NUMEROITEM1: TIBStringField;
    procedure qry_grid_di_CalcFields(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  datm_DI_saida: Tdatm_DI_saida;

implementation

{$R *.DFM}



procedure Tdatm_DI_saida.qry_grid_di_CalcFields(DataSet: TDataSet);
begin
  qry_grid_di_CalcNrProcesso.AsString := Copy( qry_grid_di_NR_PROCESSO.AsString, 5, 14);
end;


end.
