unit PGFT020;
                               
interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Db, DBTables, ppDB, ppDBPipe, ppDBBDE, ppCtrls, ppVar, ppPrnabl, ppClass,
  ppBands, ppCache, ppRelatv, ppProd, ppReport, ppComm, ppEndUsr, TXtraDev,
  ppStrtch, ppMemo, ppModule, daDatMod, ExtCtrls, TeeProcs, TeEngine,
  Chart, ppChrt, Series, ppSubRpt, ppTxPipe, DBChart, daDataModule, ppParameter;
//  ppChrtDB,

type
  Tdatm_sel_unid_cli = class(TDataModule)
    qry_unid_neg_: TQuery;
    qry_cliente_: TQuery;
    qry_cliente_CD_EMPRESA: TStringField;
    qry_cliente_NM_EMPRESA: TStringField;
    qry_cliente_AP_EMPRESA: TStringField;
    qry_unid_neg_CD_UNID_NEG: TStringField;
    qry_unid_neg_AP_UNID_NEG: TStringField;
    qry_limpa_: TQuery;
    qry_grupo_: TQuery;
    qry_grupo_CD_GRUPO: TStringField;
    qry_grupo_NM_GRUPO: TStringField;
    qry_unid_neg_NM_UNID_NEG: TStringField;
    sp_rel_cli_cc: TStoredProc;
    qry_cliente_CGC_EMPRESA: TStringField;
    qry_grupo_CNPJ_GRUPO: TStringField;
    sp_rel_emitido_cancelado: TStoredProc;
    sp_rel_exp_emb_averb: TStoredProc;
    qry_area_: TQuery;
    qry_area_CD_AREA: TStringField;
    qry_area_NM_AREA: TStringField;
    ppDesigner: TppDesigner;
    qry_rel_exp_est_cambial_: TQuery;
    ds_rel_exp_est_cambial: TDataSource;
    ppReport: TppReport;
    ppBDE_rel_exp_est_cambial: TppBDEPipeline;
    qry_rel_fat_nf_: TQuery;
    ds_rel_fat_nf: TDataSource;
    ppBDE_rel_fat_nf: TppBDEPipeline;
    sp_rel_imp_demurrage: TStoredProc;
    qry_rel_imp_demurrage_: TQuery;
    qry_rel_imp_demurrage_pagto_: TQuery;
    qry_rel_imp_demurrage_ref_: TQuery;
    qry_rel_imp_demurrage_proc_: TQuery;
    sp_rel_di_reg_desemb: TStoredProc;
    qry_rel_di_reg_desemb_: TQuery;
    ds_rel_di_reg_desemb: TDataSource;
    ppBDE_rel_di_reg_desemb: TppBDEPipeline;
    sp_rel_kpi_exportacao: TStoredProc;
    qry_rel_kpi_exportacao_: TQuery;
    qry_ref_cliente_: TQuery;
    qry_ref_cliente_CD_REFERENCIA: TStringField;
    qry_ref_cliente_DT_REFERENCIA: TDateTimeField;
    ppBDE_rel_imp_sap: TppBDEPipeline;
    ds_rel_imp_sap: TDataSource;
    qry_rel_imp_sap_: TQuery;
    sp_rel_canal_mes: TStoredProc;
    qry_rel_canal_mes_: TQuery;
    ds_rel_canal_mes: TDataSource;
    ppBDE_rel_canal_mes: TppBDEPipeline;
    sp_rel_canal_mes_mod2: TStoredProc;
    qry_rel_canal_mes_mod2_: TQuery;
    ds_rel_canal_mes_mod2_: TDataSource;
    ppBDE_rel_canal_mes_mod2: TppBDEPipeline;
    ppTextPipeline1: TppTextPipeline;
    ds_rel_canal_graf: TDataSource;
    qry_rel_canal_graf_: TQuery;
    ppBDE_Rel_canal_graf: TppBDEPipeline;
    ds_grupo_area: TDataSource;
    qry_grupo_area_: TQuery;
    qry_rel_canal_graf_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_canal_graf_NM_CANAL: TStringField;
    qry_rel_canal_graf_QT_PROC_CANAL: TIntegerField;
    qry_rel_canal_graf_QT_PROC_TOTAL: TIntegerField;
    qry_rel_canal_graf_QT_MEDIA_DIAS_TOTAL: TFloatField;
    qry_rel_canal_graf_QT_MEDIA_DIAS_VERMELHO: TFloatField;
    qry_rel_canal_graf_QT_MEDIA_DIAS_AMARELO: TFloatField;
    qry_rel_canal_graf_QT_MEDIA_DIAS_VERDE: TFloatField;
    qry_rel_canal_graf_QT_MEDIA_DIAS_CINZA: TFloatField;
    qry_rel_canal_mes_mod2_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_canal_mes_mod2_MES: TIntegerField;
    qry_rel_canal_mes_mod2_CD_UNID_NEG: TStringField;
    qry_rel_canal_mes_mod2_CD_AREA: TStringField;
    qry_rel_canal_mes_mod2_NM_GRUPO_AREA: TStringField;
    qry_rel_canal_mes_mod2_QT_PROC_VERMELHO: TIntegerField;
    qry_rel_canal_mes_mod2_QT_PROC_AMARELO: TIntegerField;
    qry_rel_canal_mes_mod2_QT_PROC_VERDE: TIntegerField;
    qry_rel_canal_mes_mod2_QT_PROC_CINZA: TIntegerField;
    qry_rel_canal_mes_mod2_MEDIA_DIAS_VERMELHO: TIntegerField;
    qry_rel_canal_mes_mod2_MEDIA_DIAS_AMARELO: TIntegerField;
    qry_rel_canal_mes_mod2_MEDIA_DIAS_VERDE: TIntegerField;
    qry_rel_canal_mes_mod2_MEDIA_DIAS_CINZA: TIntegerField;
    qry_rel_canal_mes_mod2_QT_PROC_TOTAL_AREA: TIntegerField;
    qry_rel_canal_mes_mod2_QT_TOTAL_MEDIA_DIAS: TIntegerField;
    qry_rel_canal_mes_mod2_QT_PROC_TOTAL_VERMELHO: TIntegerField;
    qry_rel_canal_mes_mod2_QT_PROC_TOTAL_AMARELO: TIntegerField;
    qry_rel_canal_mes_mod2_QT_PROC_TOTAL_VERDE: TIntegerField;
    qry_rel_canal_mes_mod2_QT_PROC_TOTAL_CINZA: TIntegerField;
    qry_rel_canal_mes_mod2_QT_TOTAL_PROCESSO: TIntegerField;
    qry_rel_canal_mes_mod2_NM_UNID_NEG: TStringField;
    qry_rel_canal_mes_mod2_NM_AREA: TStringField;
    qry_rel_canal_mes_mod2_NM_MES: TStringField;
    qry_rel_canal_graf_NR_ORDEM: TIntegerField;
    qry_tp_lead_time_: TQuery;
    qry_rel_kpi_exportacao_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_kpi_exportacao_NM_UNID_NEG: TStringField;
    qry_rel_kpi_exportacao_NM_CLIENTE: TStringField;
    qry_rel_kpi_exportacao_NR_REF_PEDIDO: TStringField;
    qry_rel_kpi_exportacao_DT_REF_PEDIDO: TDateTimeField;
    qry_rel_kpi_exportacao_DESCRICAO: TStringField;
    qry_rel_kpi_exportacao_NM_AREA: TStringField;
    qry_rel_kpi_exportacao_NM_EMPRESA: TStringField;
    qry_rel_kpi_exportacao_DT_ENV_COMEXT: TDateTimeField;
    qry_rel_kpi_exportacao_NR_REF_ORDEM: TStringField;
    qry_rel_kpi_exportacao_DT_REF_ORDEM: TDateTimeField;
    qry_rel_kpi_exportacao_DT_LIB_EST: TDateTimeField;
    qry_rel_kpi_exportacao_NR_REF_REMESSA: TStringField;
    qry_rel_kpi_exportacao_DT_REF_REMESSA: TDateTimeField;
    qry_rel_kpi_exportacao_DT_CONSOLIDACAO: TDateTimeField;
    qry_rel_kpi_exportacao_DT_LIB_FAB: TDateTimeField;
    qry_rel_kpi_exportacao_DT_LIB_PROC: TDateTimeField;
    qry_rel_kpi_exportacao_NR_NF: TStringField;
    qry_rel_kpi_exportacao_DT_NF: TDateTimeField;
    qry_rel_kpi_exportacao_NR_PROCESSO: TStringField;
    qry_rel_kpi_exportacao_NM_VIA_TRANSPORTE: TStringField;
    qry_rel_kpi_exportacao_NR_CAMINHAO: TStringField;
    qry_rel_kpi_exportacao_NM_EMBARCACAO: TStringField;
    qry_rel_kpi_exportacao_NM_TRANSP_ROD: TStringField;
    qry_rel_kpi_exportacao_DT_PREV_EMB: TDateTimeField;
    qry_rel_kpi_exportacao_DT_DESEMB: TDateTimeField;
    qry_rel_kpi_exportacao_DT_EMB: TDateTimeField;
    qry_rel_kpi_exportacao_DT_ENV_DOC: TDateTimeField;
    qry_rel_kpi_exportacao_DT_ENT_DOC: TDateTimeField;
    qry_rel_kpi_exportacao_DT_AVERBACAO: TDateTimeField;
    qry_rel_kpi_exportacao_DT_CHEGADA_DOC: TDateTimeField;
    qry_rel_kpi_exportacao_DT_CH_MERC: TDateTimeField;
    qry_rel_kpi_exportacao_AP_MOEDA: TStringField;
    qry_rel_kpi_exportacao_VL_TOTAL: TFloatField;
    qry_rel_kpi_exportacao_CD_INCOTERM: TStringField;
    qry_rel_kpi_exportacao_NM_CONTATO: TStringField;
    qry_rel_kpi_exportacao_NR_DIAS_REC_PED: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_LIB_REC: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_SOLIC_LIB: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_OR_SOLIC: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_REM_SOLIC: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_SOLIC_REM: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_LIB_REM: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_NF_LIB: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_DES_NF: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_DES: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_AV_EMB: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_DOCS: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_REC: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_PED: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_LIB_LIB: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_NF: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_CON_NF: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_CON: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_DES_EMB: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_AV_DES: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_CH_DES: TIntegerField;
    qry_rel_kpi_exportacao_DT_REC_PEDIDO: TDateTimeField;
    qry_rel_kpi_exportacao_DT_SOLIC_OV: TDateTimeField;
    qry_rel_kpi_exportacao_DT_SOLIC_REMESSA: TDateTimeField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_LIB: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_DES_LIB: TIntegerField;
    qry_produto_: TQuery;
    qry_produto_CD_PRODUTO: TStringField;
    qry_produto_NM_PRODUTO: TStringField;
    sp_rel_custos_bsh: TStoredProc;
    qry_rel_custos_bsh_: TQuery;
    ds_rel_custos_bsh: TDataSource;
    qry_custos_bsh_itens_: TQuery;
    qry_custos_bsh_itens_CD_ITEM: TStringField;
    qry_custos_bsh_itens_NM_ITEM: TStringField;
    qry_rel_custos_bsh_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_custos_bsh_NR_PROCESSO_INDAIA: TStringField;
    qry_rel_custos_bsh_NM_IMPORTADOR: TStringField;
    qry_rel_custos_bsh_NR_PROCESSO_CLIENTE: TStringField;
    qry_rel_custos_bsh_CD_FABRICANTE: TStringField;
    qry_rel_custos_bsh_NM_FABRICANTE: TStringField;
    qry_rel_custos_bsh_CD_LOCAL_DESTINO: TStringField;
    qry_rel_custos_bsh_LOCAL_DESTINO: TStringField;
    qry_rel_custos_bsh_NM_CONTATO: TStringField;
    qry_rel_custos_bsh_CD_INCOTERM: TStringField;
    qry_rel_custos_bsh_QT_TOTAL_PRODUTO: TFloatField;
    qry_rel_custos_bsh_AP_MERCADORIA: TStringField;
    qry_rel_custos_bsh_DS_INF_GERAL_EMB: TStringField;
    qry_rel_custos_bsh_CD_EMBARCACAO: TStringField;
    qry_rel_custos_bsh_NM_EMBARCACAO: TStringField;
    qry_rel_custos_bsh_DT_ETA: TDateTimeField;
    qry_rel_custos_bsh_DT_CARREGAMENTO: TDateTimeField;
    qry_rel_custos_bsh_DT_FATURAMENTO: TDateTimeField;
    qry_rel_custos_bsh_DT_INSTRUCAO: TDateTimeField;
    qry_rel_custos_bsh_DT_DEAD_LINE: TDateTimeField;
    qry_rel_custos_bsh_DT_ETD: TDateTimeField;
    qry_rel_custos_bsh_DS_OBS: TStringField;
    qry_rel_custos_bsh_CD_MOEDA: TStringField;
    qry_rel_custos_bsh_NM_MOEDA: TStringField;
    qry_rel_custos_bsh_VL_INVOICE_MOEDA: TFloatField;
    qry_rel_custos_bsh_VL_NF: TFloatField;
    qry_rel_custos_bsh_TP_FRETE: TStringField;
    qry_rel_custos_bsh_VL_FRETE: TFloatField;
    qry_rel_custos_bsh_CD_ITEM: TStringField;
    qry_rel_custos_bsh_NM_ITEM: TStringField;
    qry_rel_custos_bsh_VL_ITEM: TFloatField;
    qry_rel_custos_bsh_CD_LINHA_IMPRESSAO_ITEM: TIntegerField;
    sp_rel_lead_time2: TStoredProc;
    ds_rel_lead_time2: TDataSource;
    qry_rel_lead_time2_: TQuery;
    qry_rel_lead_time2_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_lead_time2_NR_PROCESSO: TStringField;
    qry_rel_lead_time2_NM_CLIENTE: TStringField;
    qry_rel_lead_time2_NM_EMBARCACAO: TStringField;
    qry_rel_lead_time2_DT_CHEGADA_NAVIO: TDateTimeField;
    qry_rel_lead_time2_ARMZ_ATRACACAO: TStringField;
    qry_rel_lead_time2_NM_MARGEM: TStringField;
    qry_rel_lead_time2_DT_REGISTRO_DI: TDateTimeField;
    qry_rel_lead_time2_DT_ENT_ARM: TDateTimeField;
    qry_rel_lead_time2_TEMPO_DESEMBARACO: TIntegerField;
    qry_rel_lead_time2_DT_DESEMBARACO: TDateTimeField;
    qry_rel_lead_time2_NM_CANAL: TStringField;
    qry_rel_lead_time2_VL_COMISSAO: TFloatField;
    qry_rel_lead_time2_VL_SDA: TFloatField;
    qry_rel_lead_time2_VL_CIF: TFloatField;
    qry_rel_lead_time2_ARMZ_DESCARGA: TStringField;
    qry_rel_lead_time2_PERIODO_ARMAZENAGEM: TIntegerField;
    qry_rel_lead_time2_VL_ARMZ_TERMINAL: TFloatField;
    qry_rel_lead_time2_VL_ARMZ_NORMAL: TFloatField;
    qry_rel_lead_time2_DT_ENVIO_NF: TDateTimeField;
    qry_rel_lead_time2_NM_ESPECIE: TStringField;
    qry_rel_lead_time2_QT_VOLUMES: TStringField;
    qry_rel_lead_time2_CD_REFERENCIA: TStringField;
    qry_ref_cliente_NR_SEQUENCIA: TStringField;
    qry_rel_lead_time2_DT_PRESENCA_CARGA: TDateTimeField;
    qry_rel_lead_time2_DT_DOCTOS_TRANSPORT: TDateTimeField;
    qry_rel_lead_time2_NM_AGENTE_CARGA: TStringField;
    qry_rel_lead_time2_NM_ARMAZEM_DESCARGA: TStringField;
    qry_rel_kpi_exportacao_DT_REC_NF: TDateTimeField;
    qry_rel_kpi_exportacao_NR_DIAS_DES_REC: TIntegerField;
    ppParameterList1: TppParameterList;
    qry_rel_kpi_exportacao_NR_DIAS_LIB_DLD: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_LIB_DLC: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_LIB_DESEMB: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_LIB_NF: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_LIB_EMB: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_NF_DLD: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_BL: TIntegerField;
    qry_rel_kpi_exportacao_NR_DIAS_EMB_DOC: TIntegerField;
    qry_rel_kpi_exportacao_DT_DL_DRAFT: TDateTimeField;
    qry_rel_kpi_exportacao_DT_RET_BL: TDateTimeField;
    qry_rel_kpi_exportacao_DT_DL_CARGA: TDateTimeField;
    sp_rel_fluxo_caixa: TStoredProc;
    sp_rel_fluxo_cx: TStoredProc;
    ppTitleBand1: TppTitleBand;
    pplbl_titulo: TppLabel;
    ppImage1: TppImage;
    ppHeaderBand1: TppHeaderBand;
    ppLabel19: TppLabel;
    ppLabel18: TppLabel;
    ppLabel16: TppLabel;
    ppLabel17: TppLabel;
    ppLabel2: TppLabel;
    ppLabel3: TppLabel;
    ppLabel4: TppLabel;
    ppLabel5: TppLabel;
    ppLabel6: TppLabel;
    ppLabel7: TppLabel;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppLabel10: TppLabel;
    ppLabel11: TppLabel;
    ppLabel12: TppLabel;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppLine19: TppLine;
    ppLine21: TppLine;
    ppLine22: TppLine;
    ppLine23: TppLine;
    ppLine24: TppLine;
    ppLine25: TppLine;
    ppLine26: TppLine;
    ppLine27: TppLine;
    ppLine28: TppLine;
    ppLine29: TppLine;
    ppLine30: TppLine;
    ppLine32: TppLine;
    ppShape1: TppShape;
    ppLine31: TppLine;
    ppLine18: TppLine;
    ppLine20: TppLine;
    ppLine34: TppLine;
    ppLine35: TppLine;
    ppLine40: TppLine;
    ppLine41: TppLine;
    ppDetailBand1: TppDetailBand;
    ppDBText5: TppDBText;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBMemo1: TppDBMemo;
    ppDBMemo2: TppDBMemo;
    ppDBText1: TppDBText;
    ppLine2: TppLine;
    ppLine3: TppLine;
    ppLine4: TppLine;
    ppLine5: TppLine;
    ppLine6: TppLine;
    ppLine7: TppLine;
    ppLine8: TppLine;
    ppLine9: TppLine;
    ppLine10: TppLine;
    ppLine11: TppLine;
    ppLine12: TppLine;
    ppLine13: TppLine;
    ppLine14: TppLine;
    ppLine15: TppLine;
    ppLine16: TppLine;
    tx_siscomex: TppDBText;
    ppLine38: TppLine;
    ppDBMemo3: TppDBMemo;
    ppDBText2: TppDBText;
    ppDBMemo4: TppDBMemo;
    ppDBText3: TppDBText;
    ppDBText4: TppDBText;
    ppLine36: TppLine;
    ppLine39: TppLine;
    ppFooterBand1: TppFooterBand;
    ppVarRodapeEsq: TppVariable;
    ppVarRodapeDir: TppVariable;
    ppNumPag: TppSystemVariable;
    ppTotPag: TppSystemVariable;
    ppLine17: TppLine;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppShape2: TppShape;
    ppDBCalc1: TppDBCalc;
    ppLabel1: TppLabel;
    ppDBCalc2: TppDBCalc;
    ppDBCalc3: TppDBCalc;
    ppDBCalc4: TppDBCalc;
    ppDBCalc5: TppDBCalc;
    ppDBCalc6: TppDBCalc;
    ppDBCalc7: TppDBCalc;
    ppDBCalc8: TppDBCalc;
    ppDBCalc9: TppDBCalc;
    ppGroup2: TppGroup;
    ppGroupHeaderBand2: TppGroupHeaderBand;
    ppGroupFooterBand2: TppGroupFooterBand;
    ppLine1: TppLine;
    ppDBCalc10: TppDBCalc;
    ppDBCalc11: TppDBCalc;
    ppDBCalc12: TppDBCalc;
    ppLabel15: TppLabel;
    qry_rel_fluxo_caixa_receitas: TQuery;
    qry_rel_imp_demurrage_proc_NR_PROCESSO: TStringField;
    qry_rel_imp_demurrage_proc_CD_UNID_NEG: TStringField;
    qry_rel_imp_demurrage_proc_NM_UNID_NEG: TStringField;
    qry_rel_imp_demurrage_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_imp_demurrage_NR_PROCESSO: TStringField;
    qry_rel_imp_demurrage_NM_UNID_NEG: TStringField;
    qry_rel_imp_demurrage_NR_CNTR: TStringField;
    qry_rel_imp_demurrage_NM_TP_CNTR: TStringField;
    qry_rel_imp_demurrage_IN_DEMURRAGE: TStringField;
    qry_rel_imp_demurrage_NM_TRANSPORTADOR: TStringField;
    qry_rel_imp_demurrage_NM_ARMAZEM_ATRACACAO: TStringField;
    qry_rel_imp_demurrage_NM_ARMAZEM_DESCARGA: TStringField;
    qry_rel_imp_demurrage_NM_CLIENTE: TStringField;
    qry_rel_imp_demurrage_NM_CANAL: TStringField;
    qry_rel_imp_demurrage_NM_TRANSP_NAC: TStringField;
    qry_rel_imp_demurrage_NM_AREA: TStringField;
    qry_rel_imp_demurrage_TX_MERCADORIA: TMemoField;
    qry_rel_imp_demurrage_NM_EXPORTADOR: TStringField;
    qry_rel_imp_demurrage_DT_DOCTOS_OK: TDateTimeField;
    qry_rel_imp_demurrage_DT_ENT: TDateTimeField;
    qry_rel_imp_demurrage_DT_ENT_TERMINAL: TDateTimeField;
    qry_rel_imp_demurrage_DT_PRES_CARGA: TDateTimeField;
    qry_rel_imp_demurrage_DT_LIB_BL: TDateTimeField;
    qry_rel_imp_demurrage_DT_REG_DI: TDateTimeField;
    qry_rel_imp_demurrage_DT_AVERBACAO: TDateTimeField;
    qry_rel_imp_demurrage_DT_DESEMB: TDateTimeField;
    qry_rel_imp_demurrage_DT_CI: TDateTimeField;
    qry_rel_imp_demurrage_DT_INSP_MA: TDateTimeField;
    qry_rel_imp_demurrage_DT_NF_TRANSP: TDateTimeField;
    qry_rel_imp_demurrage_DT_ENTR_FABRICA: TDateTimeField;
    qry_rel_imp_demurrage_DT_DEVOLUCAO_CNTR: TDateTimeField;
    qry_rel_imp_demurrage_pagto_NR_IDENTIFICADOR: TIntegerField;
    qry_rel_imp_demurrage_pagto_NR_PROCESSO: TStringField;
    qry_rel_imp_demurrage_pagto_DT_PAGAMENTO: TDateTimeField;
    qry_rel_imp_demurrage_pagto_VL_PAGAMENTO: TFloatField;
    qry_rel_imp_demurrage_ref_NR_PROCESSO: TStringField;
    qry_rel_imp_demurrage_ref_CD_REFERENCIA: TStringField;
    qry_rel_imp_demurrage_ref_merc: TQuery;
    qry_rel_imp_demurrage_ref_mercAP_MERCADORIA: TStringField;
    qry_rel_imp_demurrage_ref_mercNM_MERCADORIA: TStringField;
    qry_rel_imp_sap_NR_PROCESSO: TStringField;
    qry_rel_imp_sap_NR_DI: TStringField;
    qry_rel_imp_sap_NR_PEDIDO: TStringField;
    qry_rel_imp_sap_NR_ITEM: TStringField;
    qry_rel_imp_sap_VL_II_ITEM: TFloatField;
    qry_rel_imp_sap_VL_IPI_ITEM: TFloatField;
    qry_rel_imp_sap_VL_ICMS_ITEM: TFloatField;
    qry_rel_imp_sap_VL_PIS_ITEM: TFloatField;
    qry_rel_imp_sap_VL_COFINS_ITEM: TFloatField;
    qry_rel_imp_sap_VL_TX_SCX: TFloatField;
    qry_rel_imp_sap_PL_MERCADORIA: TFloatField;
    qry_rel_imp_sap_CD_CLIENTE: TStringField;
    qry_rel_imp_sap_NM_EMPRESA: TStringField;
    qry_rel_imp_sap_DT_REG_DI: TStringField;
    qry_rel_imp_sap_NR_DECL_IMP_PROT: TStringField;
    qry_rel_imp_sap_END_CIDADE: TStringField;
    qry_rel_imp_sap_NM_GRUPO: TStringField;
    qry_rel_imp_sap_UTILIZ_MAT: TIntegerField;
    qry_rel_imp_sap_CNPJ_EMPRESA: TStringField;
    qry_rel_imp_sap_VL_ANTIDUMPING: TFloatField;
    qry_rel_imp_sap_DS_NFS: TStringField;
    qry_rel_imp_sap_VL_MULTA_LI: TFloatField;
    qry_rel_imp_sap_COD_MERCADORIA: TStringField;
    procedure ppVarRodapeDirCalc(Sender: TObject; var Value: Variant);
    procedure ppVarRodapeEsqCalc(Sender: TObject; var Value: Variant);
    procedure ppHeaderBand1BeforePrint(Sender: TObject);
//    procedure datm_sel_unid_cliCreate(Sender: TObject);
//    procedure ppDBTeeChart1Print(Sender: TObject);
//    procedure ppTeeChart1Print(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  datm_sel_unid_cli: Tdatm_sel_unid_cli;

implementation

uses GSMLIB, PGGP001, PGFT019;

{$R *.DFM}

procedure Tdatm_sel_unid_cli.ppVarRodapeDirCalc(Sender: TObject;
  var Value: Variant);
begin
  ppVarRodapeDir.AsString := 'Folha ' + ppNumPag.Text + ' / ' + ppTotPag.Text;
end;

procedure Tdatm_sel_unid_cli.ppVarRodapeEsqCalc(Sender: TObject;
  var Value: Variant);
begin
  if frm_sel_unid_cli.tp_rel = 13 then
    ppVarRodapeEsq.AsString := 'RBEXP001' + Space(5) + 'Emitido em ' + FormatDateTime( 'dd/mm/yyyy', dt_server ) + '  às  ' + FormatDateTime( 'hh:mm:ss', hr_server );
  if frm_sel_unid_cli.tp_rel = 25 then
    ppVarRodapeEsq.AsString := 'RBIMP001' + Space(5) + 'Emitido em ' + FormatDateTime( 'dd/mm/yyyy', dt_server ) + '  às  ' + FormatDateTime( 'hh:mm:ss', hr_server );
  if frm_sel_unid_cli.tp_rel = 26 then
    ppVarRodapeEsq.AsString := 'RBIMP002' + Space(5) + 'Emitido em ' + FormatDateTime( 'dd/mm/yyyy', dt_server ) + '  às  ' + FormatDateTime( 'hh:mm:ss', hr_server );
  if frm_sel_unid_cli.tp_rel = 29 then
    ppVarRodapeEsq.AsString := 'RBEST003' + Space(5) + 'Emitido em ' + FormatDateTime( 'dd/mm/yyyy', dt_server ) + '  às  ' + FormatDateTime( 'hh:mm:ss', hr_server );
end;

//procedure Tdatm_sel_unid_cli.ppTeeChart1Print(Sender: TObject);
//begin
//  with Series1 do
//  begin
 //   Clear;
 //   AddPie(  62, 'Teste', clGray );
 //   AddPie(  20, 'Fatia Azul',    clBlue   );
 //   AddPie(  30, 'Fatia Verde',   clGreen  );
 //   AddPie( 150, 'Fatia Vermelha',clRed    );
 //   AddPie(  45, 'Fatia Amarela', clYellow );
//  end;
//end;

procedure Tdatm_sel_unid_cli.ppHeaderBand1BeforePrint(Sender: TObject);
begin
  ppLabel2.Caption := 'Unidade: ' + frm_sel_unid_cli.edt_nm_unid_neg.Text;
  pplbl_titulo.Caption := 'Relatório de Canais Mod2 Período ' + DateToStr(frm_sel_unid_cli.msk_dt_inicio.Date) + ' a ' +  DateToStr(frm_sel_unid_cli.msk_dt_fim.Date) ;
  if Trim( frm_sel_unid_cli.msk_cd_cliente.Text ) <> '' then
    ppLabel3.Caption := 'Cliente: ' + frm_sel_unid_cli.edt_nm_cliente.Text else
    ppLabel3.Caption := 'Grupo: ' + frm_sel_unid_cli.edt_nm_grupo.Text;
  if Trim( frm_sel_unid_cli.msk_cd_area.Text ) <> '' then
    ppLabel4.Caption    := 'Área: ' + frm_sel_unid_cli.edt_nm_area.Text else
    if Trim( frm_sel_unid_cli.msk_cd_grupo_area.Text ) <> '' then
      ppLabel4.Caption    := 'Grupo Área: ' + frm_sel_unid_cli.msk_cd_grupo_area.Text else
      ppLabel4.Caption    := 'Grupo Área: Todos';
end;



end.
