unit PGPO013;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Db, DBTables, Variants;

type
  Tdatm_po_leitura = class(TDataModule)
    qry_po_: TQuery;
    qry_po_NR_PROCESSO: TStringField;
    qry_po_NR_IDENT_USUARIO: TStringField;
    qry_po_CD_IMPORTADOR: TStringField;
    qry_po_CD_CONSIGNATARIO: TStringField;
    qry_po_CD_FABRICANTE: TStringField;
    qry_po_CD_EXPORTADOR: TStringField;
    qry_po_CD_VIA_TRANSP: TStringField;
    qry_po_CD_REPRESENTANTE: TStringField;
    qry_po_CD_MOD_PAGAMENTO: TStringField;
    qry_po_CD_PAIS_ORIGEM: TStringField;
    qry_po_CD_REGIME_TRIB: TStringField;
    qry_po_CD_PAIS_PROCEDENCIA: TStringField;
    qry_po_CD_MOEDA_NEG: TStringField;
    qry_po_CD_PAIS_AQUISICAO: TStringField;
    qry_po_CD_TP_DECLARACAO: TStringField;
    qry_po_CD_URF_DESPACHO: TStringField;
    qry_po_CD_INCOTERM: TStringField;
    qry_po_CD_TRANSP_INTERN: TStringField;
    qry_po_CD_BANDEIRA_VEIC: TStringField;
    qry_po_CD_SETOR_ARMAZENAGEM: TStringField;
    qry_po_CD_LOCAL_EMBARQUE: TStringField;
    qry_po_CD_AGENTE_CARGA: TStringField;
    qry_po_CD_URF_ENTRADA: TStringField;
    qry_po_CD_RECINTO_ALFAND: TStringField;
    qry_po_CD_MOEDA_FRETE: TStringField;
    qry_po_CD_MOEDA_SEGURO: TStringField;
    qry_po_CD_MOEDA_CARGA: TStringField;
    qry_po_CD_LOCAL_INCOTERM: TStringField;
    qry_po_CD_TX_JUROS: TStringField;
    qry_po_CD_INSTIT_FINANC: TStringField;
    qry_po_CD_MOTIVO_CAMBIO_SEM_COBERT: TStringField;
    qry_po_CD_BARRA: TStringField;
    qry_po_CD_MET_VALORACAO_ADUAN: TStringField;
    qry_po_DT_ABERTURA: TDateTimeField;
    qry_po_DT_EMISSAO_DOC_CARGA: TDateTimeField;
    qry_po_DT_CHEGADA_CARGA: TDateTimeField;
    qry_po_DT_FATURA: TDateTimeField;
    qry_po_IN_APLICACAO_MERC: TStringField;
    qry_po_IN_COMISSAO: TBooleanField;
    qry_po_IN_DESCONTO: TBooleanField;
    qry_po_IN_TP_COMISSAO: TStringField;
    qry_po_IN_TP_DESCONTO: TStringField;
    qry_po_IN_INDICADOR_CONSIG_IMPORT: TBooleanField;
    qry_po_IN_INDICADOR_PROC: TStringField;
    qry_po_IN_VINC_IMPO_EXPO: TStringField;
    qry_po_IN_COND_MERCADORIA: TStringField;
    qry_po_IN_FABR_EXPOR_IMP: TStringField;
    qry_po_IN_INDIC_MULTMODAL: TBooleanField;
    qry_po_IN_FUNDAP: TBooleanField;
    qry_po_IN_UTILIZ_CARGA: TStringField;
    qry_po_IN_INDIC_TX_JUROS: TBooleanField;
    qry_po_IN_SEGURO: TStringField;
    qry_po_NR_PLACA_VEICULO: TStringField;
    qry_po_NR_MANIFESTO: TStringField;
    qry_po_NR_DOC_MASTER: TStringField;
    qry_po_NR_DOC_HOUSE: TStringField;
    qry_po_NR_BACEN: TStringField;
    qry_po_NR_FATURA: TStringField;
    qry_po_NM_IDENT_CRT: TStringField;
    qry_po_NM_VEICULO: TStringField;
    qry_po_PC_COMISSAO: TFloatField;
    qry_po_PC_DESCONTO: TFloatField;
    qry_po_PC_SEGURO: TFloatField;
    qry_po_PC_COMISSAO_AGENTE: TFloatField;
    qry_po_PL_PO: TFloatField;
    qry_po_PB_PO: TFloatField;
    qry_po_QT_TOTAL_PESO: TFloatField;
    qry_po_QT_PORC_ICMS: TFloatField;
    qry_po_QT_TOTAL_ITENS: TStringField;
    qry_po_QT_PORC_RED_ICMS: TFloatField;
    qry_po_QT_PERIODICIDADE: TStringField;
    qry_po_TP_COBERT_CAMBIO: TStringField;
    qry_po_TP_CAMBIO: TBooleanField;
    qry_po_TP_DOC_CARGA: TStringField;
    qry_po_TP_FRETE: TStringField;
    qry_po_TP_SEGURO: TStringField;
    qry_po_TP_MOD_DESPACHO: TStringField;
    qry_po_TP_MANIFESTO: TStringField;
    qry_po_TX_JUROS: TFloatField;
    qry_po_TX_OBSERVACAO: TMemoField;
    qry_po_VL_COMISSAO: TFloatField;
    qry_po_VL_CARGA: TFloatField;
    qry_po_VL_CAMBIO: TFloatField;
    qry_po_VL_DESCONTO: TFloatField;
    qry_po_VL_FRETE_PREPAID: TFloatField;
    qry_po_VL_FRETE_COLLECT: TFloatField;
    qry_po_VL_FRETE_TERRIT_NAC: TFloatField;
    qry_po_VL_SEGURO: TFloatField;
    qry_po_VL_TOTAL: TFloatField;
    qry_po_VL_TOTAL_PARCELA: TFloatField;
    qry_po_VL_PAGTO_ANTECIPADO: TFloatField;
    qry_po_VL_PAGTO_VISTA: TFloatField;
    qry_po_VL_PERIODIC_MENSAL: TFloatField;
    qry_po_VL_DESPESAS: TFloatField;
    qry_po_VL_DESCONTOS: TFloatField;
    qry_po_IN_SELECIONADO: TStringField;
    qry_po_IN_MONTADO: TStringField;
    ds_po: TDataSource;
    ds_po_itens: TDataSource;
    qry_po_itens_: TQuery;
    qry_po_itens_NR_PROCESSO: TStringField;
    qry_po_itens_NR_ITEM: TStringField;
    qry_po_itens_CD_EXPORTADOR: TStringField;
    qry_po_itens_CD_NALADI_SH: TStringField;
    qry_po_itens_CD_PAIS_AQUISICAO: TStringField;
    qry_po_itens_CD_MERCADORIA: TStringField;
    qry_po_itens_CD_FABRICANTE: TStringField;
    qry_po_itens_CD_PAIS_ORIGEM: TStringField;
    qry_po_itens_CD_NCM_SH: TStringField;
    qry_po_itens_CD_NALADI_NCCA: TStringField;
    qry_po_itens_CD_MET_VALOR_ADUANEIRA: TStringField;
    qry_po_itens_CD_DISP_LEGAL_EXONERA: TStringField;
    qry_po_itens_CD_MOEDA_NEGOCIADA: TStringField;
    qry_po_itens_CD_INCOTERM: TStringField;
    qry_po_itens_CD_ACORDO_ALADI: TStringField;
    qry_po_itens_CD_REG_TRIB_II: TStringField;
    qry_po_itens_CD_FUND_LEGAL_II: TStringField;
    qry_po_itens_CD_UNID_MEDIDA: TStringField;
    qry_po_itens_CD_UNID_MED_II: TStringField;
    qry_po_itens_CD_UNID_MED_IPI: TStringField;
    qry_po_itens_CD_UNID_MED_AD: TStringField;
    qry_po_itens_CD_AGENTE_CAMBIO: TStringField;
    qry_po_itens_CD_MOD_PAGTO: TStringField;
    qry_po_itens_CD_TX_JUROS: TStringField;
    qry_po_itens_CD_INSTITUICAO_FINANC: TStringField;
    qry_po_itens_CD_MOT_SEM_COBERT_CAMBIAL: TStringField;
    qry_po_itens_CD_EX_II: TStringField;
    qry_po_itens_CD_EX_IPI: TStringField;
    qry_po_itens_CD_VIA_TRANSP: TStringField;
    qry_po_itens_CD_PAIS_PROCEDENCIA: TStringField;
    qry_po_itens_CD_URF_ENTRADA: TStringField;
    qry_po_itens_IN_NECESSITA_LI: TBooleanField;
    qry_po_itens_IN_INDICADOR_COND_MERC: TBooleanField;
    qry_po_itens_IN_COND_MERC: TStringField;
    qry_po_itens_IN_APLIC_MERC: TStringField;
    qry_po_itens_NM_ORGAO_EMISSOR_AL_EX_NALADI: TStringField;
    qry_po_itens_NM_AL_EX_NALADI: TStringField;
    qry_po_itens_NM_ORGAO_EMISSOR_AL_NCM: TStringField;
    qry_po_itens_NM_AL_EX_NALADI_NCCA: TStringField;
    qry_po_itens_NM_ORG_EMISSOR_EX_NALADI_NCCA: TStringField;
    qry_po_itens_NM_AL_II: TStringField;
    qry_po_itens_NM_ORGAO_EMISSOR_II: TStringField;
    qry_po_itens_NM_ORGAO_EMISSOR_IPI: TStringField;
    qry_po_itens_NM_AL_IPI: TStringField;
    qry_po_itens_NM_AL_AD: TStringField;
    qry_po_itens_NM_ORGAO_EMISSOR_AD: TStringField;
    qry_po_itens_NM_IDENTIFICACAO: TStringField;
    qry_po_itens_NR_ANO_EMISSAO_AL_EX_NALADI: TStringField;
    qry_po_itens_NR_AL_EX_NALADI: TStringField;
    qry_po_itens_NR_EX_NCM: TStringField;
    qry_po_itens_NR_AL_EX_NCM: TStringField;
    qry_po_itens_NR_ANO_EMISSAO_AL: TStringField;
    qry_po_itens_NR_ATO_LEGAL: TStringField;
    qry_po_itens_NR_EX_NALADI: TStringField;
    qry_po_itens_NR_EX_NALADI_NCCA: TStringField;
    qry_po_itens_NR_ANO_EMISSAO_EX_NALADI_NCCA: TStringField;
    qry_po_itens_NR_AL_EX_NALADI_NCCA: TStringField;
    qry_po_itens_NR_ANO_II: TStringField;
    qry_po_itens_NR_AL_II: TStringField;
    qry_po_itens_NR_ALIQ_NORMAL_II: TStringField;
    qry_po_itens_NR_ALIQ_ACORDO_II: TStringField;
    qry_po_itens_NR_ALIQ_REDUZIDA_II: TStringField;
    qry_po_itens_NR_ALIQ_PERC_RED_II: TStringField;
    qry_po_itens_NR_ANO_IPI: TStringField;
    qry_po_itens_NR_AL_IPI: TStringField;
    qry_po_itens_NR_NOTA_COMPL_IPI: TStringField;
    qry_po_itens_NR_ALIQ_NORMAL_IPI: TStringField;
    qry_po_itens_NR_ALIQ_REDUZIDA_IPI: TStringField;
    qry_po_itens_NR_ALIQ_PERC_RED_IPI: TStringField;
    qry_po_itens_NR_PROC_LI: TStringField;
    qry_po_itens_NR_EX_AD: TStringField;
    qry_po_itens_NR_ANO_AD: TStringField;
    qry_po_itens_NR_AL_AD: TStringField;
    qry_po_itens_NR_ALIQ_AD: TStringField;
    qry_po_itens_NR_BASE_CALC_AD: TFloatField;
    qry_po_itens_NR_PARCELAS: TStringField;
    qry_po_itens_NR_PERIODICIDADE: TStringField;
    qry_po_itens_NR_ROF_BACEN: TStringField;
    qry_po_itens_NR_FATURA: TStringField;
    qry_po_itens_PC_DESCONTO: TFloatField;
    qry_po_itens_PC_ICMS: TFloatField;
    qry_po_itens_PC_ICMS_REDUCAO: TFloatField;
    qry_po_itens_PC_COMISSAO: TFloatField;
    qry_po_itens_PL_ITEM: TFloatField;
    qry_po_itens_QT_INICIAL: TFloatField;
    qry_po_itens_QT_BAIXADA_DI: TFloatField;
    qry_po_itens_QT_BAIXADA_LI: TFloatField;
    qry_po_itens_QT_ESPEC_II: TFloatField;
    qry_po_itens_QT_ESPEC_IPI: TFloatField;
    qry_po_itens_QT_AD: TFloatField;
    qry_po_itens_QT_MED_ESTATISTICA: TFloatField;
    qry_po_itens_TP_CALCULO: TStringField;
    qry_po_itens_TP_COMISSAO: TStringField;
    qry_po_itens_TP_ACORDO_TARIFARIO: TStringField;
    qry_po_itens_TP_TRIBUTACAO_IPI: TStringField;
    qry_po_itens_TP_CAMBIO: TStringField;
    qry_po_itens_TP_IND_TX_JUROS: TBooleanField;
    qry_po_itens_TP_IND_PERIODICIDADE: TStringField;
    qry_po_itens_TP_RECIPIENTE: TStringField;
    qry_po_itens_TP_IND_MULTIMODAL: TStringField;
    qry_po_itens_TX_MERCADORIA: TMemoField;
    qry_po_itens_TX_JUROS_CAMBIO: TFloatField;
    qry_po_itens_VL_DESPESA_MOEDA: TFloatField;
    qry_po_itens_VL_DESCONTO_MOEDA: TFloatField;
    qry_po_itens_VL_UNITARIO: TFloatField;
    qry_po_itens_VL_TOTAL: TFloatField;
    qry_po_itens_VL_DESCONTO: TFloatField;
    qry_po_itens_VL_COMISSAO: TFloatField;
    qry_po_itens_VL_ESPEC_II: TFloatField;
    qry_po_itens_VL_ESPEC_IPI: TFloatField;
    qry_po_itens_VL_ESPEC_AD: TFloatField;
    qry_po_itens_VL_TOTAL_PARCELAS: TFloatField;
    qry_po_itens_VL_COBERT_ACIMA_360: TFloatField;
    qry_po_itens_VL_PAGTO_ANTECIPADO: TFloatField;
    qry_po_itens_VL_PAGTO_AVISTA: TFloatField;
    qry_po_itens_VL_FRETE_NAC_MOEDA: TFloatField;
    qry_po_itens_VL_SEGURO_MOEDA: TFloatField;
    qry_po_itens_VL_ACRESC_MOEDA: TFloatField;
    qry_po_itens_VL_DEDUC_MOEDA: TFloatField;
    qry_po_itens_VL_FRETE_PREPAID_MOEDA: TFloatField;
    qry_po_itens_VL_FRETE_COLLECT: TFloatField;
    qry_po_itens_IN_SELECIONADO: TStringField;
    qry_po_itens_QT_BAIXAR: TFloatField;
    qry_po_itens_QT_DISPONIVEL: TFloatField;
    qry_po_itens_IN_MONTADO: TStringField;
    qry_po_IN_IND_COND_MERC: TBooleanField;
    qry_po_IN_IND_CAMBIO_ITENS: TBooleanField;
    qry_po_NR_PARCELAS: TStringField;
    qry_po_IN_PERIODICIDADE: TStringField;
    qry_po_itens_IN_FABR_EXP_PROD: TStringField;
    qry_po_itens_NR_ANO_EX_NCM: TStringField;
    qry_po_itens_NR_NUM_EX_NCM: TStringField;
    qry_po_itens_IN_IND_COND_MERC: TBooleanField;
    qry_po_itens_NM_LOCAL_INCOTERM: TStringField;
    qry_po_itens_NM_TIPO_AL_AD: TStringField;
    qry_po_itens_IN_IND_PERIODICIDADE: TStringField;
    qry_po_itens_IN_REG_TRIB_IPI: TStringField;
    qry_verif_po_: TQuery;
    qry_verif_po_itens_: TQuery;
    qry_verif_po_TOTAL: TIntegerField;
    ds_verif_po: TDataSource;
    ds_verif_po_itens: TDataSource;
    qry_cliente_: TQuery;
    qry_cliente_CD_EMPRESA: TStringField;
    qry_cliente_NM_EMPRESA: TStringField;
    qry_emp_est_: TQuery;
    qry_emp_est_CD_EMPRESA: TStringField;
    qry_emp_est_NM_EMPRESA: TStringField;
    qry_moeda_broker_: TQuery;
    qry_pais_: TQuery;
    qry_moeda_broker_CD_MOEDA: TStringField;
    qry_moeda_broker_NM_MOEDA: TStringField;
    qry_pais_CODIGO: TStringField;
    qry_pais_DESCRICAO: TStringField;
    qry_apaga_itens_: TQuery;
    StringField1: TStringField;
    StringField2: TStringField;
    StringField3: TStringField;
    StringField4: TStringField;
    StringField5: TStringField;
    StringField6: TStringField;
    StringField7: TStringField;
    StringField8: TStringField;
    StringField9: TStringField;
    StringField10: TStringField;
    StringField11: TStringField;
    StringField12: TStringField;
    StringField13: TStringField;
    StringField14: TStringField;
    StringField15: TStringField;
    StringField16: TStringField;
    StringField17: TStringField;
    StringField18: TStringField;
    StringField19: TStringField;
    StringField20: TStringField;
    StringField21: TStringField;
    StringField22: TStringField;
    StringField23: TStringField;
    StringField24: TStringField;
    StringField25: TStringField;
    StringField26: TStringField;
    StringField27: TStringField;
    StringField28: TStringField;
    StringField29: TStringField;
    StringField30: TStringField;
    StringField31: TStringField;
    BooleanField1: TBooleanField;
    BooleanField2: TBooleanField;
    StringField32: TStringField;
    StringField33: TStringField;
    StringField34: TStringField;
    StringField35: TStringField;
    StringField36: TStringField;
    StringField37: TStringField;
    StringField38: TStringField;
    StringField39: TStringField;
    StringField40: TStringField;
    StringField41: TStringField;
    StringField42: TStringField;
    StringField43: TStringField;
    StringField44: TStringField;
    StringField45: TStringField;
    StringField46: TStringField;
    StringField47: TStringField;
    StringField48: TStringField;
    StringField49: TStringField;
    StringField50: TStringField;
    StringField51: TStringField;
    StringField52: TStringField;
    StringField53: TStringField;
    StringField54: TStringField;
    StringField55: TStringField;
    StringField56: TStringField;
    StringField57: TStringField;
    StringField58: TStringField;
    StringField59: TStringField;
    StringField60: TStringField;
    StringField61: TStringField;
    StringField62: TStringField;
    StringField63: TStringField;
    StringField64: TStringField;
    StringField65: TStringField;
    StringField66: TStringField;
    StringField67: TStringField;
    StringField68: TStringField;
    StringField69: TStringField;
    StringField70: TStringField;
    StringField71: TStringField;
    StringField72: TStringField;
    FloatField1: TFloatField;
    StringField73: TStringField;
    StringField74: TStringField;
    StringField75: TStringField;
    StringField76: TStringField;
    FloatField2: TFloatField;
    FloatField3: TFloatField;
    FloatField4: TFloatField;
    FloatField5: TFloatField;
    FloatField6: TFloatField;
    FloatField7: TFloatField;
    FloatField8: TFloatField;
    FloatField9: TFloatField;
    FloatField10: TFloatField;
    FloatField11: TFloatField;
    FloatField12: TFloatField;
    FloatField13: TFloatField;
    StringField77: TStringField;
    StringField78: TStringField;
    StringField79: TStringField;
    StringField80: TStringField;
    StringField81: TStringField;
    BooleanField3: TBooleanField;
    StringField82: TStringField;
    StringField83: TStringField;
    StringField84: TStringField;
    MemoField1: TMemoField;
    FloatField14: TFloatField;
    FloatField15: TFloatField;
    FloatField16: TFloatField;
    FloatField17: TFloatField;
    FloatField18: TFloatField;
    FloatField19: TFloatField;
    FloatField20: TFloatField;
    FloatField21: TFloatField;
    FloatField22: TFloatField;
    FloatField23: TFloatField;
    FloatField24: TFloatField;
    FloatField25: TFloatField;
    FloatField26: TFloatField;
    FloatField27: TFloatField;
    FloatField28: TFloatField;
    FloatField29: TFloatField;
    FloatField30: TFloatField;
    FloatField31: TFloatField;
    FloatField32: TFloatField;
    FloatField33: TFloatField;
    StringField85: TStringField;
    FloatField34: TFloatField;
    FloatField35: TFloatField;
    StringField86: TStringField;
    StringField87: TStringField;
    StringField88: TStringField;
    StringField89: TStringField;
    BooleanField4: TBooleanField;
    StringField90: TStringField;
    StringField91: TStringField;
    StringField92: TStringField;
    StringField93: TStringField;
    qry_mercadoria_: TQuery;
    qry_mercadoria_CD_MERCADORIA: TStringField;
    qry_mercadoria_NM_MERCADORIA: TMemoField;
    qry_ult_emp_est_: TQuery;
    qry_ult_emp_est_ULTIMO: TStringField;
    qry_unid_medida_broker_: TQuery;
    qry_unid_medida_broker_CD_UNID_MEDIDA: TStringField;
    qry_unid_medida_broker_NM_UNID_MEDIDA: TStringField;
    qry_unid_medida_broker_NM_SIGLA: TStringField;
    qry_mercadoria_AP_MERCADORIA: TStringField;
    qry_po_QT_TOTAL_DISPONIVEL: TFloatField;
    qry_verif_po_itens_TOTAL: TIntegerField;
    qry_mercadoria_CD_UN_MED_COMERC: TStringField;
    qry_mercadoria_PL_MERCADORIA: TFloatField;
    qry_mercadoria_VL_UNITARIO: TFloatField;
    qry_mercadoria_CD_TIPO_CALCULO: TStringField;
    qry_mercadoria_CD_FABR_EXPO: TStringField;
    qry_mercadoria_CD_EXPORTADOR: TStringField;
    qry_mercadoria_CD_FABRICANTE: TStringField;
    qry_mercadoria_CD_PAIS_ORIGEM: TStringField;
    qry_mercadoria_CD_PAIS_AQUISICAO: TStringField;
    qry_mercadoria_CD_NCM_SH: TStringField;
    qry_mercadoria_CD_NALADI_SH: TStringField;
    qry_mercadoria_CD_NALADI_NCCA: TStringField;
    qry_mercadoria_CD_IMPORTADOR: TStringField;
    qry_de_para_: TQuery;
    qry_de_para_CD_DDBROKER: TStringField;
    qry_po_CD_LOCAL_DESEMBARQUE: TStringField;
    qry_po_itens_NR_ATO_DRAWBACK: TStringField;
    qry_po_itens_CD_MODALIDADE: TStringField;
    qry_mercadoria_CD_GRUPO: TStringField;
    qry_po_CD_USUARIO_INT: TStringField;
    qry_po_int_: TQuery;
    StringField94: TStringField;
    StringField95: TStringField;
    StringField96: TStringField;
    StringField97: TStringField;
    StringField98: TStringField;
    StringField99: TStringField;
    StringField100: TStringField;
    StringField101: TStringField;
    StringField102: TStringField;
    StringField103: TStringField;
    StringField104: TStringField;
    StringField105: TStringField;
    StringField106: TStringField;
    StringField107: TStringField;
    StringField108: TStringField;
    StringField109: TStringField;
    StringField110: TStringField;
    StringField111: TStringField;
    StringField112: TStringField;
    StringField113: TStringField;
    StringField114: TStringField;
    StringField115: TStringField;
    StringField116: TStringField;
    StringField117: TStringField;
    StringField118: TStringField;
    StringField119: TStringField;
    StringField120: TStringField;
    StringField121: TStringField;
    StringField122: TStringField;
    StringField123: TStringField;
    StringField124: TStringField;
    StringField125: TStringField;
    StringField126: TStringField;
    DateTimeField1: TDateTimeField;
    DateTimeField2: TDateTimeField;
    DateTimeField3: TDateTimeField;
    DateTimeField4: TDateTimeField;
    StringField127: TStringField;
    BooleanField5: TBooleanField;
    BooleanField6: TBooleanField;
    StringField128: TStringField;
    StringField129: TStringField;
    BooleanField7: TBooleanField;
    StringField130: TStringField;
    StringField131: TStringField;
    StringField132: TStringField;
    StringField133: TStringField;
    BooleanField8: TBooleanField;
    BooleanField9: TBooleanField;
    StringField134: TStringField;
    BooleanField10: TBooleanField;
    StringField135: TStringField;
    StringField136: TStringField;
    StringField137: TStringField;
    StringField138: TStringField;
    StringField139: TStringField;
    StringField140: TStringField;
    StringField141: TStringField;
    StringField142: TStringField;
    StringField143: TStringField;
    FloatField36: TFloatField;
    FloatField37: TFloatField;
    FloatField38: TFloatField;
    FloatField39: TFloatField;
    FloatField40: TFloatField;
    FloatField41: TFloatField;
    FloatField42: TFloatField;
    FloatField43: TFloatField;
    StringField144: TStringField;
    FloatField44: TFloatField;
    StringField145: TStringField;
    StringField146: TStringField;
    BooleanField11: TBooleanField;
    StringField147: TStringField;
    StringField148: TStringField;
    StringField149: TStringField;
    StringField150: TStringField;
    StringField151: TStringField;
    FloatField45: TFloatField;
    MemoField2: TMemoField;
    FloatField46: TFloatField;
    FloatField47: TFloatField;
    FloatField48: TFloatField;
    FloatField49: TFloatField;
    FloatField50: TFloatField;
    FloatField51: TFloatField;
    FloatField52: TFloatField;
    FloatField53: TFloatField;
    FloatField54: TFloatField;
    FloatField55: TFloatField;
    FloatField56: TFloatField;
    FloatField57: TFloatField;
    FloatField58: TFloatField;
    FloatField59: TFloatField;
    FloatField60: TFloatField;
    StringField152: TStringField;
    StringField153: TStringField;
    BooleanField12: TBooleanField;
    BooleanField13: TBooleanField;
    StringField154: TStringField;
    StringField155: TStringField;
    FloatField61: TFloatField;
    StringField156: TStringField;
    StringField157: TStringField;
    sp_aviso_drawback: TStoredProc;
    qry_atz_po_: TQuery;
    StringField158: TStringField;
    StringField159: TStringField;
    StringField160: TStringField;
    StringField161: TStringField;
    StringField162: TStringField;
    StringField163: TStringField;
    StringField164: TStringField;
    StringField165: TStringField;
    StringField166: TStringField;
    StringField167: TStringField;
    StringField168: TStringField;
    StringField169: TStringField;
    StringField170: TStringField;
    StringField171: TStringField;
    StringField172: TStringField;
    StringField173: TStringField;
    StringField174: TStringField;
    StringField175: TStringField;
    StringField176: TStringField;
    StringField177: TStringField;
    StringField178: TStringField;
    StringField179: TStringField;
    StringField180: TStringField;
    StringField181: TStringField;
    StringField182: TStringField;
    StringField183: TStringField;
    StringField184: TStringField;
    StringField185: TStringField;
    StringField186: TStringField;
    StringField187: TStringField;
    StringField188: TStringField;
    StringField189: TStringField;
    StringField190: TStringField;
    DateTimeField5: TDateTimeField;
    DateTimeField6: TDateTimeField;
    DateTimeField7: TDateTimeField;
    DateTimeField8: TDateTimeField;
    StringField191: TStringField;
    BooleanField14: TBooleanField;
    BooleanField15: TBooleanField;
    StringField192: TStringField;
    StringField193: TStringField;
    BooleanField16: TBooleanField;
    StringField194: TStringField;
    StringField195: TStringField;
    StringField196: TStringField;
    StringField197: TStringField;
    BooleanField17: TBooleanField;
    BooleanField18: TBooleanField;
    StringField198: TStringField;
    BooleanField19: TBooleanField;
    StringField199: TStringField;
    StringField200: TStringField;
    StringField201: TStringField;
    StringField202: TStringField;
    StringField203: TStringField;
    StringField204: TStringField;
    StringField205: TStringField;
    StringField206: TStringField;
    StringField207: TStringField;
    FloatField62: TFloatField;
    FloatField63: TFloatField;
    FloatField64: TFloatField;
    FloatField65: TFloatField;
    FloatField66: TFloatField;
    FloatField67: TFloatField;
    FloatField68: TFloatField;
    FloatField69: TFloatField;
    StringField208: TStringField;
    FloatField70: TFloatField;
    StringField209: TStringField;
    StringField210: TStringField;
    BooleanField20: TBooleanField;
    StringField211: TStringField;
    StringField212: TStringField;
    StringField213: TStringField;
    StringField214: TStringField;
    StringField215: TStringField;
    FloatField71: TFloatField;
    MemoField3: TMemoField;
    FloatField72: TFloatField;
    FloatField73: TFloatField;
    FloatField74: TFloatField;
    FloatField75: TFloatField;
    FloatField76: TFloatField;
    FloatField77: TFloatField;
    FloatField78: TFloatField;
    FloatField79: TFloatField;
    FloatField80: TFloatField;
    FloatField81: TFloatField;
    FloatField82: TFloatField;
    FloatField83: TFloatField;
    FloatField84: TFloatField;
    FloatField85: TFloatField;
    FloatField86: TFloatField;
    StringField216: TStringField;
    StringField217: TStringField;
    BooleanField21: TBooleanField;
    BooleanField22: TBooleanField;
    StringField218: TStringField;
    StringField219: TStringField;
    FloatField87: TFloatField;
    StringField220: TStringField;
    StringField221: TStringField;
    qry_merc_com_ato_: TQuery;
    qry_atz_po_item_: TQuery;
    StringField222: TStringField;
    StringField223: TStringField;
    StringField224: TStringField;
    StringField225: TStringField;
    StringField226: TStringField;
    StringField227: TStringField;
    StringField228: TStringField;
    StringField229: TStringField;
    StringField230: TStringField;
    StringField231: TStringField;
    StringField232: TStringField;
    StringField233: TStringField;
    StringField234: TStringField;
    StringField235: TStringField;
    StringField236: TStringField;
    StringField237: TStringField;
    StringField238: TStringField;
    StringField239: TStringField;
    StringField240: TStringField;
    StringField241: TStringField;
    StringField242: TStringField;
    StringField243: TStringField;
    StringField244: TStringField;
    StringField245: TStringField;
    StringField246: TStringField;
    StringField247: TStringField;
    StringField248: TStringField;
    StringField249: TStringField;
    StringField250: TStringField;
    StringField251: TStringField;
    StringField252: TStringField;
    StringField253: TStringField;
    StringField254: TStringField;
    DateTimeField9: TDateTimeField;
    DateTimeField10: TDateTimeField;
    DateTimeField11: TDateTimeField;
    DateTimeField12: TDateTimeField;
    StringField255: TStringField;
    BooleanField23: TBooleanField;
    BooleanField24: TBooleanField;
    StringField256: TStringField;
    StringField257: TStringField;
    BooleanField25: TBooleanField;
    StringField258: TStringField;
    StringField259: TStringField;
    StringField260: TStringField;
    StringField261: TStringField;
    BooleanField26: TBooleanField;
    BooleanField27: TBooleanField;
    StringField262: TStringField;
    BooleanField28: TBooleanField;
    StringField263: TStringField;
    StringField264: TStringField;
    StringField265: TStringField;
    StringField266: TStringField;
    StringField267: TStringField;
    StringField268: TStringField;
    StringField269: TStringField;
    StringField270: TStringField;
    StringField271: TStringField;
    FloatField88: TFloatField;
    FloatField89: TFloatField;
    FloatField90: TFloatField;
    FloatField91: TFloatField;
    FloatField92: TFloatField;
    FloatField93: TFloatField;
    FloatField94: TFloatField;
    FloatField95: TFloatField;
    StringField272: TStringField;
    FloatField96: TFloatField;
    StringField273: TStringField;
    StringField274: TStringField;
    BooleanField29: TBooleanField;
    StringField275: TStringField;
    StringField276: TStringField;
    StringField277: TStringField;
    StringField278: TStringField;
    StringField279: TStringField;
    FloatField97: TFloatField;
    MemoField4: TMemoField;
    FloatField98: TFloatField;
    FloatField99: TFloatField;
    FloatField100: TFloatField;
    FloatField101: TFloatField;
    FloatField102: TFloatField;
    FloatField103: TFloatField;
    FloatField104: TFloatField;
    FloatField105: TFloatField;
    FloatField106: TFloatField;
    FloatField107: TFloatField;
    FloatField108: TFloatField;
    FloatField109: TFloatField;
    FloatField110: TFloatField;
    FloatField111: TFloatField;
    FloatField112: TFloatField;
    StringField280: TStringField;
    StringField281: TStringField;
    BooleanField30: TBooleanField;
    BooleanField31: TBooleanField;
    StringField282: TStringField;
    StringField283: TStringField;
    FloatField113: TFloatField;
    StringField284: TStringField;
    StringField285: TStringField;
    qry_po_itens_IN_AVISO_DB: TStringField;
    qry_po_itens_NR_ITEM_CLIENTE: TStringField;
    sp_flp_po: TStoredProc;
    sp_flp_po_item: TStoredProc;
    qry_po_CD_SERVICO: TStringField;
    qry_flp_po_: TQuery;
    qry_flp_po_item_: TQuery;
    qry_flp_po_item_NR_PROCESSO: TStringField;
    qry_flp_po_item_NR_ITEM_CLIENTE: TStringField;
    qry_flp_po_NR_PROCESSO: TStringField;
    procedure qry_po_AfterPost(DataSet: TDataSet);
    procedure qry_po_itens_AfterPost(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  datm_po_leitura: Tdatm_po_leitura;

implementation

{$R *.DFM}

uses GSMLIB, PGSM155;

procedure Tdatm_po_leitura.qry_po_AfterPost(DataSet: TDataSet);
begin
  //seleciona o processo e verifica se o serviço já existe
  //se não existir, não insere o follow up
  qry_po_.Close;
  qry_po_.ParamByName('NR_PROCESSO').AsString := Copy( frm_po_leitura.Stri, 5, 10 );
  qry_po_.Prepare;
  qry_po_.Open;

  if ( qry_po_CD_SERVICO.AsString <> '' ) or ( qry_po_CD_SERVICO.AsString <> NULL ) then
  begin
    //verifica se o item da po já existe no follow up, se não existir adiciona
    qry_flp_po_.Close;
    qry_flp_po_.ParamByName('NR_PROCESSO').AsString := Copy( frm_po_leitura.Stri, 5, 10 );
    qry_flp_po_.Prepare;
    qry_flp_po_.Open;
    if qry_flp_po_.RecordCount >= 0 then
    begin
      CloseStoredProc(sp_flp_po);
      sp_flp_po.ParamByName('@NR_PROCESSO').AsString := qry_flp_po_NR_PROCESSO.AsString;
      sp_flp_po.ParamByName('@CD_SERVICO').AsString  := qry_po_CD_SERVICO.AsString;
      ExecStoredProc(sp_flp_po);
      CloseStoredProc(sp_flp_po);
    end;
    qry_flp_po_.Close;
  end;
end;

procedure Tdatm_po_leitura.qry_po_itens_AfterPost(DataSet: TDataSet);
begin
(*  //seleciona o processo e verifica se o serviço já existe
  //se não existir, não insere o follow up
  qry_po_.Close;
  qry_po_.ParamByName('NR_PROCESSO').AsString := Copy( frm_po_leitura.Stri, 5, 10 );
  qry_po_.Prepare;
  qry_po_.Open;

  if ( qry_po_CD_SERVICO.AsString <> '' ) or ( qry_po_CD_SERVICO.AsString <> NULL ) then
  begin
    //verifica se o item da po já existe no follow up, se não existir adiciona
    qry_flp_po_item_.Close;
    qry_flp_po_item_.ParamByName('NR_PROCESSO').AsString     := Copy( frm_po_leitura.Stri, 5, 10 );
    qry_flp_po_item_.ParamByName('NR_ITEM_CLIENTE').AsString := Copy( frm_po_leitura.Stri, 1, 4 );
    qry_flp_po_item_.Prepare;
    qry_flp_po_item_.Open;
    if qry_flp_po_item_.RecordCount >= 0 then
    begin
      CloseStoredProc(sp_flp_po_item);
      sp_flp_po_item.ParamByName('@NR_PROCESSO').AsString     := qry_flp_po_item_NR_PROCESSO.AsString;
      sp_flp_po_item.ParamByName('@NR_ITEM').AsString := qry_po_itens_NR_ITEM.AsString;
      sp_flp_po_item.ParamByName('@NR_ITEM_CLIENTE').AsString := qry_flp_po_item_NR_ITEM_CLIENTE.AsString;
      sp_flp_po_item.ParamByName('@CD_SERVICO').AsString      := qry_po_CD_SERVICO.AsString;
      ExecStoredProc(sp_flp_po_item);
      CloseStoredProc(sp_flp_po_item);
      qry_flp_po_item_.Next;
    end;
    qry_flp_po_item_.Close;
  end;*)
end;

end.
