SELECT
   L.DT_ULT_MUDANCA_STATUS,
   L.DT_CONSULTA_SCX,
   L.*,
   P.CD_UNID_NEG,
   SUBSTRING(L.NR_LI, 1, 2) + '/' + SUBSTRING(L.NR_LI, 3, 7) + '-' + SUBSTRING(L.NR_LI, 10, 1) LI_FORMATADA,
   U.NM_EMAIL,
   E.NM_EMPRESA,
   G.NM_EMAIL_CONSULTA_LI 
FROM
   TPROCESSO_LI L (NOLOCK) 
   INNER JOIN TPROCESSO P (NOLOCK) ON P.NR_PROCESSO = L.NR_PROCESSO 
   CROSS APPLY (SELECT E1.NM_EMPRESA FROM TEMPRESA_NAC E1 (NOLOCK)  WHERE E1.CD_EMPRESA = P.CD_CLIENTE ) E 
   CROSS APPLY (SELECT G1.NM_EMAIL_CONSULTA_LI FROM TGRUPO G1 (NOLOCK) WHERE G1.CD_GRUPO = P.CD_GRUPO ) G 
   LEFT JOIN TUSUARIO U (NOLOCK) ON U.CD_USUARIO = P.CD_ANALISTA_COMISSARIA

WHERE
ISNULL(P.IN_CANCELADO, '0') <> '1' 
AND ISNULL(L.IN_CANCELADO, '0') <> '1' 
AND ISNULL(L.IN_UTILIZADO, '0') <> '1' 
AND CONVERT(INT, REPLACE( SUBSTRING(L.NR_LI, 1, 2), '\','0')) BETWEEN 10 AND 25 
 				-- AND CD_GRUPO IN ('002', '155')
AND 
(
               /* E PROCESSOS LI QUE NÃO TIVEREM STATUS DEFERIDO */
  ( 
		( SELECT COUNT(*) FROM TPROCESSO_LI_STATUS LS (NOLOCK) 
						  WHERE LS.NR_PROCESSO = L.NR_PROCESSO AND LS.NR_LI = L.NR_LI AND LS.TX_STATUS in ('DEFERIDO', 'DEFERIDA')
		 ) = 0 
   ) 
   
   OR 						/* OU QUE TIVER STATUS DE DEFERIDO, MAS NÃO TIVER STATUS DE UTILIZADO */
   ( 
		 ( ( SELECT COUNT(*)  FROM TPROCESSO_LI_STATUS LS (NOLOCK) 
							  WHERE LS.NR_PROCESSO = L.NR_PROCESSO AND LS.NR_LI = L.NR_LI AND LS.TX_STATUS in ('DEFERIDO', 'DEFERIDA')
		   ) > 0 
		 ) 
		 AND 
		 ( ( SELECT COUNT(*)  FROM TPROCESSO_LI_STATUS LS (NOLOCK) 
							  WHERE LS.NR_PROCESSO = L.NR_PROCESSO AND LS.NR_LI = L.NR_LI AND LS.TX_STATUS = 'UTILIZADO' 
		   ) = 0
		 )
   ) 
)
AND L.DT_CONSULTA_SCX < L.DT_ULT_MUDANCA_STATUS 
--AND NOT (L.DT_CONSULTA_SCX BETWEEN CAST('2000-01-01' AS DATE) AND CAST('2018-01-01' AS DATE))

ORDER BY P.CD_UNID_NEG, P.DT_ABERTURA DESC, P.NR_PROCESSO, L.NR_LI
