<%
	matriz = Split(Session("tx_filtros"),";",-1)
	
	objtxt.WriteLine("<html xmlns:o=""urn:schemas-microsoft-com:office:office""")
	objtxt.WriteLine("xmlns:x=""urn:schemas-microsoft-com:office:excel""")
	objtxt.WriteLine("xmlns=""http://www.w3.org/TR/REC-html40"">")
	
	objtxt.WriteLine("<head>")
	objtxt.WriteLine("<meta http-equiv=Content-Type content=""text/html; charset=windows-1252"">")
	objtxt.WriteLine("<meta name=ProgId content=Excel.Sheet>")
	objtxt.WriteLine("<title>"& nm_rel &"</title>")
	objtxt.WriteLine("<!--[if !mso]>")
	objtxt.WriteLine("<style>")
	objtxt.WriteLine("x\:* {behavior:url(#default#VML);}")
	objtxt.WriteLine("</style>")
	objtxt.WriteLine("<![endif]-->")
	objtxt.WriteLine("<style>")
	objtxt.WriteLine("<!--")
	objtxt.WriteLine("body {")
	objtxt.WriteLine("	font-family: Verdana, Arial, Helvetica, sans-serif;")
	objtxt.WriteLine("	color: #000000;")
	objtxt.WriteLine("	background-color: #FFFFFF;")
	objtxt.WriteLine("	margin: 0px;")
	objtxt.WriteLine("	padding: 0px;")
	objtxt.WriteLine("}")
	objtxt.WriteLine("table {")
	objtxt.WriteLine("	mso-displayed-decimal-separator:""\,"";")
	objtxt.WriteLine("	mso-displayed-thousand-separator:""\."";")
	objtxt.WriteLine("}")
	objtxt.WriteLine("tr {")
	'objtxt.WriteLine("	mso-height-source:auto;")
	objtxt.WriteLine("}")
	objtxt.WriteLine("td {")
	objtxt.WriteLine("	font-size: 10px;")
	'objtxt.WriteLine("	mso-width-source:auto;")			
	objtxt.WriteLine("}")
	objtxt.WriteLine("br {")
	objtxt.WriteLine("	mso-data-placement:same-cell;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".basico	{")
	objtxt.WriteLine("	text-align:general;")
	objtxt.WriteLine("	vertical-align:general;")
	objtxt.WriteLine("	white-space:nowrap;")
	objtxt.WriteLine("	mso-generic-font-family:auto;")
	objtxt.WriteLine("	mso-font-charset:0;")
	objtxt.WriteLine("	mso-number-format:General;")
	objtxt.WriteLine("	mso-background-source:auto;")
	objtxt.WriteLine("	mso-pattern:auto;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".titulo {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	vertical-align:top;")
	objtxt.WriteLine("	font-size: 14px;")
	objtxt.WriteLine("	font-weight: bold;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".gridtop {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	color: #FFFFFF;")
	objtxt.WriteLine("	font-style: italic;")
	objtxt.WriteLine("	font-weight: bold;")
	objtxt.WriteLine("	font-size: 13px;")
	objtxt.WriteLine("	background: #003366;")
	objtxt.WriteLine("	vertical-align: middle;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".gridtit {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	color: #FFFFFF;")
	objtxt.WriteLine("	font-weight: bold;")
	objtxt.WriteLine("	text-align: center;")
	objtxt.WriteLine("	background: #003366;")
	objtxt.WriteLine("	vertical-align: middle;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".gridtit2 {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	color: #FFFFFF;")
	objtxt.WriteLine("	font-weight: bold;")
	objtxt.WriteLine("	text-align: left;")
	objtxt.WriteLine("	background: #003366;")
	objtxt.WriteLine("	vertical-align: middle;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".gridsub {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	color: #FFFFFF;")
	objtxt.WriteLine("	background: #003366;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".tb1 {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("  border-style: solid;")
	objtxt.WriteLine("  border-width: 0px 0px 1px 0px;")
	objtxt.WriteLine("  border-color: #000000;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".tb2 {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("  border-style: dotted;")
	objtxt.WriteLine("  border-width: 0px 0px 1px 0px;")
	objtxt.WriteLine("  border-color: #333333;")
	objtxt.WriteLine("  padding: 2px;")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".data {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	mso-number-format:""Short Date"";")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".time {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	mso-number-format:""Short Time"";")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".inteiro {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	mso-number-format:""\#\,\#\#0"";")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".decimal {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	mso-number-format:""\#\,\#\#0\.0"";")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".decimal2 {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	mso-number-format:""\#\,\#\#0\.00"";")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".decimal4 {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	mso-number-format:""\#\,\#\#0\.0000"";")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".moeda {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	mso-number-format:""\0022R$ \0022\#\,\#\#0\.00_\)\;\[Red\]\\\(\0022R$ \0022\#\,\#\#0\.00\\\)"";")
	objtxt.WriteLine("}")
	objtxt.WriteLine(".texto {")
	objtxt.WriteLine("	mso-style-parent:basico;")
	objtxt.WriteLine("	mso-ignore:padding;")
	objtxt.WriteLine("}")
	objtxt.WriteLine("-->")
	objtxt.WriteLine("</style></head><body>")
	objtxt.WriteLine("<table x:str border=1 cellpadding=0 cellspacing=0 bordercolor='#FFFFFF' style='padding: 0px 1px 0px 1px;'>")
	
	Select Case tp_rel
		Case 2, 10, 11, 12, 15
			Select Case tp_rel 
				Case 2, 11, 15
					nm_rel = nm_rel
				Case Else
					nm_rel = nm_rel &" - Per&iacute;odo de "& Request.QueryString("dt_eventoi") &" á "& Request.QueryString("dt_eventof")
			End Select
			objtxt.WriteLine("  <tr height='40'>")
			objtxt.WriteLine("    <td width='100' valign='top'><img src='http://www.myindaia.com.br/img/logo_indaia.gif' width='190' height='85'></td>")
			objtxt.WriteLine("    <td width='100'>&nbsp;</td>")
			objtxt.WriteLine("	<td colspan='"& (col-2) &"' class='titulo'>"& nm_rel &"</td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("    <td width='80' style='text-align:right;'>Cliente:</td>")
			objtxt.WriteLine("    <td colspan='"& (col-3) &"' style='text-align:left;'><b>")
			If Request.QueryString("cd_grupo") = "X" or Not fnc_TestaVar(Request.QueryString("cd_grupo")) Then
				If Request.QueryString("cd_cliente") = "X" or Not fnc_TestaVar(Request.QueryString("cd_cliente")) Then
					objtxt.WriteLine("Todos")
				Else
					objtxt.WriteLine( fnc_ConsultaLookup("TEMPRESA_NAC","CD_EMPRESA",Request.QueryString("cd_cliente"),"NM_EMPRESA") )
				End If
			Else
				objtxt.WriteLine( fnc_ConsultaLookup("TGRUPO","CD_GRUPO",Request.QueryString("cd_grupo"),"NM_GRUPO") )
			End If
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("    <td style='text-align:right;'>Unidade:</td>")
			objtxt.WriteLine("    <td colspan='"& (col-3) &"' style='text-align:left;'><b>")
			If Request.QueryString("cd_unid_neg") = "X" or Not fnc_TestaVar(Request.QueryString("cd_unid_neg")) Then
				objtxt.WriteLine("Todas")
			Else
				objtxt.WriteLine( fnc_ConsultaLookup("TUNID_NEG","CD_UNID_NEG",Request.QueryString("cd_unid_neg"),"NM_UNID_NEG") )
			End If
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("    <td style='text-align:right;'>Produto:</td>")
			objtxt.WriteLine("    <td colspan='"& (col-3) &"' style='text-align:left;'><b>")
			If Request.QueryString("cd_produto") = "X" or Not fnc_TestaVar(Request.QueryString("cd_produto")) Then
				objtxt.WriteLine("Todos")
			Else
				objtxt.WriteLine( fnc_ConsultaLookup("TPRODUTO","CD_PRODUTO",Request.QueryString("cd_produto"),"NM_PRODUTO") )
			End If
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("  </tr>")
	  
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("    <td colspan='"& (col-3) &"' style='text-align:left;'>Emitido "& FormatDateTime(Date(), vbLongDate) &" às "& FormatDateTime(Time(), vbShortTime) &" por "& Session("nm_usuario") &"</td>")
			objtxt.WriteLine("  </tr>")
		Case 13 'GSI Exportação
			objtxt.WriteLine("  <tr height='25'>")
			objtxt.WriteLine("    <td width='100' valign='top'><img src='http://www.myindaia.com.br/img/logo_indaia.gif' width='190' height='85'></td>")
			objtxt.WriteLine("    <td width='100'>&nbsp;</td>")
			objtxt.WriteLine("	  <td colspan='2' class='titulo'>"& nm_rel &"</td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("    <td width='90' style='text-align:right;'>Cliente:</td>")
			objtxt.WriteLine("    <td width='400' style='text-align:left;'><b>")
			If Request.QueryString("cd_grupo") = "X" or Not fnc_TestaVar(Request.QueryString("cd_grupo")) Then
				If Request.QueryString("cd_cliente") = "X" or Not fnc_TestaVar(Request.QueryString("cd_cliente")) Then
					objtxt.WriteLine("Todos")
				Else
					objtxt.WriteLine( fnc_ConsultaLookup("TEMPRESA_NAC","CD_EMPRESA",Request.QueryString("cd_cliente"),"NM_EMPRESA") )
				End If
			Else
				objtxt.WriteLine( fnc_ConsultaLookup("TGRUPO","CD_GRUPO",Request.QueryString("cd_grupo"),"NM_GRUPO") )
			End If
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("    <td style='text-align:right;'>Unidade:</td>")
			objtxt.WriteLine("    <td style='text-align:left;'><b>")
			If Request.QueryString("cd_unid_neg") = "X" or Not fnc_TestaVar(Request.QueryString("cd_unid_neg")) Then
				objtxt.WriteLine("Todas")
			Else
				objtxt.WriteLine( fnc_ConsultaLookup("TUNID_NEG","CD_UNID_NEG",Request.QueryString("cd_unid_neg"),"NM_UNID_NEG") )
			End If
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("    <td style='text-align:right;'>Produto:</td>")
			objtxt.WriteLine("    <td style='text-align:left;'><b>")
			If Request.QueryString("cd_produto") = "X" or Not fnc_TestaVar(Request.QueryString("cd_produto")) Then
				objtxt.WriteLine("Exportação")
			Else
				objtxt.WriteLine( fnc_ConsultaLookup("TPRODUTO","CD_PRODUTO",Request.QueryString("cd_produto"),"NM_PRODUTO") )
			End If
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("  </tr>")
			
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("    <td colspan='2' style='text-align:left;'>Emitido "& FormatDateTime(Date(), vbLongDate) &" às "& FormatDateTime(Time(), vbShortTime) &" por "& Session("nm_usuario") &"</td>")
			objtxt.WriteLine("  </tr>")
		Case 14 'Detalhe GSI Exportação
			objtxt.WriteLine("  <tr height='25'>")
			objtxt.WriteLine("    <td width='75' valign='top'><img src='http://www.myindaia.com.br/img/logo_indaia.gif' width='150' height='70'></td>")
			objtxt.WriteLine("    <td width='75'>&nbsp;</td>")
			objtxt.WriteLine("	  <td colspan='4' class='titulo'>"& nm_rel &"</td>")
			objtxt.WriteLine("  </tr>")
			
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("	  <td colspan='4'><b>Performace "& objrsx.Fields.Item("NR_DIA_PERFORMACE").Value &" Dias</b></td>")
			objtxt.WriteLine("  </tr>")
			
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("    <td width='80' style='text-align:right;'>País:</td>")
			objtxt.WriteLine("    <td width='180' style='text-align:left;'><b>")
			objtxt.WriteLine(       UCase(fnc_ConsultaLookup("TPAIS", "CODIGO", Request.QueryString("cd_pais_destino"), "DESCRICAO")) )
			objtxt.WriteLine(" (")
			objtxt.WriteLine(       UCase(fnc_ConsultaLookup("TEMPRESA_EST", "CD_EMPRESA", Request.QueryString("cd_importador"), "NM_EMPRESA")) )
						objtxt.WriteLine(") ")
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("    <td width='80' style='text-align:right;'>Atualizado:</td>")
			objtxt.WriteLine("    <td width='180' style='text-align:left;'><b>")
			objtxt.WriteLine("    "& fnc_Mascara(objrsx.Fields.Item("DT_ALTERACAO").Value, 5) ) 
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("  </tr>")
			
			objtxt.WriteLine("  <tr height='16'>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("	  <td>&nbsp;</td>")
			objtxt.WriteLine("    <td style='text-align:right;'>Mercadoria:</td>")
			objtxt.WriteLine("    <td style='text-align:left;'><b>")
			objtxt.WriteLine(       UCase(fnc_ConsultaLookup("TFAMILIA_PROD", "CD_FAMILIA_PROD", Request.QueryString("cd_familia_prod"), "NM_FAMILIA_PROD")) )
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("    <td style='text-align:right;'>Usu&aacute;rio:</td>")
			objtxt.WriteLine("    <td style='text-align:left;'><b>")
			objtxt.WriteLine("    "& UCase(fnc_ConsultaLookup("TUSUARIO", "CD_USUARIO", objrsx.Fields.Item("CD_USUARIO").Value, "NM_USUARIO")) )
			objtxt.WriteLine("    </b></td>")
			objtxt.WriteLine("  </tr>")
		Case Else
			objtxt.WriteLine("  <tr>")
			objtxt.WriteLine("    <td width='100'><img src='http://www.myindaia.com.br/img/logo_indaia.gif' width='180' height='69'></td>")
			objtxt.WriteLine("    <td width='100'>&nbsp;</td>")
			objtxt.WriteLine("    <td colspan='"& col - 2 &"' class='titulo'>Relatório MyIndaia WEB</td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr>")
			objtxt.WriteLine("    <td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr>")
			objtxt.WriteLine("    <td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr>")
			objtxt.WriteLine("  	<td>&nbsp;</td>")
			objtxt.WriteLine("	<td>&nbsp;</td>")
			objtxt.WriteLine("    <td colspan='"& col - 2 &"'>Emitido "& FormatDateTime(Date(), vbLongDate) &" às "& FormatDateTime(Time(), vbShortTime) &" por "& Session("nm_usuario") &"</td>")
			objtxt.WriteLine("  </tr>")
			objtxt.WriteLine("  <tr height='5'>")
			objtxt.WriteLine("    <td colspan='"& col &"'></td>")
			objtxt.WriteLine("  </tr>")
  End Select
%>