<%@LANGUAGE="VBSCRIPT" CODEPAGE="1252"%>
<%
'---------------------------------------------------------------------------
'Sistema MyIndaiá - Entrada do Sistema
'Arquivo de Script e HTML: Usado para alimentar planilha Nestle
'
'Autor: Nelson Pontes
'Criado: 29/01/2021
'
'Manutenção: 
'---------------------------------------------------------------------------
%>


<html xmlns="http://www.w3.org/1999/xhtml">
<head>

</head>
<body>

<%
Dim cnstr, novoNome
	Set cnn = Server.CreateObject("ADODB.Connection")
	Set cmd = Server.CreateObject("ADODB.Command")
	Set rs  = Server.CreateObject("ADODB.Recordset")
	cnstr = "Provider=SQLOLEDB;Persist Security Info=True;"&_
					"Data Source=INDAIA10;Initial Catalog=BROKER;"&_
					"User ID=SA;Password=123;"
	On error resume next
	cnn.Open cnstr
	cmd.ActiveConnection = cnn
	

	sql ="SELECT "&_
	" SUBSTRING(TP.NR_PROCESSO,5,16) AS [Processo Indaia] "&_
	" ,CASE WHEN TP.IN_DESEMBARACO_SOBRE_AGUAS=1 THEN 'Sim' ELSE 'Não' END AS [Desembaraço sobre aguas] "&_
	" ,EN.NM_EMPRESA AS [Cliente] "&_
	" ,CASE WHEN TP.IN_URGENTE=1 THEN 'Sim' ELSE 'Não' END AS [Urgente] "&_
	" ,RTRIM(R.CD_REFERENCIA) + '/' +R.NR_ITEM_PO AS [Pedido]  "&_
	" ,A.NM_AREA AS [Area] "&_
	" ,CC.NM_CONTATO AS [Contato] "&_
	" ,TP.TX_MERCADORIA AS [Mercadoria] "&_
	" ,EV605.DT_REALIZACAO AS [Dt Recepção de cópia do BL] "&_
	" ,EV082.DT_REALIZACAO AS [Dt Doctos Completos p/ análise] "&_
	" ,EV161.DT_REALIZACAO AS [Dt Previsão de Chegada do Navio] "&_
	" ,EV162.DT_REALIZACAO AS [Dt Chegada do Navio] "&_
	" ,EV012.DT_REALIZACAO AS [Dt Presença de Carga] "&_
	" ,EV943.DT_REALIZACAO AS [Dt Sigvig OK] "&_
	" ,EV021.DT_REALIZACAO AS [Dt Registro DI] "&_
	" ,EV088.DT_REALIZACAO AS [Dt Desembaraço] "&_
	" ,EV616.DT_REALIZACAO AS [Dt Recebimento da Danfe] "&_
	" ,EV041.DT_REALIZACAO AS [Dt Liberação para transporte] "&_
	" , "&_
	" CASE "&_
	" WHEN (EV605.DT_REALIZACAO IS NULL) AND 	 (EV082.DT_REALIZACAO IS NULL) AND  "&_
		" (EV161.DT_REALIZACAO IS NULL) AND 	 (EV162.DT_REALIZACAO IS NULL) AND  "&_
		" (EV012.DT_REALIZACAO IS NULL) AND 	 (EV943.DT_REALIZACAO IS NULL) AND  "&_
		" (EV021.DT_REALIZACAO IS NULL) AND 	 (EV088.DT_REALIZACAO IS NULL) AND  "&_
		" (EV616.DT_REALIZACAO IS NULL) AND 	 (EV041.DT_REALIZACAO IS NULL)  "&_
	" THEN 'Aberto, aguardando dados'  "&_
	" WHEN (EV605.DT_REALIZACAO IS NOT NULL AND EV605.IN_APLICAVEL='1') AND (EV082.DT_REALIZACAO IS NULL AND EV082.IN_APLICAVEL='1') THEN 'Ag. Docs completos'  "&_
	" WHEN (EV082.DT_REALIZACAO IS NOT NULL AND EV082.IN_APLICAVEL='1') AND (EV161.DT_REALIZACAO IS NULL AND EV161.IN_APLICAVEL='1') THEN 'Em análise documental - Despachante'  "&_
	" WHEN (EV161.DT_REALIZACAO IS NOT NULL AND EV161.IN_APLICAVEL='1') AND (EV162.DT_REALIZACAO IS NULL AND EV162.IN_APLICAVEL='1') THEN 'Ag. Chegada do Navio'  "&_
	" WHEN (EV162.DT_REALIZACAO IS NOT NULL AND EV162.IN_APLICAVEL='1') AND (EV012.DT_REALIZACAO IS NULL AND EV012.IN_APLICAVEL='1') THEN 'Ag. Presença de Carga'  "&_
	" WHEN (EV012.DT_REALIZACAO IS NOT NULL AND EV012.IN_APLICAVEL='1') AND (EV943.DT_REALIZACAO IS NULL AND EV943.IN_APLICAVEL='1') THEN 'Ag. Liberação SIGVIG'  "&_
	" WHEN (EV012.DT_REALIZACAO IS NOT NULL AND EV012.IN_APLICAVEL='1') AND (EV943.DT_REALIZACAO IS NULL AND EV943.IN_APLICAVEL='0') AND (EV021.DT_REALIZACAO IS NULL AND EV021.IN_APLICAVEL='1') THEN 'Ag. Registro da DI'  "&_
	" WHEN (EV012.DT_REALIZACAO IS NOT NULL AND EV012.IN_APLICAVEL='1') AND (EV021.DT_REALIZACAO IS NULL AND EV021.IN_APLICAVEL='1') THEN 'Ag. Registro da DI'  "&_
	" WHEN (EV943.DT_REALIZACAO IS NOT NULL AND EV943.IN_APLICAVEL='1') AND (EV021.DT_REALIZACAO IS NULL AND EV021.IN_APLICAVEL='1') THEN 'Ag. Registro da DI'  "&_
	" WHEN (EV021.DT_REALIZACAO IS NOT NULL AND EV021.IN_APLICAVEL='1') AND (EV088.DT_REALIZACAO IS NULL AND EV088.IN_APLICAVEL='1') THEN 'Ag. Desembaraço'  "&_
	" WHEN (EV088.DT_REALIZACAO IS NOT NULL AND EV088.IN_APLICAVEL='1') AND (EV616.DT_REALIZACAO IS NULL AND EV616.IN_APLICAVEL='1') THEN 'Aguardando emissão da DANFE'  "&_
	" WHEN (EV616.DT_REALIZACAO IS NOT NULL AND EV616.IN_APLICAVEL='1') AND (EV041.DT_REALIZACAO IS NULL AND EV041.IN_APLICAVEL='1') THEN 'Ag. Liberação p/ Transporte'  "&_
	" WHEN (EV041.DT_REALIZACAO IS NOT NULL AND EV041.IN_APLICAVEL='1') THEN 'Liberado p/ transporte'  "&_
	" ELSE 'Falta parametro para Status (informar TI)'  "&_
	" END AS [Status],  "&_
	" (SELECT CASE WHEN COUNT(NR_LI) > 0 THEN 'COM LI' ELSE 'SEM LI' END FROM BROKER.DBO.TPROCESSO_LI WHERE NR_PROCESSO= TP.NR_PROCESSO) AS [Possui LI],  "&_
	" CASE WHEN EV943.IN_APLICAVEL='0' THEN 'SEM INSPEÇÃO' WHEN EV943.IN_APLICAVEL='1' AND EV943.DT_REALIZACAO IS NULL THEN 'SEM SIGVIG' ELSE 'COM SIGVIG' END AS [Sigvig],  "&_
	" ISNULL((BROKER.DBO.FN_KPI_CORRIDOS ((EV162.DT_REALIZACAO),(GETDATE()))),'') AS [ETA - Hoje] "&_
	" FROM BROKER.DBO.TPROCESSO TP (NOLOCK)  "&_
	" LEFT JOIN BROKER.DBO.TREF_CLIENTE R (NOLOCK) ON R.NR_PROCESSO = TP.NR_PROCESSO AND R.TP_REFERENCIA = '01'  "&_
	" INNER JOIN BROKER.DBO.TEMPRESA_NAC EN (NOLOCK) ON EN.CD_EMPRESA = TP.CD_CLIENTE  "&_
	" INNER JOIN BROKER.DBO.TAREA A (NOLOCK) ON A.CD_AREA = TP.CD_AREA  "&_
	" LEFT JOIN BROKER.DBO.TCLIENTE_CONTATO CC (NOLOCK) ON CC.CD_CONTATO = TP.CD_CONTATO AND TP.CD_CLIENTE = CC.CD_CLIENTE AND TP.CD_UNID_NEG = CC.CD_UNID_NEG AND TP.CD_PRODUTO = CC.CD_PRODUTO  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV041 (NOLOCK) ON EV041.NR_PROCESSO = TP.NR_PROCESSO AND EV041.CD_EVENTO='041'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV605 (NOLOCK) ON EV605.NR_PROCESSO = TP.NR_PROCESSO AND EV605.CD_EVENTO='605'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV082 (NOLOCK) ON EV082.NR_PROCESSO = TP.NR_PROCESSO AND EV082.CD_EVENTO='082'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV161 (NOLOCK) ON EV161.NR_PROCESSO = TP.NR_PROCESSO AND EV161.CD_EVENTO='161'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV162 (NOLOCK) ON EV162.NR_PROCESSO = TP.NR_PROCESSO AND EV162.CD_EVENTO='162'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV012 (NOLOCK) ON EV012.NR_PROCESSO = TP.NR_PROCESSO AND EV012.CD_EVENTO='012'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV943 (NOLOCK) ON EV943.NR_PROCESSO = TP.NR_PROCESSO AND EV943.CD_EVENTO='943'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV021 (NOLOCK) ON EV021.NR_PROCESSO = TP.NR_PROCESSO AND EV021.CD_EVENTO='021'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV088 (NOLOCK) ON EV088.NR_PROCESSO = TP.NR_PROCESSO AND EV088.CD_EVENTO='088'  "&_
	" LEFT JOIN BROKER.DBO.TFOLLOWUP EV616 (NOLOCK) ON EV616.NR_PROCESSO = TP.NR_PROCESSO AND EV616.CD_EVENTO='616'  "&_
	" WHERE TP.CD_GRUPO IN ('002','013','559')  "&_
	" AND TP.CD_PRODUTO = '01'  "&_
	" AND TP.IN_CANCELADO='0'  "&_
	" AND  "&_
	" ((EV041.IN_APLICAVEL='1')  "&_
	" AND  "&_
	" (EV041.DT_REALIZACAO IS NULL AND EV041.IN_APLICAVEL='1')  "&_
	" OR  "&_
	" (EV041.DT_REALIZACAO >= GETDATE()-3))  "&_
	" AND (EV161.DT_REALIZACAO IS not NULL)  "&_
	" AND(  "&_
	" (EV605.DT_REALIZACAO IS not NULL) or (EV082.DT_REALIZACAO IS not NULL) or   "&_
	" (EV161.DT_REALIZACAO IS not NULL) or (EV162.DT_REALIZACAO IS not NULL) or   "&_
	" (EV012.DT_REALIZACAO IS not NULL) or (EV943.DT_REALIZACAO IS not NULL) or   "&_
	" (EV021.DT_REALIZACAO IS not NULL) or (EV088.DT_REALIZACAO IS not NULL) or   "&_
	" (EV616.DT_REALIZACAO IS not NULL) or (EV041.DT_REALIZACAO IS not NULL)   "&_
	" )"
	
	
	rs.Open sql, cnn,1,1

%>
<table border="1">
  <tr>
  <%for each x in rs.Fields
    response.write("<th>" & x.name & "</th>")
  next%>
  </tr>
  <%do until rs.EOF%>
    <tr>
    <%for each x in rs.Fields%>
      <td><%Response.Write(x.value)%></td>
    <%next
    rs.MoveNext%>
    </tr>
  <%loop
  rs.close
  conn.close%>
</table>

</body>
</html>
