unit DocumentosFaturamento;

interface

uses
  SysUtils, Classes, ExtCtrls, DB, ADODB, ppBands, ppReport,
  ppSubRpt, ppClass, Graphics, ppCtrls, jpeg, ppStrtch, ppMemo, ppPrnabl,
  ppCache, ppParameter, ppComm, ppRelatv, ppProd, ppDB, ppDBPipe, DBClient,
  Provider, ppRegion, ppEndUsr, FMTBcd, DBXMSSQL, SqlExpr, ppBarCode2D,
  ppModule, raCodMod, ppPageBreak, ppRichTx, ppVar, GIFImg, ppDesignLayer;

type
  TdtmDocumentosFaturamento = class(TDataModule)
    CapaMyIndaiaV2: TADOQuery;
    CapaMyIndaiaV2EmissaoExtenso: TWideStringField;
    CapaMyIndaiaV2Fatura: TWideStringField;
    CapaMyIndaiaV2NomeCliente: TWideStringField;
    CapaMyIndaiaV2BairroCliente: TWideStringField;
    CapaMyIndaiaV2CNPJCliente: TWideStringField;
    CapaBroker: TADOQuery;
    CapaBrokerNR_PROCESSO: TStringField;
    CapaBrokerNomeAnalista: TStringField;
    CapaBrokerPedidoCliente: TWideStringField;
    CapaBrokerNR_DI: TStringField;
    CapaBrokerNR_PLACA_VEICULO: TStringField;
    CapaBrokerDT_PRESENCA_CARGA: TDateTimeField;
    CapaBrokerDESCRICAO: TStringField;
    CapaBrokerVL_CIF_MN: TFloatField;
    CapaBrokerVL_MLE_MN: TFloatField;
    CapaBrokerDescricao_1: TStringField;
    CapaBrokerTX_MERCADORIA: TMemoField;
    ItensDocumento: TADOQuery;
    ItensDocumentoItem: TWideStringField;
    ItensDocumentoValorItem: TBCDField;
    dsCapaMyIndaiaV2: TDataSource;
    dsCapaBroker: TDataSource;
    dsItensDocumento: TDataSource;
    ppCapaMyIndaiaV2: TppDBPipeline;
    ppItensDocumento: TppDBPipeline;
    dspCapaMyIndaiaV2: TDataSetProvider;
    cdsCapaMyIndaiaV2: TClientDataSet;
    cdsCapaMyIndaiaV2EmissaoExtenso: TWideStringField;
    cdsCapaMyIndaiaV2Fatura: TWideStringField;
    cdsCapaMyIndaiaV2NomeCliente: TWideStringField;
    cdsCapaMyIndaiaV2BairroCliente: TWideStringField;
    cdsCapaMyIndaiaV2CNPJCliente: TWideStringField;
    dspCapaBroker: TDataSetProvider;
    cdsCapaBroker: TClientDataSet;
    dspItensDocumento: TDataSetProvider;
    cdsItensDocumento: TClientDataSet;
    cdsCapaBrokerNR_PROCESSO: TStringField;
    cdsCapaBrokerNomeAnalista: TStringField;
    cdsCapaBrokerPedidoCliente: TWideStringField;
    cdsCapaBrokerNR_DI: TStringField;
    cdsCapaBrokerNR_PLACA_VEICULO: TStringField;
    cdsCapaBrokerDT_PRESENCA_CARGA: TDateTimeField;
    cdsCapaBrokerDESCRICAO: TStringField;
    cdsCapaBrokerVL_CIF_MN: TFloatField;
    cdsCapaBrokerVL_MLE_MN: TFloatField;
    cdsCapaBrokerDescricao_1: TStringField;
    cdsCapaBrokerTX_MERCADORIA: TMemoField;
    cdsItensDocumentoItem: TWideStringField;
    cdsItensDocumentoValorItem: TBCDField;
    ppCapaBroker: TppDBPipeline;
    ModelosDocumentos: TADOQuery;
    ModelosDocumentosCD_UNID_NEG: TIntegerField;
    ModelosDocumentosCD_PRODUTO: TIntegerField;
    ModelosDocumentosCD_ROTINA: TIntegerField;
    ModelosDocumentosDESCRICAO: TStringField;
    ModelosDocumentosNM_PATH: TStringField;
    ModelosDocumentosCD_GRUPO: TStringField;
    dspModelosDocumentos: TDataSetProvider;
    dsModelosDocumentos: TDataSource;
    cdsModelosDocumentos: TClientDataSet;
    cdsModelosDocumentosCD_UNID_NEG: TIntegerField;
    cdsModelosDocumentosCD_PRODUTO: TIntegerField;
    cdsModelosDocumentosCD_ROTINA: TIntegerField;
    cdsModelosDocumentosDESCRICAO: TStringField;
    cdsModelosDocumentosNM_PATH: TStringField;
    cdsModelosDocumentosCD_GRUPO: TStringField;
    Report: TppReport;
    CapaMyIndaiaV2EndCliente: TWideStringField;
    cdsCapaMyIndaiaV2EndCliente: TWideStringField;
    CapaMyIndaiaV2CidadeCliente: TWideStringField;
    cdsCapaMyIndaiaV2CidadeCliente: TWideStringField;
    CapaMyIndaiaV2UFCliente: TWideStringField;
    CapaMyIndaiaV2CepCliente: TWideStringField;
    cdsCapaMyIndaiaV2UFCliente: TWideStringField;
    cdsCapaMyIndaiaV2CepCliente: TWideStringField;
    CapaMyIndaiaV2inscEstadual: TWideStringField;
    cdsCapaMyIndaiaV2inscEstadual: TWideStringField;
    Faturamento: TADOQuery;
    Faturamentobillind_id: TLargeintField;
    FaturamentoRPS: TWideStringField;
    FaturamentoDataEmissao: TStringField;
    FaturamentoDataVencimento: TStringField;
    FaturamentoNomeUnidFat: TStringField;
    FaturamentoEndUnidFat: TStringField;
    FaturamentoCNPJUnidFat: TStringField;
    FaturamentoTelUnidFat: TStringField;
    FaturamentoBairroUnidFat: TStringField;
    FaturamentoIEUnidFat: TStringField;
    FaturamentoIMUnidFat: TStringField;
    FaturamentoCidadeUnidFat: TStringField;
    FaturamentoFaxUnidFat: TStringField;
    FaturamentoUFUnidFat: TStringField;
    dspFaturamento: TDataSetProvider;
    dsFaturamento: TDataSource;
    cdsFaturamento: TClientDataSet;
    cdsFaturamentobillind_id: TLargeintField;
    cdsFaturamentoRPS: TWideStringField;
    cdsFaturamentoDataEmissao: TStringField;
    cdsFaturamentoDataVencimento: TStringField;
    cdsFaturamentoNomeUnidFat: TStringField;
    cdsFaturamentoEndUnidFat: TStringField;
    cdsFaturamentoCNPJUnidFat: TStringField;
    cdsFaturamentoTelUnidFat: TStringField;
    cdsFaturamentoBairroUnidFat: TStringField;
    cdsFaturamentoIEUnidFat: TStringField;
    cdsFaturamentoIMUnidFat: TStringField;
    cdsFaturamentoCidadeUnidFat: TStringField;
    cdsFaturamentoFaxUnidFat: TStringField;
    cdsFaturamentoUFUnidFat: TStringField;
    ppFaturamento: TppDBPipeline;
    FaturamentoCEPUnidFat: TStringField;
    cdsFaturamentoCEPUnidFat: TStringField;
    CapaBrokerNM_VIA_TRANSPORTE: TStringField;
    cdsCapaBrokerNM_VIA_TRANSPORTE: TStringField;
    CapaBrokerNM_AREA: TStringField;
    CapaBrokerNM_CONTATO: TStringField;
    CapaBrokerNM_REFERENCIA: TWideStringField;
    cdsCapaBrokerNM_AREA: TStringField;
    cdsCapaBrokerNM_CONTATO: TStringField;
    cdsCapaBrokerNM_REFERENCIA: TWideStringField;
    ppDesigner1: TppDesigner;
    CapaBrokerVOLUME: TStringField;
    CapaBrokerNM_LOCAL_EMBARQUE: TStringField;
    CapaBrokerNM_VEICULO: TStringField;
    cdsCapaBrokerVOLUME: TStringField;
    cdsCapaBrokerNM_LOCAL_EMBARQUE: TStringField;
    cdsCapaBrokerNM_VEICULO: TStringField;
    TotaisFatura: TADOQuery;
    TotaisFaturaDataNumerario: TStringField;
    TotaisFaturaTotalNumerario: TBCDField;
    TotaisFaturaTotalDespesa: TFMTBCDField;
    TotaisFaturaTotalFatura: TBCDField;
    dspTotaisFatura: TDataSetProvider;
    dsTotaisFatura: TDataSource;
    cdsTotaisFatura: TClientDataSet;
    cdsTotaisFaturaDataNumerario: TStringField;
    cdsTotaisFaturaTotalNumerario: TBCDField;
    cdsTotaisFaturaTotalDespesa: TFMTBCDField;
    cdsTotaisFaturaTotalFatura: TBCDField;
    ppTotaisFatura: TppDBPipeline;
    dsNumerario: TDataSource;
    dspNumerario: TDataSetProvider;
    cdsNumerario: TClientDataSet;
    ppNumerario: TppDBPipeline;
    CapaBrokerDT_ENTRADA: TDateTimeField;
    cdsCapaBrokerDT_ENTRADA: TDateTimeField;
    CapaBrokerTIPO_DOC: TStringField;
    CapaBrokerNR_DOC: TStringField;
    cdsCapaBrokerTIPO_DOC: TStringField;
    cdsCapaBrokerNR_DOC: TStringField;
    CapaMyIndaiaV2NOME_INDAIA: TStringField;
    CapaMyIndaiaV2END_INDAIA: TStringField;
    CapaMyIndaiaV2CIDADE_INDAIA: TStringField;
    CapaMyIndaiaV2CEP_INDAIA: TStringField;
    CapaMyIndaiaV2TELFAX_INDAIA: TStringField;
    CapaMyIndaiaV2CPNJ: TStringField;
    cdsCapaMyIndaiaV2NOME_INDAIA: TStringField;
    cdsCapaMyIndaiaV2END_INDAIA: TStringField;
    cdsCapaMyIndaiaV2CIDADE_INDAIA: TStringField;
    cdsCapaMyIndaiaV2CEP_INDAIA: TStringField;
    cdsCapaMyIndaiaV2TELFAX_INDAIA: TStringField;
    cdsCapaMyIndaiaV2CPNJ: TStringField;
    TotaisFaturaTpFatura: TStringField;
    cdsTotaisFaturaTpFatura: TStringField;
    TotaisFaturavalorTibutavel: TBCDField;
    cdsTotaisFaturavalorTibutavel: TBCDField;
    Numerario: TADOQuery;
    Numerarioid: TLargeintField;
    NumerarioDataNumerario: TStringField;
    NumerarioTotalNumerario: TBCDField;
    cdsNumerarioid: TLargeintField;
    cdsNumerarioDataNumerario: TStringField;
    cdsNumerarioTotalNumerario: TBCDField;
    CapaBrokerDT_DESEMBARACO: TDateTimeField;
    CapaBrokerNM_LOCAL_DESEMBARQUE: TStringField;
    CapaBrokerVL_PESO_BRUTO: TFloatField;
    CapaBrokerVL_PESO_LIQUIDO: TFloatField;
    cdsCapaBrokerDT_DESEMBARACO: TDateTimeField;
    cdsCapaBrokerNM_LOCAL_DESEMBARQUE: TStringField;
    cdsCapaBrokerVL_PESO_BRUTO: TFloatField;
    cdsCapaBrokerVL_PESO_LIQUIDO: TFloatField;
    CapaBrokerNM_AGENTE: TStringField;
    cdsCapaBrokerNM_AGENTE: TStringField;
    CapaBrokerNM_DESPACHO: TStringField;
    CapaBrokerNM_EXPORTADOR: TStringField;
    cdsCapaBrokerNM_DESPACHO: TStringField;
    cdsCapaBrokerNM_EXPORTADOR: TStringField;
    TotaisFaturaHonorário: TFMTBCDField;
    TotaisFaturair: TBCDField;
    TotaisFaturacofins: TBCDField;
    cdsTotaisFaturaHonorário: TFMTBCDField;
    cdsTotaisFaturair: TBCDField;
    cdsTotaisFaturacofins: TBCDField;
    TotaisFaturaTotalDescontadoImposto: TFMTBCDField;
    cdsTotaisFaturaTotalDescontadoImposto: TFMTBCDField;
    Consolidado: TADOQuery;
    ConsolidadoHonorario: TFMTBCDField;
    ConsolidadoIr: TFMTBCDField;
    ConsolidadoCofins: TFMTBCDField;
    ConsolidadoTotalFatServico: TFMTBCDField;
    dspConsolidado: TDataSetProvider;
    cdsConsolidado: TClientDataSet;
    dsConsolidado: TDataSource;
    cdsConsolidadoHonorario: TFMTBCDField;
    cdsConsolidadoIr: TFMTBCDField;
    cdsConsolidadoCofins: TFMTBCDField;
    cdsConsolidadoTotalFatServico: TFMTBCDField;
    ppConsolidado: TppDBPipeline;
    ConsolidadoTotaServicos: TFMTBCDField;
    ConsolidadoTotalFatDespesa: TFMTBCDField;
    ConsolidadoTotalConsolidado: TFMTBCDField;
    cdsConsolidadoTotaServicos: TFMTBCDField;
    cdsConsolidadoTotalFatDespesa: TFMTBCDField;
    cdsConsolidadoTotalConsolidado: TFMTBCDField;
    ItensDocumentoValorItemCliente: TFMTBCDField;
    cdsItensDocumentoValorItemCliente: TFMTBCDField;
    Faturamentoobs: TStringField;
    cdsFaturamentoobs: TStringField;
    NumerarioSomaNumerario: TFMTBCDField;
    cdsNumerarioSomaNumerario: TFMTBCDField;
    ConsolidadoIss: TFMTBCDField;
    cdsConsolidadoIss: TFMTBCDField;
    TotaisFaturaiss: TBCDField;
    cdsTotaisFaturaiss: TBCDField;
    cdsModelosDocumentosCD_TIPO_DOCTO: TIntegerField;
    ModelosDocumentosCD_TIPO_DOCTO: TIntegerField;
    Reembolso: TADOQuery;
    Reembolsoname: TStringField;
    ReembolsoValorReembolso: TFMTBCDField;
    dspReembolso: TDataSetProvider;
    dsReembolso: TDataSource;
    cdsReembolso: TClientDataSet;
    cdsReembolsoname: TStringField;
    cdsReembolsoValorReembolso: TFMTBCDField;
    ppReembolso: TppDBPipeline;
    ConsolidadoTotalGeral: TFMTBCDField;
    cdsConsolidadoTotalGeral: TFMTBCDField;
    NumerarioSeniorKey: TWideStringField;
    cdsNumerarioSeniorKey: TWideStringField;
    ItensDocsemImposto: TADOQuery;
    dspItensDocsemImposto: TDataSetProvider;
    dsItensDocsemImposto: TDataSource;
    cdsItensDocsemImposto: TClientDataSet;
    ItensDocsemImpostoItem: TWideStringField;
    ItensDocsemImpostovaloritemCliente: TIntegerField;
    ItensDocsemImpostovalorItem: TFMTBCDField;
    cdsItensDocsemImpostoItem: TWideStringField;
    cdsItensDocsemImpostovaloritemCliente: TIntegerField;
    cdsItensDocsemImpostovalorItem: TFMTBCDField;
    ppItensDocsemImposto: TppDBPipeline;
    FaturamentoANO_BASF: TStringField;
    cdsFaturamentoANO_BASF: TStringField;
    CapaBrokerFATURA_PROCESSO: TStringField;
    cdsCapaBrokerFATURA_PROCESSO: TStringField;
    CapaBrokerNR_CONHECIMENTO: TStringField;
    cdsCapaBrokerNR_CONHECIMENTO: TStringField;
    ConsolidadoNumerario: TADOQuery;
    dspConsolidadoNumerario: TDataSetProvider;
    cdsConsolidadoNumerario: TClientDataSet;
    dsConsolidadoNumerario: TDataSource;
    ppConsolidadoNumerario: TppDBPipeline;
    ConsolidadoNumerarioHONORARIO: TFMTBCDField;
    ConsolidadoNumerarioIR: TFMTBCDField;
    ConsolidadoNumerarioCOFINS: TFMTBCDField;
    ConsolidadoNumerarioISS: TFMTBCDField;
    ConsolidadoNumerarioTOTASERVICOS: TFMTBCDField;
    ConsolidadoNumerarioTOTALFATSERVICO: TFMTBCDField;
    ConsolidadoNumerarioSOMANUMERARIO: TFMTBCDField;
    ConsolidadoNumerarioTOTALCONSOLIDADO: TFMTBCDField;
    ConsolidadoNumerarioTOTALGERAL: TFMTBCDField;
    ConsolidadoNumerarioTOTALFATDESPESA: TFMTBCDField;
    cdsConsolidadoNumerarioHONORARIO: TFMTBCDField;
    cdsConsolidadoNumerarioIR: TFMTBCDField;
    cdsConsolidadoNumerarioCOFINS: TFMTBCDField;
    cdsConsolidadoNumerarioISS: TFMTBCDField;
    cdsConsolidadoNumerarioTOTASERVICOS: TFMTBCDField;
    cdsConsolidadoNumerarioTOTALFATSERVICO: TFMTBCDField;
    cdsConsolidadoNumerarioSOMANUMERARIO: TFMTBCDField;
    cdsConsolidadoNumerarioTOTALCONSOLIDADO: TFMTBCDField;
    cdsConsolidadoNumerarioTOTALGERAL: TFMTBCDField;
    cdsConsolidadoNumerarioTOTALFATDESPESA: TFMTBCDField;
    dsNumerarioConsolidado: TDataSource;
    ppNumerarioConsolidado: TppDBPipeline;
    cdsNumerarioConsolidado: TClientDataSet;
    dspNumerarioConsolidado: TDataSetProvider;
    NumerarioConsolidado: TADOQuery;
    NumerarioConsolidadoID: TLargeintField;
    NumerarioConsolidadoDATANUMERARIO: TStringField;
    NumerarioConsolidadoTOTALNUMERARIO: TBCDField;
    NumerarioConsolidadoSOMANUMERARIO: TFMTBCDField;
    NumerarioConsolidadoSENIORKEY: TWideStringField;
    cdsNumerarioConsolidadoID: TLargeintField;
    cdsNumerarioConsolidadoDATANUMERARIO: TStringField;
    cdsNumerarioConsolidadoTOTALNUMERARIO: TBCDField;
    cdsNumerarioConsolidadoSOMANUMERARIO: TFMTBCDField;
    cdsNumerarioConsolidadoSENIORKEY: TWideStringField;
    ppHeaderBand1: TppHeaderBand;
    ppDetailBand1: TppDetailBand;
    ppDBText33: TppDBText;
    ppDBText36: TppDBText;
    ppFooterBand1: TppFooterBand;
    SubNumerario: TppSubReport;
    ppChildReport1: TppChildReport;
    ppTitleBand1: TppTitleBand;
    ppDetailBand2: TppDetailBand;
    ppDBText52: TppDBText;
    ppLabel47: TppLabel;
    ppDBText53: TppDBText;
    ppDBText54: TppDBText;
    ppDBText41: TppDBText;
    ppFooterBand2: TppFooterBand;
    ppSummaryBand2: TppSummaryBand;
    ppDBText39: TppDBText;
    ppDBText44: TppDBText;
    R1: TppRegion;
    ppDBText50: TppDBText;
    ppDBText51: TppDBText;
    ppLabel58: TppLabel;
    ppLabel59: TppLabel;
    ppLabel1: TppLabel;
    RegISS: TppRegion;
    ppLabel60: TppLabel;
    ppDBText35: TppDBText;
    R2: TppRegion;
    ppDBText61: TppDBText;
    ppDBText63: TppDBText;
    ppDBText65: TppDBText;
    ppLine47: TppLine;
    ppDBText47: TppDBText;
    ppDBText34: TppDBText;
    ppPageStyle2: TppPageStyle;
    ppLine50: TppLine;
    ppLabel10: TppLabel;
    ppLabel46: TppLabel;
    ppLabel57: TppLabel;
    ppImage8: TppImage;
    ppLine51: TppLine;
    ppLine52: TppLine;
    ppLine53: TppLine;
    ppLine54: TppLine;
    ppLine58: TppLine;
    ppLine61: TppLine;
    ppLine62: TppLine;
    ppLine63: TppLine;
    ppLine64: TppLine;
    ppLine65: TppLine;
    ppLine66: TppLine;
    ppLine67: TppLine;
    ppLine68: TppLine;
    ppLine69: TppLine;
    ppLine70: TppLine;
    ppLine71: TppLine;
    ppLine72: TppLine;
    ppLabel61: TppLabel;
    ppLine73: TppLine;
    ppLine74: TppLine;
    ppLine75: TppLine;
    ppLine76: TppLine;
    ppLine77: TppLine;
    ppLabel62: TppLabel;
    ppLabel64: TppLabel;
    ppLine78: TppLine;
    ppLine79: TppLine;
    ppLine80: TppLine;
    ppLine81: TppLine;
    ppLine82: TppLine;
    ppLine83: TppLine;
    ppLine84: TppLine;
    ppLine85: TppLine;
    ppLine86: TppLine;
    ppLine87: TppLine;
    ppLine88: TppLine;
    ppLine89: TppLine;
    ppLine90: TppLine;
    ppLine91: TppLine;
    ppLine92: TppLine;
    ppLine93: TppLine;
    ppLabel66: TppLabel;
    ppLabel67: TppLabel;
    ppLabel68: TppLabel;
    ppLabel69: TppLabel;
    ppLabel70: TppLabel;
    ppLabel73: TppLabel;
    ppLabel74: TppLabel;
    ppLabel75: TppLabel;
    ppLabel76: TppLabel;
    ppLabel77: TppLabel;
    ppLabel78: TppLabel;
    ppLabel79: TppLabel;
    ppLabel80: TppLabel;
    ppLabel81: TppLabel;
    ppLabel82: TppLabel;
    ppLabel83: TppLabel;
    ppLabel84: TppLabel;
    ppLabel85: TppLabel;
    ppLabel86: TppLabel;
    ppLabel87: TppLabel;
    ppLabel88: TppLabel;
    ppLabel89: TppLabel;
    ppLabel90: TppLabel;
    ppLabel91: TppLabel;
    ppLabel92: TppLabel;
    ppLabel93: TppLabel;
    ppLabel94: TppLabel;
    ppLabel97: TppLabel;
    ppLabel98: TppLabel;
    ppLabel100: TppLabel;
    ppLabel104: TppLabel;
    ppLabel107: TppLabel;
    ppLabel109: TppLabel;
    ppDBText1: TppDBText;
    ppLabel113: TppLabel;
    ppLabel114: TppLabel;
    ppDBText2: TppDBText;
    ppLine11: TppLine;
    ppLine14: TppLine;
    ppLine16: TppLine;
    ppLabel2: TppLabel;
    Cancelado: TppLabel;
    ppLabel5: TppLabel;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppDBText3: TppDBText;
    ppDBText4: TppDBText;
    ppDBText5: TppDBText;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBText14: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppDBText20: TppDBText;
    ppDBText21: TppDBText;
    ppDBText22: TppDBText;
    ppDBText23: TppDBText;
    ppDBText24: TppDBText;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppDBText27: TppDBText;
    ppDBText28: TppDBText;
    ppDBText29: TppDBText;
    ppDBText30: TppDBText;
    ppDBText31: TppDBText;
    ppDBText32: TppDBText;
    ppLabel116: TppLabel;
    ppLabel117: TppLabel;
    ppDBText57: TppDBText;
    ppDBText40: TppDBText;
    ppLabel119: TppLabel;
    ppDBText46: TppDBText;
    ppDBText48: TppDBText;
    ppDBText55: TppDBText;
    ppLabel120: TppLabel;
    ppLabel121: TppLabel;
    ppLabel122: TppLabel;
    ppLabel123: TppLabel;
    ppLabel124: TppLabel;
    ppLabel125: TppLabel;
    ppDBText58: TppDBText;
    ppDBText59: TppDBText;
    ppLabel126: TppLabel;
    ppDBText62: TppDBText;
    ppDBText64: TppDBText;
    ppDBText66: TppDBText;
    ppLabel3: TppLabel;
    ppDBText42: TppDBText;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppGroup3: TppGroup;
    ppGroupHeaderBand3: TppGroupHeaderBand;
    ppDBMemo2: TppDBMemo;
    ppLabel4: TppLabel;
    ppGroupFooterBand3: TppGroupFooterBand;
    ppDBText37: TppDBText;
    ppDBText38: TppDBText;
    ppDBText43: TppDBText;
    ppLabel6: TppLabel;
    CapaBrokerIMPORTADOR: TStringField;
    cdsCapaBrokerIMPORTADOR: TStringField;

    procedure DataModuleCreate(Sender: TObject);
    procedure ReportBeforePrint(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dtmDocumentosFaturamento: TdtmDocumentosFaturamento;

implementation

{$R *.dfm}

uses
   DadosFaturamentoERP,Global;

procedure TdtmDocumentosFaturamento.DataModuleCreate(Sender: TObject);
begin
  if cdsCapaMyIndaiaV2.Active then
    cdsCapaMyIndaiaV2.Close;
  cdsCapaMyIndaiaV2.Params.ParamByName('idFatura').AsInteger:=dtmFaturamentoERP.qryFaturasid.AsInteger;
  cdsCapaMyIndaiaV2.Open;

  if cdsFaturamento.Active then
    cdsFaturamento.Close;
  cdsFaturamento.Params.ParamByName('Nota').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
  cdsFaturamento.Open;

  if cdsCapaBroker.Active then
    cdsCapaBroker.Close;
 cdsCapaBroker.Params.ParamByName('ProcessoID').AsInteger := Parametros.Processoid;
 cdsCapaBroker.Open;

 if cdsItensDocsemImposto.Active then
    cdsItensDocsemImposto.Close;
 cdsItensDocsemImposto.Params.ParamByName('idFatura').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
 cdsItensDocsemImposto.Open;

  if cdsItensDocumento.Active then
    cdsItensDocumento.Close;
  cdsItensDocumento.Params.ParamByName('idFatura').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
  cdsItensDocumento.Open;

 if cdsTotaisFatura.Active then
    cdsTotaisFatura.Close;
 cdsTotaisFatura.Params.ParamByName('idFatura').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
 cdsTotaisFatura.Open;

 if cdsNumerario.Active then
    cdsNumerario.Close;
 cdsNumerario.Params.ParamByName('idFatura').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
 cdsNumerario.Open;

  if cdsConsolidado.Active then
    cdsConsolidado.Close;
 cdsConsolidado.Params.ParamByName('ProcessoID').AsInteger := Parametros.Processoid;
 cdsConsolidado.Params.ParamByName('idFatura').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
 cdsConsolidado.Open;

   if cdsConsolidadoNumerario.Active then
    cdsConsolidadoNumerario.Close;
 cdsConsolidadoNumerario.Params.ParamByName('ProcessoID').AsInteger := Parametros.Processoid;
 cdsConsolidadoNumerario.Params.ParamByName('idFatura').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
 cdsConsolidadoNumerario.Open;

   if cdsNumerarioConsolidado.Active then
    cdsNumerarioConsolidado.Close;
 cdsNumerarioConsolidado.Params.ParamByName('idFatura').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
 cdsNumerarioConsolidado.Open;

   if cdsReembolso.Active then
    cdsReembolso.Close;
 cdsReembolso.Params.ParamByName('billing_id').AsInteger := dtmFaturamentoERP.qryFaturasid.AsInteger;
 cdsReembolso.Open;

 cdsModelosDocumentos.Close;
 cdsModelosDocumentos.Open;
end;

procedure TdtmDocumentosFaturamento.ReportBeforePrint(Sender: TObject);
begin
  if dtmDocumentosFaturamento.FindComponent('Cancelado') <> nil then
  begin
    if dtmFaturamentoERP.qryFaturasstatus.AsString='CLOSED'  then
      TppRegion(dtmDocumentosFaturamento.FindComponent('Cancelado')).Visible := True
    else
      TppRegion(dtmDocumentosFaturamento.FindComponent('Cancelado')).Visible := False;
  end;
end;

end.
